fetchai/agents-aea

- aea/channel/gym.py
- aea/protocols/gym/__init__.py
- aea/protocols/gym/message.py
- aea/protocols/gym/serialization.py
- tests/test_channel/test_gym.py
- tests/test_channel/test_local/test_misc.py
- tests/test_channel/test_local/test_search_services.py
- tests/test_channel/test_oef.py
- tests/test_protocols/test_base.py
- tox.ini
This PR provides:
- a new 'gym' channel to connect the aea with a gym.Env
- a new 'gym' protocol for interaction with the 'gym' channel and environment
It addresses a feature request on fetchai/agents-tac (https://github.com/fetchai/agents-tac/issues/364)
The gym protocol does not implement an error code. It is probably preferable to have the code fail loudly rather than implement error handling.
> Add gym protocol and channel

- aea/protocols/gym/serialization.py
- tests/test_channel/test_gym.py
This PR fixes the serialization module of the Gym protocol by handling the `step_id` field properly.
None.
None.
> Fix `step_id` field in Gym protocol.

- aea/protocols/base/message.py
- aea/protocols/default/message.py
- aea/protocols/default/serialization.py
- aea/protocols/oef/message.py
- aea/protocols/oef/serialization.py
- aea/protocols/tac/message.py
- aea/protocols/tac/serialization.py
- aea/protocols/tac/tac.proto
- aea/protocols/tac/tac_pb2.py
- tests/test_protocols/test_tac.py
Use the same approach for representing a message type in a protocol, across protocols. That is, use a Python enumeration for a message type when the message is still a Python object. Then, encode/decode accordingly, depending on the serialization method.
E.g. for `protocol_id="default"`, the field `"type"` in the `DefaultMessage` body gives a `DefaultMessage.Type` object. 
None.
None.
> Fix message type representation and serialization.

- Pipfile
- Pipfile.lock
- setup.py
For some reason, the `oef` package needs the `colorlog` package, but it's not declared in the `oef` dependencies and so it's not automatically installed.
None.
None.
> Fix the missing 'colorlog' dependency required by 'oef'.

- aea/aea.py
- aea/channel/oef.py
- aea/cli/__main__.py
- aea/cli/common.py
- aea/cli/run.py
- aea/skills/base.py
- examples/echo_skill/skill.yaml
This PR adds a new section to the agent's configuration file, `connections`, to explicitly declare which connections are available to an AEA agent.
Also, the user can switch between connections by using `aea run --connection <connection-name>`.
Fixes #41 
None.
> Add connections section in the configuration file.

- setup.py
This PR aims to split the dependencies of the channel supported by the framework.
In particular, the dependencies for the `GymChannel` in `aea.channel.gym` and the `OEFChannel` in `aea.channel.oef` have been put in two different extra dependencies, installable via `pip install aea[gym-channel]` and `pip install aea[oef-channel]`, respectively.
None.
None.
> Add channel extras for the Gym channel and the OEF channel.

- aea/skills/base/core.py
- examples/gym_skill/handler.py
- examples/gym_skill/helpers.py
- examples/gym_skill/tasks.py
With this PR, the code from another module defined in the skill folder can be imported using the skill name + `_skill` as package name.
For example, if you want to import a function 'bar' defined in a module 'foo.py' in the skill 'foobar':
```
from foobar_skill.foo import bar
```
Solves a problem related to issue #48 .
None.
> make skill packages importable.

- aea/aea.py
- aea/channels/oef.py
- aea/cli/run.py
With this PR when the connection to the OEF node fails, a `ConnectionError` exception is raised.
This is useful because then the method can gracefully stop the AsyncioCore launched to make the attempt to establish the connection, in case an error occurs.
Fixes #85 
We could later add the `ConnectionError` exception to every `.+Connection.connect()` method.
> add exception handling to OEFConnection.connect()

- Jenkinsfile
- Makefile
- tox.ini
This PR adds two test environments:
- `docs`: checks that the documentation can be built without errors.
- `docs-serve`: builds the documentations and serves it using `mkdocs serve` This is just for development purposes.
They can be run, respectively, with `tox -e docs` and `tox -e docs-serve`.
`tox` will run `docs`, but not `docs-serve`.
Moreover, the documentation building has been added to the CI pipeline.
None.
Inspired by [this page](https://tox.readthedocs.io/en/latest/example/documentation.html#mkdocs).
Also, worth investigating the `mkdocs gh-deploy` command used in the linked page.
> Add 'docs' and 'docs-serve' environments in tox.ini.

- tox.ini
The 'docs' test environment in `tox.ini` didn't explicitly declare all the `mkdocs` dependencies to build the documentation. In particular, `mkdocs-material` and `pymdown-extentions`.
This PR adds the above-mentioned dependencies, making `tox -e docs` work again.
An alternative might be to run a `pipenv install --dev`  before `mkdocs build --clean`. But we don't need all the packages declared in the `Pipfile` to successfully run the tests.
> fix docs testenv.

- aea/cli/add.py
- aea/cli/remove.py
- tests/test_cli/test_commands/test_add/__init__.py
- tests/test_cli/test_commands/test_add/test_connection.py
- tests/test_cli/test_commands/test_add/test_protocol.py
- tests/test_cli/test_commands/test_add/test_skill.py
- tests/test_cli/test_commands/test_remove/__init__.py
- tests/test_cli/test_commands/test_remove/test_connection.py
- tests/test_cli/test_commands/test_remove/test_protocol.py
- tests/test_cli/test_commands/test_remove/test_skill.py
This PR aims to get 100% test coverage on the `aea.cli` modules.
None.
None.
> (WIP) Test `aea.cli.*` modules.

- aea/__init__.py
- aea/configurations/loader.py
- tests/conftest.py
Due to the upgrade of MyPy from version 0.720 to 0.730, MyPy raised errors about how we get the current path of a module. Add 'type: ignore' to solve the issue, since the risk is minimal.
Fixes #140 
None.
> fix mypy errors when getting the current frame of a module.

- deploy-image/Dockerfile
- deploy-image/README.md
- deploy-image/docker-env.sh
- deploy-image/scripts
This PR adds a new Docker image for AEA deployment.
It contains all the dependencies needed to install the `aea` package, as well as some popular skill dependencies (e.g. the `gym` skill and the `oef` protocol.)
Fixes #141 
None.
> Add Docker image for AEA deployment

- aea/cli/add.py
- aea/cli/common.py
- aea/configurations/base.py
- aea/configurations/loader.py
- aea/configurations/schemas/connection-config_schema.json
- aea/configurations/schemas/protocol-config_schema.json
- aea/protocols/base.py
- aea/registries/base.py
- tests/test_cli/test_commands/test_add/test_protocol.py
This PR adds the `ProtocolConfig` class (analogous to the other `*Config` classes) and the loading of such `protocols/<protocol_name>/protocol.yaml` configuration files during the AEA setup.
fixes #115 
Tests are missing.
> Add `ProtocolConfig` class and parsing of protocol configuration files.

- aea/registries/base.py
Fix the issue of improper loading of folders (e.g. '.DS_Store')
by filtering out all the files/directories that don't match with
a package Python name.
Why? Because if that's not the case, the component cannot be used in an 'import' statement.
In the future, there might be the need to have a 'ignore' file with all the known patterns whose matching string shouldn't be considered correct.
Fixes #114 
None.
> Use regex in order to filter out bad package names.

- aea/cli/__main__.py
- aea/cli/common.py
- aea/cli/run.py
- aea/configurations/base.py
- now every time `aea run` is executed, all the dependencies of the components are gathered together and installed via the current interpreter's pip module.
- `aea freeze` will instead print on stdout the list of gathered dependencies.
Fixes #128 and #152 
None.
> Gather dependencies and install them in 'aea run'. Add 'aea freeze'

- aea/configurations/loader.py
- aea/configurations/schemas/connection-config_schema.json
- aea/configurations/schemas/definitions.json
- aea/configurations/schemas/protocol-config_schema.json
- aea/configurations/schemas/skill-config_schema.json
- tests/test_cli/test_schema.py
This PR helps in the handling of complex schemas.
Now it's possible to easily reference parts of schemas between files. The only condition is that the root of the URI is `aea/configurations/schemas/`.
E.g. look at the `"dependencies"` schema definitions:
```
"dependencies": {
"type": "array",
"uniqueItems": true,
"items": { "$ref": "definitions.json#/definitions/requirement" }
}
```
it is an array of `"requirement"` object. This schema is defined in `aea/configurations/schemas/definitions.json`.
Fixes #154 
None.
> Reference a schema from another file.

- aea/configurations/base.py
- aea/configurations/schemas/skill-config_schema.json
- aea/skills/base.py
- tests/data/dummy_aea/skills/dummy/skill.yaml
- tests/test_cli/test_commands/test_create.py
This PR makes the fields `args` in  `handler`, `behaviour`, `task`, and `shared_classe` of `skill.yaml` optional.
Fixes #166 
None.
> Make skill resources 'args' field optional in config file 'skill.yaml'

- aea/cli/__main__.py
- aea/cli/install.py
- aea/cli/run.py
- docs/cli-commands.md
This PR adds the subcommand `aea install` to install dependencies explicitly.
Moreover, they are not installed by default when `aea run`.
Fixes #167 
Should we add a `aea run --install-deps` to force the installation when launching the agent?
> Add 'aea install [-r requirement]' subcommand

- aea/cli/__main__.py
- aea/cli/common.py
- aea/cli/list.py
- aea/cli/search.py
- aea/configurations/base.py
- aea/configurations/schemas/aea-config_schema.json
- docs/logging.md
- mkdocs.yml
This PR adds an option to `aea` command: `-l/--logfile log_file_path` It will save the logs of every subcommand of `aea` to the specified file.
Fixes #178 
None.
> Save `aea` logs to file.

- Pipfile
- Pipfile.lock
- aea/cli/common.py
- aea/cli/run.py
- aea/configurations/loader.py
- aea/connections/oef/connection.yaml
- mypy.ini
- setup.py
This PR adds the following two features:
- makes the configuration loader to resolve environment variables by using the process environment. In particular, it allows for variables in the following format: `${VAR_NAME:default_value}`. E.g.: `${OEF_ADDR:127.0.0.1}`.
- let the user load an environment file when doing `aea run --env ENV_FILE_PATH`. By default, the `ENV_FILE_PATH` is `.env`.
First of all, do `aea create myagent` and then `cd myagent`.
Notice that in `connection.yaml` the field `config` contains:
```
config:
addr: ${OEF_ADDR:127.0.0.1}
port: ${OEF_PORT:10000}
```
Then, assuming an OEF node is listening at `127.0.0.1:10000`, all the following approaches should work:
1. `aea -v DEBUG run`  gives the output:
```
...
do connected finished
on_connect_ok[139647330480928] …
```
> Load .env file and resolve variable names in .yaml files. 

- aea/cli_gui/__main__.py
- aea/configurations/schemas/aea-config_schema.json
- aea/configurations/schemas/connection-config_schema.json
- aea/configurations/schemas/definitions.json
- aea/configurations/schemas/protocol-config_schema.json
- aea/configurations/schemas/skill-config_schema.json
- aea/connections/scaffold/connection.yaml
- aea/protocols/scaffold/protocol.yaml
- aea/skills/base.py
- aea/skills/scaffold/skill.yaml
- packages/protocols/tac/serialization.py
- packages/skills/tac/game.py
- packages/skills/tac/handlers.py
- packages/skills/tac/search.py
- packages/skills/tac/skill.yaml
- tests/test_cli/test_commands/test_create.py
- tests/test_cli/test_schema.py
Fix an importing issue in the `tac` skill/protocol.
Also, fix a more general issue of the framework. In particular:
- enforce at schema level the resource names to be at least of length `1`
- enforce at schema level the resource names to be compatible as Python module names.
None.
None/
> Enforce good resource names at schema level

- aea/cli/__main__.py
- setup.py
make 'cli_gui' extra depend on 'cli' and not the other way around.
In this way, we have `cli_gui` as an extra (installable through `pip install aea[cli_gui]`).
This will let us to include `"connexion[swagger-ui] @ git+https://github.com/neverpanic/connexion.git@jsonschema-3#egg=connexion[swagger-ui]"` as an (extra) direct dependency and hence allow the release to PyPI.
None.
None.
> make 'cli_gui' depend on 'cli' and not the other way around.

- Pipfile
- Pipfile.lock
- aea/cli/__main__.py
- aea/cli/common.py
- aea/cli/loggers.py
- setup.py
- tests/conftest.py
- tests/test_aea.py
- tests/test_cli/test_commands/test_add/test_connection.py
- tests/test_cli/test_commands/test_add/test_protocol.py
- tests/test_cli/test_commands/test_add/test_skill.py
- tests/test_cli/test_commands/test_create.py
- tests/test_cli/test_commands/test_delete.py
- tests/test_cli/test_commands/test_remove/test_connection.py
- tests/test_cli/test_commands/test_remove/test_protocol.py
- tests/test_cli/test_commands/test_remove/test_skill.py
Put log messages to stdout with default config.
this change implied removing the 'click_log' dependency and
reimplementing part of the functionalities that the package provided.
fixes #236 
None
> Put log messages to stdout with default config.

- Jenkinsfile
- aea/registries/base.py
- aea/skills/base.py
- tests/conftest.py
- tests/test_cli/test_commands/test_gui.py
- tests/test_cli/test_commands/test_run.py
- tox.ini
make tests pass with Python 3.6.
Tests that use `oef` SDK must be skipped because it seems there's a compatibility problem.
Fixes #139 
None.
> make tests pass with Python 3.6

- Jenkinsfile
Proposing to add a pipeline timeout of 2 hours to ensure that Jenkins job will abort after a finite amount of time and not block execution slots.
* 
*
> add pipeline timeout to Jenkinsfile

- aea/connections/oef/connection.py
- tests/test_connections/test_oef/test_communication.py
Supports the new FIPA performatives `ACCEPT_W_ADDRESS`, `MATCH_ACCEPT_W_ADDRESS`, `INFORM` in oef connection.
-
> Support new fipa performatives in oef connection, fixes #250

- aea/crypto/ledger_apis.py
- aea/protocols/fipa/message.py
- examples/weather_skills/README.md
- packages/skills/weather_client_ledger/behaviours.py
- packages/skills/weather_client_ledger/dialogues.py
- packages/skills/weather_client_ledger/handlers.py
- packages/skills/weather_client_ledger/skill.yaml
- packages/skills/weather_client_ledger/strategy.py
- packages/skills/weather_station_ledger/behaviours.py
- packages/skills/weather_station_ledger/dialogues.py
- packages/skills/weather_station_ledger/handlers.py
- packages/skills/weather_station_ledger/skill.yaml
- packages/skills/weather_station_ledger/strategy.py
This PR:
- streamlines the weather skills
- exposes ledger api presence
- changes dialogue management
It addresses #353 
-
> Streamline weather skills with ledger and dialogue management

- aea/crypto/ledger_apis.py
- setup.cfg
- tests/test_crypto/test_ledger_apis.py
100% coverage on aea/cryptos/ledger_api module.
> 100% on ledger_apis module

- aea/aea.py
- aea/context/base.py
- aea/skills/base.py
- tests/test_aea.py
Thi PR exposes the connection status to the skill context.
It addresses #358.
In the future - once we have the multiplexer - we can collect each connection's status in a `ConnectionStatuses` object. Then we can also add additional information, like `reconnection` counts etc.
#358 asks for the ledger api status to also be exposed. However, the entire ledger api is accessible via the context so no further work is required there.
> Add is connected status to skill context

- packages/skills/weather_station/behaviours.py
- packages/skills/weather_station/skill.yaml
- packages/skills/weather_station_ledger/behaviours.py
- packages/skills/weather_station_ledger/skill.yaml
The OEF operates a transient registry (and is error prone). This PR addresses the fact and changes the registration behaviour in the remaining skills such that the agent's services are occasionally update (deregistered/reregistered) on the OEF.
It addresses #391 
-
> Adds services updating on OEF to all skills

- tests/test_decision_maker/test_base.py
Just added a couple of lines in order to test a logger.warning that we had in the decision_maker.
Nothing
> 100% coverage on decision maker

- aea/agent.py
- aea/mail/base.py
After the change from `MailBox` to `Multiplexer` (PR # #376 and #422 ), `OutBox.put`
and `OutBox.put_message` are blocking methods if the multiplexer is not running.
However, that casues issues when a skill in a teardown method of some Behaviour tries to use the connection to send the last messages, as it happened in #426.
To fix this problem, the `Agent.start` and `Agent.stop` should initialize and tear down resources in a mirrored way.
That is:
```
Agent.start():
1) set connections up
2) set skills up
3) liveness to True
```
```
Agent.stop():
3) liveness to False
2) tear skills down
1) tear connections down
```
That wasn't the case before this commit. Indeed, the `Agent.stop()` method was:
```
Agent.stop():
3) liveness to False
1) tear connections down
2) tear skills down
```
But if the …
> Update Agent.stop method with new outbox.put_message semantics.

- examples/gym_ex/proxy/env.py
- examples/gym_ex/rl/agent.py
- examples/gym_ex/train.py
- tests/test_examples/test_gym_ex.py
After the recent change of API (from `MailBox` to `Multiplexer`), the Gym example stopped working. This was because the multiplexer requires that it is connected before using `OutBox.put`. However, in the Gym example, the interleaving of the main thread (that executes `RLAgent.fit`) and the agent thread caused that the outbox was used before the multiplexer was fully set up.
> Fix Gym example and associated test.

- aea/decision_maker/messages/transaction.py
- aea/protocols/fipa/fipa.proto
- aea/protocols/fipa/fipa_pb2.py
- aea/protocols/fipa/message.py
- aea/protocols/fipa/serialization.py
- docs/tac-skills.md
- packages/skills/carpark_client/handlers.py
- packages/skills/carpark_detection/handlers.py
- packages/skills/tac_negotiation/handlers.py
- packages/skills/weather_client/handlers.py
- packages/skills/weather_client_ledger/handlers.py
- packages/skills/weather_station/handlers.py
- packages/skills/weather_station_ledger/handlers.py
- tests/data/dummy_aea/protocols/fipa/fipa.proto
- tests/data/dummy_aea/protocols/fipa/fipa_pb2.py
- tests/data/dummy_aea/protocols/fipa/message.py
- tests/data/dummy_aea/protocols/fipa/serialization.py
- tests/test_connections/test_oef/test_communication.py
- tests/test_protocols/test_fipa.py
This PR:
- refactors fipa to include `W_INFORM` rather than `W_ADDRESS`. This makes it more versatile and is needed for TAC.
Related to #214 
-
> Refactor the fipa protocol to include inform component

- aea/cli/install.py
- aea/configurations/base.py
- aea/configurations/schemas/skill-config_schema.json
- aea/registries/base.py
- aea/skills/base.py
- aea/skills/error/skill.yaml
- aea/skills/scaffold/skill.yaml
- packages/skills/carpark_client/skill.yaml
- packages/skills/carpark_detection/skill.yaml
- packages/skills/echo/skill.yaml
- packages/skills/gym/handlers.py
- packages/skills/gym/skill.yaml
- packages/skills/ml_data_provider/skill.yaml
- packages/skills/ml_train/skill.yaml
- packages/skills/tac_control/skill.yaml
- packages/skills/tac_negotiation/skill.yaml
- packages/skills/tac_participation/skill.yaml
- packages/skills/weather_client/skill.yaml
- packages/skills/weather_client_ledger/skill.yaml
- packages/skills/weather_station/skill.yaml
- packages/skills/weather_station_ledger/skill.yaml
- tests/data/dependencies_skill/skill.yaml
- tests/data/dummy_aea/skills/dummy/skill.yaml
- tests/data/dummy_aea/skills/error/skill.yaml
- tests/data/dummy_skill/skill.yaml
- tests/data/exception_skill/skill.yaml
- tests/test_aea.py
- tests/test_configurations/test_schema.py
- tests/test_packages/test_skills/test_gym.py
- tests/test_registries.py
Before this PR, a skill.yaml would have the following format:
```yaml
...
behaviours:
- behaviour:
class_name: {..}
args: {...}
tasks: [...] # analogous structure as 'behaviours'
handlers: [...] # analogous structure as 'behaviours'
shared_classes: [...] # analogous structure as 'behaviours'
```
That is, the components are listed as 'lists'. Instead, change with the following format:
```yaml
...
behaviours:
behaviour_1_id:
class_name: {...}
args: {...}
...
...
```
The same for the other component types. That means the actual components, e.g. a single behaviour, can be retrived by using its identifier, instead of having an indexing based on the position.
Fixes #205 
_Put an `x` in the boxes …
> Change skill configuration resources types from lists to dictionaries.

- aea/cli/config.py
- tests/test_cli/test_config.py
This PR enhances the commands `aea config get` and `aea config set` by letting the user to specify an arbitrary nested json path. 
The path can only navigate through objects.
Fixes #522 
> Support nested get/set.

- aea/cli/common.py
- aea/cli_gui/__init__.py
- aea/cli_gui/aea_cli_rest.yaml
- aea/cli_gui/templates/home.js
- develop-image/Dockerfile
- tests/test_gui/test_add.py
- tests/test_gui/test_base.py
- tests/test_gui/test_create.py
- tests/test_gui/test_delete.py
- tests/test_gui/test_list.py
- tests/test_gui/test_remove.py
- tests/test_gui/test_run_agent.py
- tests/test_gui/test_run_oef.py
- tests/test_gui/test_scaffold.py
- tests/test_gui/test_search.py
Fix minor issues in the tests relative to the CLI GUI component.
- the main reason of this PR is about some tests that started failing for Python 3.8. Namely:
- `tests/test_gui/test_search.py::test_search_protocols`
- `tests/test_gui/test_search.py::test_search_connections`
- `tests/test_gui/test_search.py::test_list_skills`
Each of them raised the following error:
```
File ".../agents-aea/.tox/py38/lib/python3.8/site-packages/connexion/apis/abstract.py", line 325, in _response_from_handler
raise TypeError(
TypeError: The view function did not return a valid response tuple. The tuple must have the form (body), (body, status, headers), (body, status), or (body, headers).
```
Indeed, the `aea/cli_gui/__init__.py::search_registered_items` returned 4 values instead of the allowed number …
> Fix minor issues in CLI GUI tests.

- aea/cli/remove.py
- tests/test_cli/test_remove/test_connection.py
- tests/test_cli/test_remove/test_protocol.py
- tests/test_cli/test_remove/test_skill.py
Now it is possible to remove packages from their public id.
```
aea remove skill error
aea remove skill fetchai/error:0.1.0  # this now works.
```
The CLI will try to parse the provided package name as if it were a public id. If it fails, it will remove the package with the same name.
Fixes part of #564 
> let 'aea remove' to remove by public id.

- aea/cli/add.py
- aea/cli/registry/fetch.py
- aea/cli/registry/push.py
- aea/cli/registry/utils.py
- aea/configurations/base.py
- tests/test_cli/test_add/test_connection.py
- tests/test_cli/test_add/test_protocol.py
- tests/test_cli/test_add/test_skill.py
- tests/test_cli/test_common.py
- tests/test_cli/test_registry/test_fetch.py
- tests/test_cli/test_registry/test_utils.py
- tests/test_gui/test_add.py
- tests/test_gui/test_run_agent.py
This PR fixes some issues around inconsistent `author` vs `owner` usage. It replaces all occurrences of `owner` with `author` in the codebase.
It addresses #568 
-
> Replaces references of owner with author

- aea/cli/common.py
- aea/cli/run.py
- aea/helpers/base.py
- aea/skills/base.py
This PR fixes some issues of the import system for agent components.
In particular:
- uses the right dotted path (e.g. `packages.protocols.fipa`) for imports.
- make the framework to import the whole connection package, and not only the `connection.py` module.
None
> fix import of agent components.

- aea/registries/base.py
- aea/skills/tasks.py
Handle exception when calling the `teardown` of skill components by logging the exception message with warning level.
This should make the interruption of an agent cleaner, avoiding problems such as the process "hanging" because during the agent teardown the framework couldn't stop a skill component.
In the future, such behaviour can be customized. For instance, do not filter out such errors for some critical components where the fails in the teardown cannot be ignored.
> Handle exceptions when calling 'teardown' of skill components.

- aea/aea.py
- aea/agent.py
- aea/cli/run.py
- docs/hacking-an-agent.md
- tests/test_aea.py
- tests/test_registries.py
- tests/test_skills/test_base.py
- tests/test_skills/test_error.py
This PR fixes the guide to build an agent programmatically. It also adds a flag to an AEA/Agent which lets the developer skip the loading from resource directory stage.
#619 
-
> AEA-267 fix programmatic guide, add programmatic mode flag to aea/agent

- aea/cli/common.py
- aea/cli/create.py
- aea/configurations/schemas/definitions.json
- tests/test_cli/test_create.py
- tests/test_cli/test_search.py
- use regex `[a-zA-Z_][a-zA-Z0-9_]*` instead of `[a-zA-Z0-9_]*` in particular, the empty string is not allowed anymore, and it can contains digits but not at the beginning
- set 'author' as default author. This should be improved when the CLI will have more user's information.
fixes #552 
> Change author regex and use 'author' as default

- aea/aea.py
- aea/decision_maker/base.py
- tests/test_decision_maker/test_base.py
This PR makes the Decision Maker run in its own thread.
Fixes #584 
> AEA-258 make Decision Maker run in its own thread.

- aea/registries/base.py
- aea/skills/base.py
- docs/skill.md
- tests/test_aea.py
This PR adds a special queue in every skill context instance, called `new_behaviours`, that lets the skill code to request the framework for registration of new behaviours.
Fixes #591 
> Let skills register new behaviours.

- tests/test_decision_maker/test_base.py
- tests/test_packages/test_protocols/test_ml_message.py
- tests/test_packages/test_protocols/test_oef_message.py
- tests/test_protocols/test_base.py
Removed any unnecessary check_consistency from tests. I left though the checks that look like this : 
```
with mock.patch.object(OEFMessage.Type, "__eq__", return_value=False):
assert not msg._check_consistency()
```
#643 
> Remove the unnecessary msg._check_consistency from tests

- aea/cli/registry/utils.py
- tests/test_cli/test_publish.py
- tests/test_cli/test_registry/test_publish.py
- tests/test_cli/test_registry/test_push.py
- tests/test_cli/test_registry/test_utils.py
- tests/test_cli/tools_for_testing.py
Test coverage of `aea.cli.registry` subpackage.
#684 
> Feature/registry test coverage [AEA-328]

- aea/aea.py
- aea/agent.py
- aea/cli/run.py
- aea/context/base.py
- aea/decision_maker/base.py
- aea/identity/__init__.py
- aea/identity/base.py
- aea/skills/base.py
- docs/agent-vs-aea.md
- docs/build-aea-programmatically.md
- tests/test_aea.py
- tests/test_agent.py
- tests/test_registries.py
- tests/test_skills/test_base.py
- tests/test_skills/test_error.py
This PR introduces an `Identity` object. This is used by in the agent `Agent(identity, [connections])` and the AEA `AEA(identity, ...)`.
For now, it just contains the name and public key and address (if set). Later, it will also include other identity claims. It is introduced now to be forward compatible to these changes and not break the AEA and Agent constructor when they are extended.
#699 
-
> AEA-354 add identity object to agent and aea

- setup.py
This PR defines a minimal installation of the `aea` package, that includes the following dependencies:
```
PyYAML      # to load configuration files
jsonschema      # to validate configuration files
protobuf      # serialization
watchdog      # stub connection
web3==5.2.2      # ethereum integration
eth-account==0.4.0      # ethereum integration
fetchai-ledger-api==1.0.0rc1      # fetchai integration
```
notice that `click`  and `python-dotenv` of `cli` extra have been removed.
To check that, create a temporary virtual environment, install `aea`, and try to run the AEA programmatically: https://fetchai.github.io/agents-aea/build-aea-programmatically
Fixes #736 
_Put an `x` in the boxes that …
> AEA-368 - Add minimal aea install.

- aea/crypto/ledger_apis.py
The way we generating the transaction nonce it asserts if the identifier exists in the `ledger_apis.keys()`. But when we don't want to transact with a ledger we cannot generate a `tx_nonce` because we implemented this functionality inside the `LedgerApi` of each token. I added the assertion inside the try/catch block so it will return an empty tx_nonce.
#788
> Fix tx_nonce generator

- aea/cli/common.py
- aea/cli/scaffold.py
This PR fixes an issue of `aea scaffold` when an invalid package name is given as input.
E.g.: the result of the following command
```
aea scaffold protocol hello-world
```
used to fail, making the `aea-config.yaml` file empty.
> Fix `aea scaffold` when an invalid package name is given as input.

- aea/registries/base.py
- packages/fetchai/skills/ml_data_provider/skill.yaml
- packages/fetchai/skills/ml_train/handlers.py
- packages/fetchai/skills/ml_train/model.py
The ML Skill didn't work properly. The model was not actually trained, due to problems with Keras models when trained in multiple threads.
This PR improves the training process in the `ml_train` skill. In particular, the model component `MLModel` starts a `training_loop`, running in a separate thread, and waits for data from a data queue, which in turn is populated by the main thread.
So the training is done in a separate thread, but at the end of every `fit` it updates the weights stored as an attribute in `MLModel`. This operation is made thread-safe by using a lock. The weights are then loaded whenever there's the need for `predict` or `evaluate` the model, which is compiled every time but updated with the latest version of the weights.
I leave this link as a future reference: …
> Fix several issues in ml skills.

- aea/protocols/base.py
- aea/registries/base.py
- docs/build-aea-programmatically.md
- docs/cli-vs-programmatic-aeas.md
- tests/test_docs/test_build_aea_programmatically/programmatic_aea.py
- tests/test_docs/test_cli_vs_programmatic_aeas/programmatic_aea.py
- tests/test_protocols/test_base.py
- tests/test_registries.py
- tests/test_skills/test_base.py
This PR introduces functionality for protocols to be loaded directly from a directory in one line via `Protocol.from_dir(protocol_dir_path)`.
- #834
-
> first step towards simplifying protocol loading

- aea/skills/base.py
This PR adds warning messages at runtime, while loading skill components.
Fixes #323 
> Log warning message for loadable skill components not declared in config files.

- aea/skills/base.py
The classes now are filtered by the import path. If they start with 'aea.' then they are removed, since they belong to the framework and are not user-defined.
Fixes #886 
> fix issue #886

- packages/fetchai/connections/http/connection.py
- tests/test_packages/test_connections/test_http/test_http.py
the assumption underlying the AEA connections is that the
attribute 'self.loop' is already running, because it is started by
the multiplexer. (notice, 'self.loop' of the connection is the same loop
passed to the http channel).
In the tests, if the multiplexer is not used, the loop must be run in
a thread (or, even better, using the asyncio loop being run by the
pytest-asyncio plugin). That's the reason why the code with
'run_coroutine_threadsafe' didn't work.
Moreover, the approach of 'run_until_complete' won't work with the
multiplexer, because at the time the method is called the loop
is already running:
RuntimeError: This event loop is already running
Change (only one) test to show the above in code.
What …
> Make http connection use the already-running asyncio loop

- aea/agent.py
- aea/connections/base.py
- aea/decision_maker/base.py
- aea/mail/base.py
- packages/fetchai/connections/oef/connection.py
- tests/test_multiplexer.py
The OEF connection teardown had problems in the following cases:
- the OEF is down, we try to connect, and then we stop
- the OEF was up, we were connected, the OEF goes down and then we stop
to solve that, the `Multiplexer.disconnect` now calls the `Connection.disconnect`
of all the connection that are "connected" or "connecting".
Fixes #841 
> Fix OEF Connection teardown

- docs/thermometer-skills.md
Added a Note in the guide to inform that we have to change the config.
- 
> Small update  in the thermometer demo.

- aea/configurations/base.py
- aea/configurations/schemas/aea-config_schema.json
- aea/configurations/schemas/connection-config_schema.json
- aea/configurations/schemas/contract-config_schema.json
- aea/configurations/schemas/definitions.json
- aea/configurations/schemas/protocol-config_schema.json
- aea/configurations/schemas/protocol-specification_schema.json
- aea/configurations/schemas/skill-config_schema.json
- setup.cfg
- setup.py
- tests/test_configurations/test_base.py
Both at JSON schema level and code level, now we have a clear separation of the version numbers.
In particular:
- dependencies.version is compliant with PEP 440 version specifiers
- aea_version is compliant either with PEP 440 version specifiers or one version number (as recommended by PEP 440)
- version is compliant with the SemVer format, since an AEA package is not coupled with Python.
Fixes  #931
N/A
> Correctly split between semantic versioning and package versioning.

- aea/cli/run.py
This PR changes which connections are used by default.
If the user does not provide `--connections` then all connections are used. This makes more sense than the previous implementation as it aligns it to how we load protocols and skills.
Also, previously `default_connection` was misused. The `default_connection` specifies the connection which should be used for routing envelopes by default. It should not specify which connections are actually run.
- #952 
-
> change what connections are used by default

- aea/cli/common.py
- aea/cli/core.py
- aea/cli/launch.py
- aea/cli/loggers.py
Forward verbosity options in `aea launch`.
That is, the command `aea -v DEBUG launch aea_proj_name [aea_proj_name ...]` 
will forward the verbosity option `DEBUG` to every other agents.
Fixes #951 
N/A
> AEA-452 Forward verbosity option in 'aea launch'.

- aea/cli/add.py
Adding protocold recursively changed to call the method directly, not invoking the command. For correct error handling.
> Adding protocold recursively changed to call the method directly

- aea/aea_builder.py
- aea/agent.py
- tests/common/utils.py
- tests/test_aeabuilder.py
small refactoring over Agent to make tests easier: now it's possible to spin agents main loop manually
set default agent sleep timeout in AEABuilder to reduce cpu utilization
> AEA-531 fix for default agent loop timeout on contruction with AEABuild

- aea/aea.py
- aea/aea_builder.py
- aea/context/base.py
- aea/skills/base.py
- docs/skill.md
- tests/test_aea.py
The agent context namespace is populated via either AgentContext constructor or AEA constructor through keyword arguments.
It can be accessed with
- agent_context.namespace.attribute_name
- skill_context.namespace.attribute_name
Fixes #1008 
> AEA-500 Add agent context namespace.

- aea/aea_builder.py
- aea/exceptions.py
- tests/test_aea.py
- tests/test_aeabuilder.py
- tests/test_docs/test_agent_vs_aea/test_agent_vs_aea.py
- tests/test_protocols/test_generator.py
This PR does the following:
- adds an user-defined `AEAException`. 
- improves the `AEABuilder.add_component` so it raises `AEAException`s in specific circumstances.
The `AEAException` class is supposed to be used whenever we need to describe exceptions at framework level.
For instance, trying to add a package in the AEABuilder class (`AEABuilder.add_component(type, path)`) might fail for many reasons:
1. the path to the package does not exist
2. the directory exists, but there isn't the expected configuration file.
3. the package already exists in the AEABuilder
4. there are some missing package dependencies
...
Despite we can't foresee all the exceptions, for some of them we can. For instance, case (3) and (4) are exceptions at framework level, so we can raise the right exception to the …
> Add AEAException and use it in exceptions of AEABuilder.add_component

- aea/cli/publish.py
- tests/test_cli/test_publish.py
…+ tests.
#1066 
Preventing from publishing agents with private_key_paths implemented
> Preventing from publishing with private_key_paths implemented AEA-535

- aea/helpers/base.py
This PR changes the `aea.helpers.base.import_module` helper function, called by `aea.helpers.base.add_modules_to_sys_modules`, which in turn is called by many `aea.aea_builder.load_and_add_<package_type>`.
Now it adds all the prefixes of the import path as namespace namespaces in `sys.modules`.
Also, rename the function to `import_aea_module` since it used to handle only import statements for an AEA package (i.e. of the form `packages.<author_name>.<package_type_plural>.<package_name>...`).
Fix (partially) #1062 and  #890
... why? 
Because now, when trying to import, say, `packages.fetchai but on what follows: skills.generic_seller.non_existing_module` (see #890), assuming `packages.fetchai but on what follows: skills.generic_seller` is loaded correctly, instead of:
error: An error …
> AEA-503 improve the import_module function in helpers.

- aea/skills/tasks.py
- tests/test_skills/test_tasks.py
TaskManager by default uses a lazy way to init workers pool on first enqueue instead of on start.
Can be controlled by TaskManager init argument: is_lazy_pool_start
default pool workers amount set to 1 instead of 5.
refers to https://github.com/fetchai/agents-aea/issues/1136
Saves some resources on agent start.
> [AEA-552] TaskManager: lazy pool creation option

- deploy-image/Dockerfile
One liner to install go on the docker production image, required by `fetchai/connections/p2p_noise` package.
> Add golang installation to prod image

- aea/cli/install.py
One liner to allow for `aea install` with `fetchai/p2p_noise:0.1.0` dependencies (`pynacl` in particular) to finish
> Boost cli aea install timeout

- Pipfile
`aiohttp` and `markdown` versions caused issues in `pipenv lock`ing.
this is the screen after  `pipenv install --dev 2> output_file && vim output_file`
as you can see, `aries-cloud-agent caused the problem
n/a
> Update pipfile due to dependency conflicts

- aea/configurations/base.py
- aea/configurations/constants.py
- benchmark/framework/aea_test_wrapper.py
- tests/test_aea_exectimeout.py
- tests/test_configurations/test_base.py
- tests/test_connections/test_base.py
This PR fixes the configuration objects such that the name and author are now required arguments.
-
-
> fixes requirements for name and author in configs

- .github/workflows/workflow.yml
- scripts/check_package_versions_in_docs.py
- tox.ini
This PR adds a new script to check that the package ids in the docs are not out of sync with the current state of the local registry `packages/`.
Fixes #1188 
> AEA-573 CI check for consistent package usage

- tests/test_cli/test_add/test_connection.py
- tests/test_cli/test_add/test_protocol.py
- tests/test_cli/test_add/test_skill.py
- tests/test_cli/test_create.py
- tests/test_cli/test_generate/test_protocols.py
- tests/test_cli/test_remove/test_connection.py
- tests/test_cli/test_remove/test_protocol.py
- tests/test_cli/test_remove/test_skill.py
- tests/test_cli/test_scaffold/test_connection.py
- tests/test_cli/test_scaffold/test_protocols.py
- tests/test_cli/test_scaffold/test_skills.py
- tests/test_connections/test_stub.py
- tests/test_packages/test_connections/test_oef/test_communication.py
- tests/test_registries.py
use patch.start and patch.stop instead of patch.__enter__ and patch.__exit__
got a problem with mac os ci:
```
@classmethod
def teardown_class(cls):
"""Tear the test down."""
>       cls.patch.__exit__()
/Users/runner/runners/2.262.1/work/agents-aea/agents-aea/tests/test_cli/test_scaffold/test_protocols.py:384: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/Users/runner/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/unittest/mock.py:1524: in __exit__
return exit_stack.__exit__(*exc_info)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <contextlib.ExitStack object at 0x12048aa90>, exc_details = ()
def __exit__(self, *exc_details):
>       received_exc = exc_details[0] is not None
E       IndexError: tuple index out …
```
> patch.__enter__/__exit__ replaced with more suitable start/stop

- aea/aea_builder.py
- aea/crypto/wallet.py
Make `AEABulider.add_private_key` to accept the `private_key_path` argument to be `None`.
Fixes #1237 
n/a
> Make 'private_key_path' to be None in AEABulider.add_private_key

- aea/aea_builder.py
There was an execution path where the sys.exit was called on AEABuilder.build. This is not right since we don't want the app to stop, for instance when used programmatically A good alternative is to raise an exception.
Fixes #1190 
n/a
> Remove sys.exit from subcalls to AEABuilder.build

- aea/aea_builder.py
- tests/test_aea_builder.py
- tests/test_aea_exception_policy.py
**Merge #1277 before this PR**
Make `AEABuilder.build` reentrant, but only for components loaded from directories.
The reason is that manually added component cannot be deep-copied due to unpredictable attributes that user-define classes could have. More importantly, objects like `queue.Queue` cannot be deep-copied.
Notice also that `copy.copy` is not enough because the component objects are complex.
Fixes #1190 
n/a
> AEABuilder reentrancy

- aea/registries/base.py
- aea/registries/resources.py
- tests/test_registries.py
Changes:
- add `AgentComponentRegistry`, a generic registry for `Component` objects
- remove `ProtocolRegistry` and `ContractRegistry` since they are subsumed by the `AgentComponentRegistry`
Preliminary work to address #1291 and #1290 
> Add generic agent component registry

- aea/mail/base.py
This PR will let the connection list in a `Multiplexer` instance to be modifiable even after the initialization of the instance.
Preliminary work for #1290, #1291 and #1191 
> Make connection list of the Multiplexer modifiable also after initialization

- .github/workflows/workflow.yml
- Pipfile
- tests/conftest.py
- tests/test_cli/test_run.py
- tests/test_docs/test_agent_vs_aea/test_agent_vs_aea.py
- tests/test_packages/test_connections/test_local/test_search_services.py
- tests/test_packages/test_skills/test_erc1155.py
- tests/test_packages/test_skills/test_generic.py
- tests/test_packages/test_skills/test_tac.py
- tests/test_packages/test_skills/test_thermometer.py
- tests/test_packages/test_skills/test_weather.py
- tox.ini
pytest rerun decorator applied to some flaky tests
help to pass CI tests 
adds new development/ci dependency:  https://github.com/pytest-dev/pytest-rerunfailures
> AEA-625 flaky tests rerun

- tests/conftest.py
- tests/test_packages/test_connections/test_p2p_libp2p/test_communication.py
- tests/test_packages/test_connections/test_p2p_libp2p_client/test_communication.py
Add a decorator to libp2p-related tests that prints libp2p nodes logs to standard output in case of test failure. Practical for debugging ci test failures.
> libp2p tests print node log after timeout

- aea/cli/add.py
- aea/cli/create.py
- aea/cli/fetch.py
- aea/cli/registry/fetch.py
- tests/test_cli/test_add/test_contract.py
- tests/test_cli/test_fetch.py
- tests/test_cli/test_registry/test_fetch.py
Add method refactored: passing ctx instead of click_context.
That makes `add_item` programmatically callable without `click_context` object that is CLI command specific. Also it wasn't really needed as we operate our custom `ctx: aea.ci.utils.context.Context` object together with `@pass_ctx` decorator in CLI commands.
Also public method `add_item` name fixed.
> Add method refactored: passing ctx instead of click_context.

- aea/aea_builder.py
- aea/agent.py
- tests/test_aea_builder.py
This PR updates docstrings in the builder and adds the partial reset by default.
Partial reset only resets the private keys and components added as instances.
-
-
> AEA-637 Feature/partial reset

- aea/aea_builder.py
Fix a bug in the case when only one address is provided to the AEA builder, and the default is not `fetchai`.
n/a
> fix set up of identity object in case one address is provided

- aea/skills/base.py
update duplicate skill model classes check: filter out those whose module path starts with 'packages.'
> update duplicate skill model classes check

- aea/cli/generate.py
- aea/protocols/generator/__init__.py
- aea/protocols/generator/base.py
- aea/protocols/generator/common.py
- aea/protocols/generator/extract_specification.py
- aea/protocols/generator/generator.py
- aea/protocols/generator/validate.py
- tests/test_protocols/test_generator.py
This PR breaks the code in the generator module into the following modules:
- `validate`: containing code used to validate a protocol specification
- `extract_specification`: containing code to extract fields from a protocol specification into pythonic objects (all fields are encapsulated in `PythonicProtocolSpecification`)
- `common`: containing constants and functions used in more than one module
- `generator`: containing the old generator code minus the above separated codes
The PR doesn't do anything else other than breaking existing functionality into separate modules (except some minor necessary tweaks to make that happen).
Some notes:
`validate` is now supposed to just take a protocol specification and indicates whether it is a valid specification or not. Crucially it no longer …
> Generator refactoring 

- aea/aea_builder.py
After #939 , it is possible to load a skill from another skill. However, it is important the order in which the skills declared in aea-config.yaml file are processed. This PR aims to fix that, by finding the topological order in the skill dependency graph.
n/a
> Fix Skill loading order

- aea/cli/generate.py
- aea/protocols/generator/base.py
- aea/protocols/generator/common.py
- aea/protocols/generator/extract_specification.py
- aea/protocols/generator/validate.py
- tests/test_cli/test_generate/test_generate.py
- tests/test_cli/test_generate/test_protocols.py
- tests/test_protocols/test_generator.py
This PR includes the following:
- Moved the following functionalities from CLI generate to the generator:
- Checking `protoc` is installed
- Checking `black` is installed
- Loading protocol specification yaml file
- Run black code formatting
- Added the following functionalities:
- Checking whether a protobuf schema file is valid, by trying to compile it.
- The above process is now atomic, if invalid it rolls back everything generated. If any errors, it correctly forwards them as part of exception message.
- Running `protoc` is now via `subprocess` instead of `os.system(cmd)`
- `extract_specification.py`, `validate.py`, `common.py` pass `pylint` now
- Updating tests to reflect the above changes
_Put an `x` in the boxes that …
> AEA-516 Move functionalities from cli generate to generator

- aea/protocols/generator/common.py
This PR address an incompatibility issue for Python 3.6 in the generator code.
> Addressing generator bug for Python 3.6

- scripts/check_package_versions_in_docs.py
- scripts/deploy_to_registry.py
- tests/test_cli/test_add/test_connection.py
- tests/test_cli/test_add/test_contract.py
- tests/test_cli/test_add/test_protocol.py
- tests/test_cli/test_add/test_skill.py
- tests/test_cli/test_fetch.py
- tests/test_cli/test_gui.py
This PR applies a few minor fixes which are possible post-release.
-
-
> fix deploy and check scripts; enable disabled tests

- .github/workflows/workflow.yml
- scripts/check_package_dependencies.py
- tox.ini
Add script to check package dependencies.
Fixes #1213 
> AEA-704 Add script to check package dependencies

- .github/workflows/workflow.yml
> Upgrade golangci-lint

- aea/registries/resources.py
- aea/skills/base.py
- tests/test_registries/test_base.py
- tests/test_skills/test_base.py
This PR removes the `inject_contract` feature of the `Skill` and `Resources` classes, made obsolete by recent changes on contract loading and usage.
Fixes #1465 
n/a
> Remove 'inject contract' feature

- aea/crypto/cosmos.py
- tests/test_crypto/test_cosmos.py
This change adds support for signing CosmWasm messages which are in a different format than standard CosmosSDK messages.
I added if the message contains a specific type it is handled as CosmWasm message otherwise old functionality is kept.
- I need someone to help me to test this change if it doesn't break anything.
> CosmWasm message signing

- tests/data/generator/t_protocol/dialogues.py
- tests/data/generator/t_protocol/message.py
- tests/data/generator/t_protocol/protocol.yaml
- tests/data/generator/t_protocol_no_ct/dialogues.py
- tests/data/generator/t_protocol_no_ct/message.py
- tests/data/generator/t_protocol_no_ct/protocol.yaml
- tests/test_protocols/test_generator/test_end_to_end.py
This PR fixes the generator tests that failed due to the recent generator changes.It:
* Regenerates the `t_protocol` and `t_protocol_no_ct` protocols.
* Adds dialogues into the generator end_to_end test.
> Fix Generator Tests

- aea/helpers/async_utils.py
- aea/multiplexer.py
- tests/test_helpers/test_async_utils.py
- tests/test_multiplexer.py
- tests/test_packages/test_connections/test_oef/test_communication.py
multiplexer cancel recv send loops before disconnecting connections
https://github.com/fetchai/agents-aea/issues/1738
fixes issue when multiplexer tries to handle messages in queues but connections alraedy disconnected.
now it stops message processing loops and disconnect connections
> [AEA-903] multiplexer cancel recv send loops before disconnecting connections

- aea/aea_builder.py
- aea/configurations/base.py
- aea/configurations/loader.py
- aea/configurations/schemas/configurable_parts/base-custom_config.json
- aea/configurations/schemas/configurable_parts/connection-custom_config.json
- aea/configurations/schemas/configurable_parts/skill-custom_config.json
- aea/configurations/schemas/skill-config_schema.json
- aea/helpers/base.py
- tests/conftest.py
- tests/data/aea-config.example_multipage.yaml
- tests/test_aea_builder.py
- tests/test_configurations/test_base.py
- tests/test_helpers/test_base.py
Currently, it is not possible to overwrite configurations _only_ for specific fields from the `aea-config.yaml` file, as could be done with `aea set`.
This PR allows that. (TODO: add an example)
n/a
n/a
> AEA-928 Allow finer-grained overwrite of component configuration from aea-config.yaml.

- aea/configurations/pypi.py
- tests/test_configurations/test_pypi.py
Update aea.configurations.pypi.is_satisfiable so to handle '~=' operator correctly.
Previously, only versions of the form `~=<major>.<minor>` were handled. After this PR this restriction is not imposed anymore.
Partially addresses #1702
n/a
> Update aea.configurations.pypi.is_satisfiable so to handle '~=' operator correctly

- aea/configurations/base.py
- tests/test_configurations/test_base.py
Prevent update of 'class_name' in SkillConfig.update for skill component configuration.
The field `class_name` was already ignored, but now we also add a consistency check to the input of the `SkillConfig.update` function.
Partially addresses #1702 
n/a
> Prevent update of 'class_name' in SkillConfig.update for skill component configuration

- aea/configurations/base.py
- aea/configurations/loader.py
- tests/test_configurations/test_base.py
Add validation of component configurations in agent config setter.
Partially addresses #1702.
n/a
> Add validation of component configurations in agent config setter

- aea/aea_builder.py
The bug has been introduced by #1822. The problem was due to wrong computation of the input to provide to the topological order algorithm.
n/a
n/a
> AEA-948 fix bug on import order computation in the 'AEABuilder'

- tests/test_cli/test_upgrade.py
The 'TestNonVendorProject' fails because the minor version number of the framework has been upgraded to 0.7.0 on 'develop'. Using the flag '--skip-consistency-check' we avoid failing for that reason.
n/a
> Fix test for 'aea upgrade' by adding 'skip-consistency-checks'

- aea/cli/config.py
- aea/cli/utils/constants.py
- tests/test_cli/test_config.py
This PR adds support for setting and getting dict values in configs.
https://github.com/fetchai/agents-aea/issues/1881
-
> add config set/get support for dict

- scripts/acn/Dockerfile.dev
- scripts/acn/README.md
- scripts/acn/k8s/deployment.yaml
- scripts/acn/k8s/dns.yaml
- scripts/acn/k8s/istio.yaml
- scripts/acn/k8s/secret.yaml
- scripts/acn/k8s_deploy_acn_node.py
- scripts/acn/run_acn_node_standalone.py
Add script for reproducible deployment of an ACN node to kubernetes cluster.
Check self-review for more details.
``` bash
python3 scripts/acn/k8s_deploy_acn_node.py --acn-key-file fet_key_test_1.txt --acn-port 9009 --acn-port-delegate 11009 --acn-port-monitoring 8080 --k8s-fetchai-defaults --docker-fetchai-defaults-dev
python3 scripts/acn/k8s_deploy_acn_node.py --acn-key-file fet_key_test_1.txt --acn-port 9009 --acn-port-delegate 11009 --acn-port-monitoring 8080 --k8s-fetchai-defaults --docker-fetchai-defaults-dev --delete
python3 scripts/acn/k8s_deploy_acn_node.py --from-file .acn_deployment.yaml 
python3 scripts/acn/k8s_deploy_acn_node.py  --from-file .acn_deployment.yaml --delete
```
> [AEA-910, AEA-666] Add k8s files and scripts

- aea/cli/registry/utils.py
- tests/test_cli/test_upgrade.py
Use mixed mode to retrieve latest public id (in 'aea upgrade'). This wasn't the case before this PR.
n/a
n/a
> Use mixed mode to retrieve latest public id in `aea upgrade`

- tests/conftest.py
- tests/test_packages/test_connections/test_p2p_libp2p/test_errors.py
This should fix failing tests with 
```python
addrs = ['fetch.ai', 'agents-p2p-dht.sandbox.fetch-ai.com']
def _ip_all_private_or_all_public(addrs: List[str]) -> bool:
if len(addrs) == 0:
return True
is_private = ip_address(gethostbyname(addrs[0])).is_private
is_loopback = ip_address(gethostbyname(addrs[0])).is_loopback
for addr in addrs:
>           if ip_address(gethostbyname(addr)).is_private != is_private:
E           socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```
> Change public dht dns from sandbox to prod for ip class test

- aea/multiplexer.py
- tests/test_multiplexer.py
connection added twice in gym ex. caused cause unproper cleanup on multiplexer.setup
https://github.com/fetchai/agents-aea/issues/1846
> fix for multiplexer setup connections replace

- scripts/bump_aea_version.py
Improve `bump _aea_version` script.
Now it also updates the specifier sets.
Say the old version if `0.7.4` and the new one is `1.0.0`; the script looks for occurrences in the whole codebase for specifier sets like `>=0.7.0,<0.8.0` and replace it with >=1.0.0,<1.1.0
since many replacements will occur in `packages/` , we also run the computation of hashes.
Partially addresses #1854
n/a
> [AEA-1035] Improve bump aea version script

- aea/helpers/search/models.py
- docs/query-language.md
- tests/test_helpers/test_search/test_models.py
- tests/test_packages/test_connections/test_oef/test_models.py
This PR fills coverage holes in `helpers.search.model`.
It also corrects the semantics of <, <=, >, >=, relations in ConstraintTypes.
> AEA-1121 Filling coverage gaps for `helpers/search/model`; Resolve semantics

- .github/workflows/workflow.yml
Fix "common-check-5" to run only when merging into master
n/a
n/a
> Fix "common-check-5" to run only when merging into master

- aea/aea_builder.py
- aea/cli/utils/config.py
- aea/configurations/base.py
- aea/configurations/constants.py
Move logging configuration  loading  from `aea.cli.utils.config.try_to_load_agent_config` to ~AEABuilder.from_aea_project.~ `AEABuilder.build`. 
Fixes #2159
n/a
> AEA-1220 Move logging configuration loading in AEABuilder.build

- aea/cli/fetch.py
- aea/manager/manager.py
- aea/manager/project.py
Make the multi-agent manager fetch in mixed mode by default.
It involved minor refactoring in `aea.cli.fetch` and in the agent manager APIs (added `remote` flag alongside `local`).
Fixes #2155 
n/a
> AEA-1221 Make multi-agent manager fetch in mixed mode by default

- aea/cli/add_key.py
- tests/test_cli/test_add_key.py
fix for err message on file not found for aea cli add-key with no file specified
https://github.com/fetchai/agents-aea/issues/2161
> AEA-1229 aea clie add-key file not found small fix

- aea/cli/upgrade.py
- aea/helpers/base.py
- tests/common/mocks.py
- tests/test_cli/test_upgrade.py
- tests/test_helpers/test_base.py
With this PR, at the beginning of `aea upgrade`, in case the project is on the registry with a newer version, the user has the option to download the latest version and replace the current project with the new one.
Fixes AEA-1223 
n/a
> AEA-1223 Add prompt in "aea upgrade" in case project is on registry with newer version

- aea/protocols/generator/validate.py
- docs/protocol-generator.md
- examples/protocol_specification_ex/sample.yaml
- tests/test_docs/test_bash_yaml/md_files/bash-protocol-generator.md
This PR updates the following:
* Protocol generator documentation page.
* sample.yaml example protocol specification
* validate.py under the generator 
The first two is a response to changes to protocols and generator. 
The last one removes an extra constraint and adds a repetition check on initial performatives
> Minor updates to protocol docs page and example

- aea/cli/registry/utils.py
- aea/cli/upgrade.py
- tests/common/utils.py
- tests/test_cli/test_registry/test_add.py
- tests/test_cli/test_upgrade.py
Enable AEA version compatibility in `aea upgrade`, after https://github.com/fetchai/agents-registry/pull/275/
This means packages are searched among the one compatible with the `aea` version of the currently installed framework.
Fixes #2138 
n/a
> [AEA-1222] add aea version compatibility in 'aea upgrade'

- scripts/generate_api_docs.py
Update 'generate_api_docs.py' script to include plugins apidocs
This new version of the script adds plugin apidocs in docs/api/plugins/*, one folder for each package.
Fixes the missing generation of apidocs for plugins after #2112
n/a
> Update 'generate_api_docs.py' script to include plugins apidocs

- aea/cli/upgrade.py
- aea/configurations/schemas/protocol-config_schema.json
- tests/test_aea_builder.py
- tests/test_cli/test_upgrade.py
This PR adds a simple test for the dependencies in AEA Builder and addresses #2261
#2261
-
> AEA-1360 Add builder test for dependencies, add protocol spec id as required

- aea/skills/base.py
- tests/test_skills/test_base.py
Two changes:
- Reintroduce warning messages when a class not declared in config is found in a skill module (2f83384).
- This was removed after #2319
- Allow to explicitly declare behaviours that are registered programmatically. (828c702, e29a98d)
Fix #1480
n/a
> AEA-1387 Allow to explicitly declare behaviours that are registered programmatically. 

- aea/cli/add_key.py
- aea/cli/generate_key.py
- aea/cli/generate_wealth.py
- aea/cli/get_address.py
- aea/cli/get_multiaddress.py
- aea/cli/get_wealth.py
- aea/cli/issue_certificates.py
- aea/cli/launch.py
- aea/cli/run.py
- aea/cli/transfer.py
- aea/cli/utils/click_utils.py
- tests/test_cli/test_utils/test_utils.py
reusable password_option decorator provided
it adds two options
-p flag to ask password interactively
--password to set password with command line
(can not combine it, cause one flag and another is option requires argument)
if -p and --password specified same time, password will be asked interactively
we can change priority and --password value will be used.
> AEA-173 cli password promting improved

- aea/configurations/schemas/definitions.json
- aea/helpers/base.py
- aea/test_tools/test_cases.py
- tests/test_cli/test_interact.py
- tests/test_cli/test_registry/test_publish.py
- tests/test_cli/test_registry/test_push.py
- tests/test_cli/test_transfer.py
- tests/test_cli/test_upgrade.py
- tests/test_cli/test_utils/test_utils.py
- tests/test_cli/tools_for_testing.py
- RegexConstrainedString should have used re.fullmatch instead of re.match
- JSON schema regexes should have "^" and "$" because they are not full-matched by default.
n/a
n/a
> Fix bug in RegexConstrainedString and regexes in schemas

- .coveragerc
- aea/cli/add.py
- aea/cli/create.py
- aea/cli/fetch.py
- aea/cli/publish.py
- aea/cli/push.py
- aea/cli/search.py
- aea/cli/utils/context.py
- aea/cli/utils/package_utils.py
- tests/test_cli/test_add/test_connection.py
- tests/test_cli/test_create.py
- tests/test_cli/test_fetch.py
- tests/test_cli/test_utils/test_utils.py
- tests/test_packages/test_connections/test_p2p_libp2p_client/test_communication.py
This PR addresses an issue with v1 whereby a missing local registry (`packages` folder) can lead to messy exceptions.
#2442
-
> AEA-1519 fix: provide proper stdout messages when local registry not present

- plugins/aea-cli-ipfs/setup.py
- plugins/aea-ledger-cosmos/setup.py
- plugins/aea-ledger-fetchai/setup.py
- setup.py
Versions of dependencies in setup.py are not bounded so far. This can lead to unexpected install issues if dependencies are updated. We now bound by the next major version. As long as dependencies follow semantic versioning this should solve the problem.
-
-
> feat: bound version of dependencies by next major

- tests/test_packages/test_connections/test_p2p_libp2p_client/test_communication.py
The test involved was in a temporary state, waiting for improvements on the libp2p implementation. Now we do not need to resend the envelope, as it will be retransmitted by the connection logic.
Fix #2435
n/a
> Test: update libp2p test after new ack mechanism (#2435)

- aea/aea_builder.py
- aea/configurations/data_types.py
- aea/configurations/manager.py
- aea/configurations/utils.py
- aea/manager/manager.py
- aea/manager/project.py
- tests/test_manager/test_manager.py
Add consistency of package versions in MAM.
MAM should track all versions of packages and raise an exception when incompatible versions of any packages are added. Otherwise, this can lead to problems at runtime (with whatever version being loaded last being in memory).
This PR addresses the above issue.
Fix #2459 
n/a
> AEA-1610 fix: add check consistency of package versions (#2459)

- aea/cli/utils/context.py
- aea/configurations/base.py
- aea/configurations/loader.py
- aea/manager/manager.py
- aea/manager/project.py
- tests/test_configurations/test_aea_config.py
- tests/test_configurations/test_loader.py
Validate aea_version when loading configuration.
That is, before validating the loaded YAML file against the schema, first check that `aea_version` is consistent with the current `aea` version being used.
It also introduces the `skip_aea_validation` flag in the `ConfigLoader` constructor (and factory methods/functions). This is useful to switch the behaviour of configuration loading in terms of `aea_version` validation.
As pointed out by @DavidMinarsch , sometime we don't want to validate the `aea_version`, e.g. we can fetch packages even if the current AEA version is incompatible with the fetched package; but we want such validation for the MAM.
#2519 …
> AEA-1613 fix: validate aea_version when loading configuration (#2519)

- aea/aea_builder.py
- aea/cli/install.py
- aea/cli/utils/context.py
- aea/configurations/pypi.py
- aea/helpers/install_dependency.py
- tests/test_cli/test_install.py
- tests/test_configurations/test_pypi.py
Detect conflicts in `aea install`.
before this change, the problem was that if there were two PyPI dependencies with the same package, one of them replaced the other in an unpredictable way.
Now instead we check upfront whether there are two dependencies with the same package name, and we also check whether they are conflicting or unsatisfiable.
This is not the final solution. A proper solution would require more efforts trying to understand how to merge dependencies in different PyPI indexes, different repository versions etc. But I think it is a good trade-off and covers a lot of use-cases.
n/a
n/a
> Detect conflicts in `aea install`

- aea/test_tools/test_cases.py
- tests/test_packages/test_skills_integration/test_simple_oracle.py
Currently it's hard to debug tests that fail only in CI because the AEA logs are not visible. This PR adds an option to return the AEA logs so they can be reported on test failures.
> Add option to return AEA logs in missing string check (AEA-1636)

- aea/cli/generate_key.py
- tests/test_cli/test_generate_key.py
add-key option for generate key cli command
https://github.com/fetchai/agents-aea/issues/2093
> add-key option for generate key cli command

- .github/pull_request_template.md
Use absolute paths for links in the pull request template.
Relative paths in the pull request template work when browsing the repo **but not when viewing a pull request**. Absolute paths will ensure consistent behavior.
> chore: use absolute links in pull request template (ECO-1073)

- aea/cli/init.py
- aea/test_tools/test_cases.py
- docs/generic-skills-step-by-step.md
- docs/quickstart.md
- tests/test_cli/test_add/test_connection.py
- tests/test_cli/test_add/test_protocol.py
- tests/test_cli/test_add/test_skill.py
- tests/test_cli/test_add_key.py
- tests/test_cli/test_create.py
- tests/test_cli/test_delete.py
- tests/test_cli/test_generate/test_protocols.py
- tests/test_cli/test_init.py
- tests/test_cli/test_launch.py
- tests/test_cli/test_remove/test_base.py
- tests/test_cli/test_remove/test_connection.py
- tests/test_cli/test_remove/test_dependencies.py
- tests/test_cli/test_remove/test_protocol.py
- tests/test_cli/test_remove/test_skill.py
- tests/test_cli/test_run.py
- tests/test_cli/test_scaffold/test_connection.py
- tests/test_cli/test_scaffold/test_protocols.py
- tests/test_cli/test_scaffold/test_skills.py
- tests/test_cli/test_search.py
- tests/test_cli/test_upgrade.py
- tests/test_docs/test_bash_yaml/md_files/bash-generic-skills-step-by-step.md
- tests/test_docs/test_bash_yaml/md_files/bash-quickstart.md
- tests/test_docs/test_quickstart.py
- tests/test_multiplexer.py
Authors should not need to register to get started developing AEAs.
With this change, users can still register with:
``` bash
aea init --register
```
or
``` bash
aea register
```
but by default, only the author handle will be setup (previously `aea init --local`).
> feat: make registering author optional
