Pipfile, Pipfile.lock, aea/channel/oef.py, aea/protocols/fipa/fipa.proto, aea/protocols/fipa/serialization.py, tests/common/oef_search_pluto_scripts/launch.py, tests/common/oef_search_pluto_scripts/launch_config_latest.json, tests/common/oef_search_pluto_scripts/node_config_latest.json, tests/conftest.py, tests/test_channel/test_oef/__init__.py, tests/test_channel/test_oef/test_communication.py, tests/test_channel/test_oef/test_models.py, tests/test_protocols/test_fipa.py
This PR aims to fix an issue when the data model is `None`, both in a description and in a query object.
Moreover, it adds more tests for the OEF channel.
None/
=> Handle the case in the oef transaltion when data model is None.

tests/common/__init__.py, tests/common/oef_search_pluto_scripts/launch.py, tests/conftest.py, tests/test_channel/test_oef/test_communication.py
This PR fixes listing issues.
-
N/A
=> Apply linting fixes

.gitignore, aea/channel/oef.py
Quick fix to make the oef_channel work again with the tac protocol.
-
None
=> Fix oef channel to work with tac protocol.

Pipfile, Pipfile.lock
Bump OEF SDK version to `0.6.3`.
None.
None.
=> bump oef sdk version to 0.6.2

Pipfile, Pipfile.lock, aea/protocols/oef/message.py, tests/test_channel/test_oef/test_communication.py
Add more tests for the OEF protocol. Tested with the `oef==0.6.3`.
In particular, provide tests for `SEARCH_SERVICES`, `REGISTER_SERVICE` and `UNREGISTER_SERVICE`, useful for regression testing.
None.
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
None.
=> Add more tests for the OEF protocol.

Pipfile, Pipfile.lock, aea/mail/base.py
Update the OEF SDK to version `0.6.4`.
None.
=> Bump OEF SDK version to 0.6.4.

Pipfile, Pipfile.lock, tests/test_channel/test_oef/test_communication.py
Bump OEF SDK version to `0.6.7`.
None.
None.
=> Bump OEF SDK version to `0.6.7`.

aea/skills/base.py, examples/echo_skill/behaviours.py, examples/echo_skill/tasks.py
This PR completes the loading of Behaviours and Tasks from a "skill" folder.
None.
None.
=> Load skill behaviours and tasks at runtime.

setup.py
Add `"fipa"` and `"tac`" extras in the package setup.
The other protocols supported by the framework didn't use any additional dependency.
Also, add the `"all"` extras, such that all the dependencies can be installed by:
```pip install aea[all]```
None.
=> Add extras for protocol dependencies. 

aea/aea.py, aea/skills/base.py, aea/skills/default/skill.yaml, examples/echo_skill/behaviours.py, examples/echo_skill/handler.py, examples/echo_skill/skill.yaml, examples/echo_skill/tasks.py
This PR introduces the concept of the skill configuration file.
Here an example of configuration file for the [`echo_skill`](https://github.com/fetchai/agents-aea/blob/1312d343fd3e1ed90670a4ce9aeb03eb7d64b906/examples/echo_skill/skill.yaml):
```
name: echo
authors: Fetch.AI Limited
version: 0.1.0
license: Apache 2.0
url: ""
behaviours:
- class_name: EchoBehaviour
args:
foo: bar
handler:
class_name: EchoHandler
args:
foo: bar
bar: foo
tasks:
- class_name: EchoTask
args:
foo: bar
bar: foo
protocol: "default"
```
Fixes  #26
None.
=> Introduce the skill configuration file.

Jenkinsfile, Pipfile, Pipfile.lock, README.md, aea/aea.py, aea/channel/gym.py, aea/channel/local.py, aea/channel/oef.py, aea/cli/add.py, aea/cli/common.py, aea/cli/remove.py, aea/crypto/base.py, aea/mail/base.py, aea/protocols/default/message.py, aea/protocols/fipa/serialization.py, aea/protocols/gym/serialization.py, aea/protocols/oef/message.py, aea/protocols/tac/message.py, aea/protocols/tac/serialization.py, aea/skills/base.py, examples/echo_skill/behaviours.py, examples/echo_skill/handler.py, examples/echo_skill/tasks.py, examples/gym/agent.py, examples/gym/env.py, mypy.ini, tests/conftest.py
This PR adds mypy to the repo for static type checking. It amends the code base to resolve issues raised by mypy. It adds mypy to the testing pipeline (Jenkins).
It fixes #25 .
Mypy can be used in a stricter fashion than currently configured. More details here: https://mypy.readthedocs.io/en/latest/common_issues.html#unexpected-errors-about-none-and-or-optional-types
=> Add mypy for static type checking, fix mypy issues, fixes #25

Makefile
Add mypy cache cleanup to Makefile.
-
None
=> Update Makefile to include mypy reference.

README.md, scripts/generate_private_key.py, tests/test_crypto.py, tox.ini
This PR adds a script to generate a private key which was previously stored in the tac.
-
None
=> Adds crypto script from tac

setup.py
Include JSON schema files in build distribution.
Fixes #68 
None.
=> include JSON schema files in build distribution.

aea/skills/base/config.py, aea/skills/base/core.py
This PR fixes small bugs in skill config parsing and skill loading.
None.
None.
=> Fix small bugs in skill config parsing and skill loading.

Pipfile, Pipfile.lock, setup.py
Adds missing dependencies.
-
-
=> Adds missing protobuf dependency

Jenkinsfile
=> Removes nested stages from Jenkins config

examples/gym_ex/gyms/env.py, examples/gym_ex/proxy/env.py, examples/gym_ex/rl/agent.py, examples/gym_ex/train.py
Reward type changed from bool to float; Gym states the default type of reward is float.
Added missing static types; 
General cleanup and formatting
=> Minor cleanups

.dockerignore, .gitmodules, develop-image/Dockerfile, develop-image/README.md, develop-image/docker-env.sh, develop-image/scripts
Add Docker development image with all the dependencies.
Fixes #77 
None.
=> Add Docker development image.

aea/helpers/base.py
Remove debug print in `aea.helpers.base.locate`, and convert them into logging messages.
None.
=> remove debug print in `aea.helpers.base.locate`.

HISTORY.rst, aea/__version__.py, develop-image/docker-env.sh
Prepares develop for bump to release 0.1.3
-
=> Prepare develop for version bump

aea/cli/__main__.py, tests/test_cli/test_commands/__init__.py, tests/test_cli/test_commands/test_create.py, tests/test_cli/test_commands/test_delete.py, tests/test_cli/test_commands/test_misc.py
This PR adds tests to reach 100% coverage on the `aea.cli.__main__.py` module.
None
None.
=> get 100% coverage on aea.cli.__main__.py.

aea/cli/common.py, examples/gym_ex/proxy/env.py, examples/skills/gym/handler.py, examples/skills/gym/helpers.py
This PR fixes the Gym Skill so to import the Gym messages from `gym_protocol`, that is a module loaded dynamically.
None.
None.
=> fix import from gym_protocol loaded dynamically.

examples/gym_ex/proxy/agent.py, examples/gym_ex/proxy/env.py, examples/gym_ex/train.py, packages/__init__.py, packages/connections/__init__.py, packages/protocols/__init__.py, packages/skills/__init__.py
Fix the Gym example after the export of Gym resources from the `aea` framework.
None.
None.
=> Fix Gym example

tox.ini
Add missing dependencies to run the documentation build correctly.
None.
None.
=> fix tox docs testenvc

HISTORY.rst, aea/__version__.py, develop-image/docker-env.sh
Version number: `0.1.5`
TODO
None.
=> Release 0.1.5

docs/gym-plugin.md, docs/gym-skill.md, docs/index.md, docs/quickstart.md
Updating documentation for running the `gym_ex` skill and some minor edits.
https://github.com/fetchai/agents-aea/issues/137
=> Fixing gym_ex skill instructions and minor edits

.gitignore, aea/protocols/oef/models.py, tests/test_aea.py
This PR adds the implementation of constraint types (e.g. equality, set inclusion).
It is a work in progress. Tests are missing.
Fixes #23 
None.
=> Implementation of constraint types.

aea/protocols/oef/models.py, tests/test_aea.py, tests/test_agent.py
=> Fixes some tests

packages/skills/gym/rl_agent.py
This PR fixes an issue with the Gym skill example.
None/
None
=> fix import issue when running gym skill.

aea/aea.py, aea/registries/base.py, aea/skills/base.py, aea/skills/error/behaviours.py, aea/skills/error/handlers.py, aea/skills/error/tasks.py, aea/skills/scaffold/behaviours.py, aea/skills/scaffold/handlers.py, aea/skills/scaffold/tasks.py, packages/skills/echo/behaviours.py, packages/skills/echo/handlers.py, packages/skills/echo/tasks.py, packages/skills/fipa_negotiation/behaviours.py, packages/skills/fipa_negotiation/handlers.py, packages/skills/fipa_negotiation/tasks.py, packages/skills/gym/handlers.py, packages/skills/gym/tasks.py, tests/data/dummy_aea/skills/dummy/behaviours.py, tests/data/dummy_aea/skills/dummy/handlers.py, tests/data/dummy_aea/skills/dummy/tasks.py, tests/data/dummy_aea/skills/error/behaviours.py, tests/data/dummy_aea/skills/error/handlers.py, tests/data/dummy_aea/skills/error/tasks.py, tests/data/dummy_skill/behaviours.py, tests/data/dummy_skill/handlers.py, tests/data/dummy_skill/tasks.py
This PR completes the implementation of the setup method in skills and makes it a required method.
It fixes #156 
Docs already include reference to this.
=> Finishes implementing setup method throughout the stack, fixes #156

packages/skills/gym/behaviours.py, packages/skills/gym/skill.yaml
Restore `behaviours.py` modules to the Gym skill, so to make the Gym example working again.
None.
None
=> Restore `behaviours.py` module of the Gym skill.

tests/test_connections/test_local/test_search_services.py
Remove test on filter searches that turned out not to be very predictable. 
None.
It's not a big deal since the local node is going to disappear in the near future.
=> Remove flaky test on local OEF node for constrained searches.

packages/skills/weather_station/weather_station_data_model.py
=> Resolves linting errors

aea/aea.py
A previous commit swapped the order of two statements making one potentially fail.
Fixes the issue.
-
=> Fixes small issue in aea.py

aea/cli/__main__.py, aea/cli/list.py, aea/cli/search.py
Add list subcommand.
`aea list protocols`
`aea list connections`
`aea list skills`
Fixes #136 
None.
=> add list subcommand.

aea/connections/oef/connection.py, aea/protocols/fipa/message.py, aea/protocols/fipa/serialization.py, packages/skills/fipa_negotiation/dialogues.py, packages/skills/fipa_negotiation/handlers.py, packages/skills/weather_client/handlers.py, tests/data/dummy_aea/protocols/fipa/serialization.py, tests/test_connections/test_oef/test_communication.py
Change fipa message id field name from 'id' to 'message_id' 
Fixes #185 
None
=> Change fipa message id field name from 'id' to 'message_id'

packages/skills/echo/behaviours.py, packages/skills/echo/handlers.py, packages/skills/echo/tasks.py, packages/skills/fipa_negotiation/behaviours.py, packages/skills/fipa_negotiation/dialogues.py, packages/skills/fipa_negotiation/handlers.py, packages/skills/fipa_negotiation/transactions.py, packages/skills/gym/handlers.py, packages/skills/gym/rl_agent.py, packages/skills/gym/tasks.py, packages/skills/tac/game.py, packages/skills/tac/handlers.py
Removes print and replaces it with logging in packages.
-
-
=> Replace print with logging

setup.py
point to [neverpanic/connexion@jsonschema-3](https://github.com/neverpanic/connexion/tree/jsonschema-3) for dependency `connexion[swagger-ui]`.
None.
None.
=> point to neverpanic/connexion@jsonschema-3

aea/cli/__main__.py, aea/cli/common.py, aea/cli/run.py, aea/configurations/base.py, aea/configurations/schemas/aea-config_schema.json, aea/crypto/helpers.py, aea/crypto/wallet.py, tests/data/aea-config.example.yaml, tests/test_aea.py
=> Updates schema for private key paths

HISTORY.rst, aea/__version__.py, aea/cli_gui/__main__.py
This PR prepares develop for the new release.
If fixes minor bugs.
-
=> prepare develop for release 0.1.7

aea/decision_maker/messages/transaction.py
Changes 
```python
assert self.is_set("currency") ------> assert self.is_set("currency_pbk")
```
To mach the `super().__init__`
- [x ] Bugfix (non-breaking change which fixes an issue)
=> Consistency check bug fix in transaction.py

aea/cli/__main__.py, aea/cli/common.py, aea/cli/search.py, aea/connections/__init__.py, deploy-image/docker-env.sh, develop-image/docker-env.sh, setup.py
Do minor fixes before release `0.1.7`
-  [X] bump `develop-image` version number to `0.1.7`
-  [X] bump `deploy-image` version number to `0.1.7`
None.
None.
=> Prepare for release `0.1.7`

aea/cli/__main__.py, setup.py
This PR fixes setup.py for consistency with PyPI.
-
-
=> fixes setup.py dependency references

aea/cli_gui/__init__.py
I did a fix last pr which was incorrect and actually ended up breaking the starting of the OEF node from the gui. This fixes it.
Put an x in the boxes that apply
[x]  Bugfix (non-breaking change which fixes an issue)
[] New feature (non-breaking change which adds functionality)
[] Breaking change (fix or feature that would cause existing functionality to not work as expected)
Put an x in the boxes that apply.
[x] I have read the CONTRIBUTING doc
[x] I am making a pull request against the develop branch (left side). Also you should start your branch off our develop.
[x]  Lint and unit tests pass locally with my changes
[] I have added tests that prove my fix is effective or that my feature works
[] I have checked that the …
=> oef node starting - fixed

aea/connections/local/connection.yaml, aea/connections/oef/connection.yaml, aea/connections/scaffold/connection.yaml, aea/connections/stub/connection.yaml, aea/protocols/default/protocol.yaml, aea/protocols/fipa/protocol.yaml, aea/protocols/oef/protocol.yaml, aea/protocols/scaffold/protocol.yaml, aea/skills/error/skill.yaml, aea/skills/scaffold/skill.yaml, docs/file-structure.md, docs/index.md, docs/skill-guide.md, docs/skill.md, docs/steps.md, mkdocs.yml, packages/connections/gym/connection.yaml, packages/protocols/gym/protocol.yaml, packages/protocols/tac/protocol.yaml, packages/skills/echo/skill.yaml, packages/skills/fipa_negotiation/skill.yaml, packages/skills/gym/skill.yaml, packages/skills/tac/skill.yaml, packages/skills/weather_client/skill.yaml, packages/skills/weather_station/skill.yaml
This PR:
- introduces a guide which walks the developer through the process of writing a skill.
- updates the new description fields of the resource configs.
Fixes #193 
Note, when reviewing this, please follow the guide to see if the code works :)
=> Updates docs to incliude a skill developing guide, fixes #193

aea/cli_gui/static/css/home.css, aea/cli_gui/templates/home.html, aea/cli_gui/templates/home.js
Error message was not always visible of scrolled off screen - now it is + minor formatting improvements. 
#243
- [x ] Bugfix (non-breaking change which fixes an issue)
- [x ] I have read the [CONTRIBUTING](../master/CONTRIBUTING.rst) doc
- [x ] I am making a pull request against the `develop` branch (left side). Also you should start your branch off our `develop`.
=> Error message always shows at bottom of screen now

HISTORY.rst, aea/__version__.py, deploy-image/docker-env.sh, develop-image/docker-env.sh
Prepares develop for release.
-
-
=> Prepares develop for release v0.1.8

.github/pull_request_template.md, deploy-image/README.md, deploy-image/docker-env.sh, develop-image/README.md, develop-image/docker-env.sh
Update READMEs of Docker images `develop-image` and `deploy-image`.
Add links to them into PR release template.
None.
None.
=> Add details on Docker images publishing in PR release template.

docs/quickstart.md
Add instructions for Docker installation in Quickstart preliminaries.
This PR provides links to the official Docker website.
None.
None.
=> Add instructions for Docker installation in Quickstart preliminaries.

Pipfile, Pipfile.lock, docs/cli-gui.md, setup.py
Finally, this PR removes our connexion hack!
It fixes the fork dependency.
-
=> Fix the connexion depenceny and bump its version

aea/connections/local/connection.py
#280
- [x ] Bugfix (non-breaking change which fixes an issue)
- [x ] I have read the [CONTRIBUTING](../master/CONTRIBUTING.rst) doc
- [x ] I am making a pull request against the `develop` branch (left side). Also you should start your branch off our `develop`.
=> Bug Fix in connection.py handle_agent_message

aea/configurations/loader.py, setup.py
Fix the root path for the resolution of paths for JSON schemas on Windows.
None.
None.
=> Fix schema path resolution for Windows

aea/connections/base.py, aea/connections/local/connection.py, tests/test_connections/test_local/test_misc.py, tests/test_connections/test_local/test_search_services.py
Coverage to the local/connection.py 96%
- [x ] I have read the [CONTRIBUTING](../master/CONTRIBUTING.rst) doc
- [ x] I am making a pull request against the `develop` branch (left side). Also you should start your branch off our `develop`.
- [x ] Lint and unit tests pass locally with my changes
- [x ] I have added tests that prove my fix is effective or that my feature works
=> Tests for the local/connection

Jenkinsfile, aea/configurations/loader.py, aea/connections/base.py, aea/connections/local/connection.py, aea/registries/base.py, aea/skills/base.py, setup.py, tests/conftest.py, tests/test_cli/test_commands/test_gui.py, tests/test_cli/test_commands/test_run.py, tests/test_connections/test_local/test_misc.py, tests/test_connections/test_local/test_search_services.py, tests/test_crypto/test_crypto.py, tox.ini
Covers the tests for the crypto/base.py 
- [x ] I have read the [CONTRIBUTING](../master/CONTRIBUTING.rst) doc
- [x ] I am making a pull request against the `develop` branch (left side). Also you should start your branch off our `develop`.
- [x ] Lint and unit tests pass locally with my changes
=> 95% coverage on crypto/base.py

aea/cli_gui/__init__.py
GUI now lists all skills, connections and protocols from aea in virtual env as well as from packge registry dir. Previously it just listed from package dir. 
-
- [ x] I have read the [CONTRIBUTING](../master/CONTRIBUTING.rst) doc
- [ x] I am making a pull request against the `develop` branch (left side). Also you should start your branch off our `develop`.
- [x ] I have added necessary documentation (if appropriate)
- [x ] Any dependent changes have been merged and published in downstream modules
=> GUI bug fix

docs/quickstart.md
This steps seems to be needed for 'cytoolz' dependency, that needs to be built on the machine.
[https://github.com/pytoolz/cytoolz](https://github.com/pytoolz/cytoolz)
[https://pypi.org/project/cytoolz/](https://pypi.org/project/cytoolz/)
None.
None.
=> Add 'known issues' section to install missing headers.

aea/configurations/schemas/aea-config_schema.json, aea/configurations/schemas/connection-config_schema.json, aea/configurations/schemas/protocol-config_schema.json, aea/configurations/schemas/skill-config_schema.json, tests/conftest.py, tests/test_cli/test_commands/test_gui.py, tests/test_connections/test_local/test_search_services.py
This PR aims to avoid cross-platform issues when trying to import definitions from relative paths in JSON Schemas.
None.
None.
=> Avoid import from other files in json schemas.

examples/gym_ex/proxy/agent.py, examples/gym_ex/proxy/env.py
=> Fixes gym ex

HISTORY.rst, aea/__version__.py, deploy-image/docker-env.sh, develop-image/docker-env.sh
Prepare develop for release 0.1.10
-
-
=> Prepare develop for release 0.1.10

aea/cli/common.py, aea/crypto/fetchai.py, aea/crypto/helpers.py, aea/decision_maker/base.py, examples/weather_skills/README.md, packages/skills/weather_client_ledger/handlers.py, packages/skills/weather_client_ledger/skill.yaml, packages/skills/weather_station_ledger/handlers.py, packages/skills/weather_station_ledger/skill.yaml, scripts/fetchai_wealth_generation.py
Fix several issues in the Transaction Example with the weather agents.
None.
Some of them are temporary changes to the framework core. Must be revised at some point.
=> fix transaction example.

aea/helpers/base.py, tests/test_helpers/test_base.py
Reach 100% on 'aea/helpers/base.py'
None.
None.
=> 100% on 'aea/helpers/base.py'

aea/connections/local/connection.py, aea/protocols/oef/message.py, tests/test_helpers/__init__.py, tests/test_helpers/test_base.py, tests/test_helpers/test_dialogue/__init__.py, tests/test_helpers/test_dialogue/test_base.py, tests/test_protocols/test_oef_message.py
Added tests for the aea/helpers.
expected)
=> Almost 100% on aea/helpers

aea/cli/__init__.py, aea/cli/__main__.py, aea/cli/core.py, tests/test_cli/test_commands/test_misc.py
make `aea --version` print the true version number.
None.
None.
=> Make 'aea --version' print the true version number.

.github/pull_request_template.md
add item in the check list re. non-decreasing code coverage.
somehow related to #73 
None.
=> Add item in the check list re. non-decreasing code coverage.

aea/cli/__main__.py, aea/cli/core.py, tests/test_cli/test_commands/test_misc.py
Due to previous changes, the AEA CLI tool lost the sub-commands. Restore them.
None.
None.
=> Fix aea cli subcommands

docs/quickstart.md
This PR updates the Quickstart guide to include the stub connection usage.
Partially addresses #326 
-
=> Update docs to include guidance on stub connection

aea/aea.py, aea/decision_maker/base.py, aea/decision_maker/messages/state_update.py, aea/decision_maker/messages/transaction.py, aea/protocols/base.py, aea/registries/base.py, tests/data/dummy_aea/skills/dummy/handlers.py, tests/data/dummy_aea/skills/dummy/skill.yaml, tests/test_decision_maker/test_base.py, tests/test_registries.py
This PR introduces the concept of the `Filter`. The filter is responsible for keeping track of inactive skill components and for routing internal messages.
It addresses #295 
-
=> Initial implementation of filter concept

examples/weather_skills/README.md, packages/skills/weather_client_ledger/behaviours.py, packages/skills/weather_client_ledger/handlers.py, packages/skills/weather_client_ledger/skill.yaml
Ports the weather skills with ledger to the Filter approach.
-
-
=> Port weather skills w ledger to filter approach

Jenkinsfile, develop-image/Dockerfile, develop-image/docker-env.sh, tests/test_cli/test_gui.py, tox.ini
Run tests against Python 3.8
Fixes #263 
=> (WIP) Test/python3.8

aea/cli/add.py, aea/cli/common.py, aea/cli/core.py, aea/cli/install.py, aea/cli/remove.py, aea/cli/run.py, aea/cli/scaffold.py, aea/crypto/helpers.py, tests/test_cli/test_add/test_connection.py, tests/test_cli/test_add/test_protocol.py, tests/test_cli/test_add/test_skill.py, tests/test_cli/test_create.py, tests/test_cli/test_delete.py, tests/test_cli/test_install.py, tests/test_cli/test_misc.py, tests/test_cli/test_remove/test_connection.py, tests/test_cli/test_remove/test_protocol.py, tests/test_cli/test_remove/test_skill.py, tests/test_cli/test_run.py, tests/test_cli/test_scaffold/test_connection.py, tests/test_cli/test_scaffold/test_protocols.py, tests/test_cli/test_scaffold/test_skills.py
Fix `aea delete <aea-project-name>` such that it can only delete AEA project directories.
Fixes #248 
None.
=> Make `aea delete <project-name>` only delete AEA project directories.

aea/mail/base.py
This PR introduces the concept of `EnvelopeSerializer`. This interface will let the developer to specify a custom serialization format for the `Envelope` object, instead of relying necessarily on Protobuf.
The change is made in such a way that the code existing up to now is fully backwards compatible.
None.
None.
=> Add envelope serializer.

aea/aea.py, aea/cli/run.py, aea/registries/base.py, tests/conftest.py, tests/test_aea.py, tests/test_registries.py, tests/test_skills/test_base.py, tests/test_skills/test_error.py
This PR lets the developer to initialize the resources of an AEA programmatically.
Fixes #312 
=> Initialize AEA programmatically

Pipfile, Pipfile.lock, aea/connections/oef/connection.py, aea/connections/oef/connection.yaml, aea/crypto/ledger_apis.py, setup.py, tests/test_connections/test_oef/test_communication.py
This PR introduces changes to the oef connection which are making it more stable:
- bump to 0.8.1
- reconnection procedure via a separate thread
Addresses #359
Currently, this adds yet another thread to the connection. We will refactor this anyway in the context of moving to the multiplexer.
=> Bumps oef sdk to 0.8.1 and adds reconnection procedure

tests/data/aea-config.example_w_keys.yaml, tests/test_aea.py
=> Add test in aea

README.md
Updates the clone path.
If addresses #384 
-
=> Update clone path

aea/cli/run.py
This swaps the default connection public key to FETCHAI
-
Temporary fix for an issue with using non-compatible public keys
=> Change default wallet to FETCHAI

packages/skills/carpark_detection/behaviours.py
fixed bug in connection status for car parking skills
-
=> fixed status issues in car park skill

packages/skills/carpark_detection/behaviours.py
=> Minor fix of whitespace

aea/crypto/ledger_apis.py, tests/test_crypto/test_ledger_apis.py, tests/test_skills/test_base.py
This PR fixes a number of tests in the crypto module, including stubbing all remote calls.
-
=> Fix tests in crypto module

.gitignore, aea/cli/add.py, aea/cli/core.py, aea/cli/remove.py, aea/cli/scaffold.py
This PR removes two unnecessary files from the repo and makes the CLI logging more parsimonious and clear.
It fixes #404 and #356
-
=> Remove input and output files, simplify logging of cli

docs/cli-how-to.md, docs/gym-plugin.md, docs/gym-skill.md, docs/index.md, docs/quickstart.md, docs/skill-guide.md, docs/tac-skills.md, docs/version.md, docs/weather-skills.md
This fixes a few issues with the docs in response to developer feedback.
-
-
=> Fix docs issues

aea/connections/oef/connection.py, tests/test_connections/test_oef/test_communication.py
=> Remove unneeded lines

aea/aea.py, aea/agent.py, aea/cli/run.py, aea/connections/oef/connection.py, aea/connections/stub/connection.py, aea/connections/tcp/base.py, aea/mail/base.py, docs/connection.md, docs/core-components.md, docs/hacking-an-agent.md, tests/conftest.py, tests/test_aea.py, tests/test_agent.py, tests/test_connections/test_local/test_misc.py, tests/test_connections/test_local/test_search_services.py, tests/test_connections/test_oef/test_communication.py, tests/test_connections/test_stub.py, tests/test_connections/test_tcp/test_base.py, tests/test_connections/test_tcp/test_communication.py, tests/test_mail.py, tests/test_registries.py, tests/test_skills/test_base.py, tests/test_skills/test_error.py
This PR aims to remove the class `MailBox`, that became obsolete after the implementation of the class `Multiplexer`.
Fixes #414 
Docs need to be updated. Also, some namings in the tests code should to be updated.
=> Remove class MailBox.

docs/weather-skills.md, scripts/fetchai_wealth_generation.py
Instead of 'my_weather_X/...', 'weather_X/...' was used.
Related to #425 
=> Fix the documentation for the weather skill demo.

aea/cli/core.py, aea/crypto/helpers.py, docs/cli-commands.md, tests/test_aea.py, tests/test_cli/test_add_key.py, tests/test_cli/test_misc.py
This PR adds the command `aea add-key LEDGER FILE`.
TODOs:
Fixes #431 and #425 
=> add 'aea add-key LEDGER FILE' command.

tests/test_connections/test_local/test_search_services.py
Fix the Local Node search feature.
fixes #317 
=> Fix local node search

packages/skills/gym/rl_agent.py, packages/skills/gym/skill.yaml, packages/skills/gym/tasks.py, tests/test_packages/test_skills/test_gym.py
Reduce the number of steps. That required to parametrize the number of steps in the GymTask.
=> fix gym skill test.

aea/decision_maker/base.py, aea/protocols/fipa/dialogues.py, docs/car-park.md, docs/gym-skill.md, docs/tac-skills.md, docs/weather-skills.md, examples/gym_ex/proxy/agent.py, packages/protocols/tac/message.py, tests/test_examples/__init__.py, tests/test_examples/test_gym_ex.py
This PR resolves several issues with the current code base and docs and aligns both.
-
=> Fix docs and codebase issues

aea/cli/common.py, aea/cli/run.py, aea/cli_gui/__init__.py, aea/connections/local/connection.py, aea/connections/oef/connection.py, aea/connections/stub/connection.py, aea/connections/tcp/tcp_client.py, aea/connections/tcp/tcp_server.py, tests/test_cli/test_run.py, tests/test_packages/test_skills/test_echo.py, tests/test_packages/test_skills/test_gym.py
Ths PR changes the option `--connection` to `--connections` in `aea run`.
Fixes #423 
=> Add multiple connections to 'aea run' option '--connections'.

HISTORY.rst, aea/__version__.py, deploy-image/docker-env.sh, develop-image/docker-env.sh
This PR prepares develop for release v0.1.14
-
-
=> Prepares develop for release v0.1.14

packages/connections/gym/connection.py, tests/conftest.py, tests/test_connections/test_oef/test_communication.py, tests/test_packages/test_connections/test_gym.py, tests/test_packages/test_protocols/test_gym.py, tests/test_packages/test_protocols/test_tac.py
Tests for packages connections/ protocols
=> Tests for packages connections and protocols

aea/connections/tcp/tcp_server.py, docs/car-park.md, packages/skills/carpark_client/skill.yaml, tests/test_packages/test_skills/test_carpark.py
Made rather station ledger tests and carpark test - though neither tests the tty out, 
-
- [] Lint and unit tests pass locally with my changes
=> got weather skill working and made carpark skill

Pipfile, Pipfile.lock, aea/connections/p2p/connection.py, setup.cfg, setup.py, tests/test_connections/test_p2p_connection/test_p2p.py
=> fix implementation of p2p connection.

aea/connections/stub/connection.py, docs/hacking-an-agent.md, mkdocs.yml
Done a walkthrough - also fixed an issue where stub connection failed to read message if it was on the last line of the file without a carriage return
-
=> Docs now have walkthrough of building an AEA with code api

aea/decision_maker/base.py, aea/decision_maker/messages/transaction.py, aea/registries/base.py, packages/protocols/tac/message.py, packages/protocols/tac/serialization.py, packages/protocols/tac/tac.proto, packages/protocols/tac/tac_pb2.py, packages/skills/carpark_client/handlers.py, packages/skills/ml_train/handlers.py, packages/skills/tac_control/handlers.py, packages/skills/tac_negotiation/handlers.py, packages/skills/tac_negotiation/helpers.py, packages/skills/tac_participation/handlers.py, packages/skills/tac_participation/skill.yaml, packages/skills/weather_client_ledger/handlers.py, tests/test_decision_maker/test_base.py, tests/test_decision_maker/test_messages/test_transaction.py
Add necessary changes to make tac work end to end
-
=> add changes to mac tac work end to end

aea/connections/p2p/connection.py, tests/test_aea.py, tests/test_registries.py, tox.ini
- Fix `tox.ini` configuration. `whitelist_externals` was not used correctly.
- Fix `receiving_loop` in `P2PConnection`. There was a concurrency issue when the connection was disconnected.
- Other minor issues.
=> fix several issues in tests.

packages/skills/tac_control/behaviours.py, packages/skills/tac_control/game.py, packages/skills/tac_control/handlers.py, packages/skills/tac_negotiation/handlers.py, packages/skills/tac_negotiation/transactions.py, packages/skills/tac_participation/game.py, packages/skills/tac_participation/handlers.py
This PR introduces several fixes to the tac skills.
-
-
=> add several fixes to the tac skills

aea/aea.py, aea/connections/p2p/connection.py, aea/registries/base.py, aea/skills/base.py, aea/skills/behaviours.py, packages/skills/tac_control/behaviours.py, packages/skills/tac_control/game.py, packages/skills/tac_control/handlers.py, packages/skills/tac_negotiation/handlers.py, packages/skills/tac_negotiation/transactions.py, packages/skills/tac_participation/game.py, packages/skills/tac_participation/handlers.py, tests/test_aea.py, tests/test_registries.py, tox.ini
Introduce behaviour hierarchy (e.g. `CyclicBehaviour`, `OneShotBehaviour` etc.)
Notice that at the moment `Behaviour` is equivalent to `CyclicBehaviour`.
Fixes #400 
=> first prototype of behaviour hierarchy.

aea/cli/common.py, aea/cli/search.py, aea/connections/p2p/connection.py, aea/connections/stub/connection.py, aea/mail/base.py, tests/test_connections/test_p2p.py, tests/test_decision_maker/test_messages/test_transaction.py, tests/test_helpers/test_dialogue/test_base.py, tests/test_protocols/test_fipa.py
=> Minor test additions

packages/protocols/ml_trade/message.py, packages/protocols/ml_trade/serialization.py, packages/protocols/tac/serialization.py, tests/test_connections/test_p2p.py, tests/test_decision_maker/test_messages/test_transaction.py, tests/test_packages/test_protocols/test_ml_message.py, tests/test_packages/test_protocols/test_tac.py
Added tests for the packages/protocols - ML_trade, Tac
Fixes #451 
=> 100% on packages/protocols

aea/mail/base.py, tests/test_mail.py
Adds URI scaffold for forward compatibility with the Envelopes in the p2p network.
It addresses #413 
-
=> Adds URI class

aea/aea.py, aea/skills/base.py, aea/skills/behaviours.py, packages/skills/carpark_client/behaviours.py, packages/skills/carpark_client/skill.yaml, packages/skills/carpark_client/strategy.py, packages/skills/carpark_detection/behaviours.py, packages/skills/ml_data_provider/behaviours.py, packages/skills/ml_data_provider/skill.yaml, packages/skills/ml_train/behaviours.py, packages/skills/ml_train/skill.yaml, packages/skills/ml_train/strategy.py, packages/skills/weather_client/behaviours.py, packages/skills/weather_client/skill.yaml, packages/skills/weather_client/strategy.py, packages/skills/weather_client_ledger/behaviours.py, packages/skills/weather_client_ledger/skill.yaml, packages/skills/weather_client_ledger/strategy.py, packages/skills/weather_station/behaviours.py, packages/skills/weather_station_ledger/behaviours.py
This PR aims to use the new behaviours in existing skills.
=> Use new behaviours in existing skills

aea/cli/core.py, aea/configurations/base.py, tests/test_cli/test_add/test_connection.py, tests/test_cli/test_add/test_protocol.py, tests/test_cli/test_add/test_skill.py, tests/test_cli/test_add_key.py, tests/test_cli/test_create.py, tests/test_cli/test_delete.py, tests/test_cli/test_freeze.py, tests/test_cli/test_generate_key.py, tests/test_cli/test_gui.py, tests/test_cli/test_install.py, tests/test_cli/test_list.py, tests/test_cli/test_remove/test_connection.py, tests/test_cli/test_remove/test_protocol.py, tests/test_cli/test_remove/test_skill.py, tests/test_cli/test_run.py, tests/test_cli/test_scaffold/test_connection.py, tests/test_cli/test_scaffold/test_protocols.py, tests/test_cli/test_scaffold/test_skills.py, tests/test_cli/test_search.py
This PR ask for confirmation when generating the private key.
Fixes #433 
=> Ask confirmation overwriting private key

aea/cli/add.py, aea/cli/common.py, aea/cli/core.py, aea/cli/create.py, aea/configurations/base.py, tests/test_cli/test_create.py
=> Prevent 'aea create' within an AEA project

aea/cli_gui/__init__.py, aea/cli_gui/__main__.py
=> Fixed flake8 problems

aea/cli/common.py, aea/cli/config.py, aea/cli/search.py, aea/configurations/base.py, tests/test_gui/test_search.py
`aea config set` if the value is not valid against the json schema it will overwrite the target yaml file.
=> fix issues in aea config

tests/test_packages/test_protocols/test_ml_message.py
Added `np.array_equal` in order to compare np arrays.
Fixes #496 
=> Added the correct way to compare np.arrays

aea/cli/push.py, aea/cli/registry/push.py, aea/cli/registry/utils.py, tests/test_cli/test_misc.py, tests/test_cli/test_registry/test_push.py, tests/test_cli/test_registry/test_utils.py
Local "push" item implemented, handling ConnectionError while request added
Local "push" item implemented, handling ConnectionError while request added
=> Local "push" item implemented, handling ConnectionError added

aea/cli/add.py, aea/cli/common.py, aea/cli/fetch.py, aea/cli/publish.py, aea/cli/registry/fetch.py, aea/cli/registry/publish.py, aea/cli/registry/push.py, aea/cli/registry/utils.py, packages/connections/tcp/connection.yaml, packages/skills/carpark_client/skill.yaml, packages/skills/carpark_detection/skill.yaml, packages/skills/weather_client/skill.yaml, packages/skills/weather_client_ledger/skill.yaml, packages/skills/weather_station/skill.yaml, packages/skills/weather_station_ledger/skill.yaml, tests/test_cli/test_common.py, tests/test_cli/test_registry/test_fetch.py, tests/test_cli/test_registry/test_publish.py, tests/test_cli/test_registry/test_push.py, tests/test_cli/test_registry/test_utils.py, tests/test_gui/test_search.py
Local agent save implemented + tests.
=> Local publish implemented + tests. Incl. small refactoring.

aea/cli/common.py, aea/cli/create.py, aea/cli/search.py, aea/cli_gui/__init__.py, tests/test_cli/test_remove/test_connection.py, tests/test_cli/test_remove/test_protocol.py, tests/test_cli/test_remove/test_skill.py, tests/test_cli/test_search.py
Add `local-registry-dir` option to `aea search`.
Fixes part of #564 
=> Add local-registry-dir option to 'aea search'

aea/cli/add.py, tests/test_cli/test_add/test_connection.py, tests/test_cli/test_add/test_protocol.py, tests/test_cli/test_add/test_skill.py
Fix `aea add [item-type] PUBLIC_ID` such that it checks that the selected item has a public id equal to `PUBLIC_ID`.
Fixes part of #564 
=> Check public id of added package

aea/cli/push.py, aea/cli/registry/push.py, tests/test_cli/test_registry/test_push.py
`aea push` now accepts only public ids.
Fixes part of #564 
=> 'aea push' now accepts only public ids.

aea/cli/common.py, aea/cli/search.py, aea/configurations/base.py, tests/test_cli/test_search.py
Agents search in registry implemented + test.
------
=> Agents search in registry implemented + test.

aea/cli/run.py, aea/configurations/base.py, aea/configurations/loader.py, aea/configurations/schemas/aea-config_schema.json, aea/configurations/schemas/definitions.json, aea/crypto/base.py, aea/crypto/ethereum.py, aea/crypto/fetchai.py, aea/crypto/ledger_apis.py, packages/skills/carpark_detection/handlers.py, packages/skills/weather_station_ledger/handlers.py, tests/data/aea-config.example_w_keys.yaml, tests/data/gym-connection.yaml, tests/test_cli/test_run.py, tests/test_cli/test_search.py, tests/test_configurations/test_schema.py, tests/test_crypto/test_ledger_apis.py, tests/test_decision_maker/test_base.py, tests/test_packages/test_skills/test_carpark.py, tests/test_packages/test_skills/test_echo.py, tests/test_packages/test_skills/test_gym.py, tests/test_packages/test_skills/test_ml_skills.py, tests/test_packages/test_skills/test_weather.py, tests/test_packages/test_skills/test_weather_ledger.py, tests/test_skills/test_base.py
This PR introduces the `LedgerApi` abstraction in order to get a better organization of the code and improve flexibility and extendabiity of the crypto features of the framework.
Fixes #555 
=> Introduce 'LedgerApi' abstract class.

aea/cli/fetch.py, aea/cli/publish.py, aea/cli/push.py, aea/cli/registry/fetch.py, aea/cli/registry/utils.py, tests/test_cli/test_registry/test_fetch.py, tests/test_cli/test_registry/test_utils.py
Bugfix: CLI outstanding issues:
#564, #565
=> Bugfix: CLI outstanding issues

aea/cli/add.py, aea/cli/core.py, aea/cli/create.py, docs/car-park.md, docs/core-components.md, docs/gym-skill.md, docs/ml-skills.md, docs/quickstart.md, docs/tac-skills.md, docs/weather-skills.md
Multiple small updates to docs.
It fixes #532 
-
=> Small doc updates

aea/cli/registry/publish.py, tests/test_cli/test_registry/test_publish.py
CLI Publish agent with dependencies implemented, test updated.
es
=> AEA-239 CLI Publish agent with dependencies implemented, test updated.

aea/helpers/base.py
Fix `aea.helpers.import_module` utility function to create a virtual root package if not present.
None.
=> add virtual root package

aea/cli/add.py, aea/cli/common.py, aea/cli/fetch.py, aea/cli/publish.py, tests/test_cli/test_fetch.py, tests/test_cli/tools_for_testing.py
Local fetch agent with deps implemented, tests updated.
Fixes #600 
=> Local fetch with dependencies implemented, tests updated.

HISTORY.rst, aea/__version__.py, deploy-image/docker-env.sh, develop-image/docker-env.sh, docs/logging.md, docs/version.md, packages/fetchai/agents/car_data_buyer/aea-config.yaml, packages/fetchai/agents/car_detector/aea-config.yaml, packages/fetchai/agents/ml_data_provider/aea-config.yaml, packages/fetchai/agents/ml_model_trainer/aea-config.yaml, packages/fetchai/agents/my_first_agent/aea-config.yaml
This PR prepares develop for release 0.1.16
-
-
=> prepare develop for 0.1.16

tests/test_packages/test_connections/test_oef/test_communication.py, tests/test_packages/test_connections/test_tcp/test_base.py, tests/test_packages/test_protocols/test_fipa.py
Quick fix of import paths.
-
-
=> fix import paths

aea/cli/registry/publish.py, aea/cli/registry/push.py, aea/cli/registry/utils.py, tests/test_cli/test_registry/test_publish.py, tests/test_cli/test_registry/test_push.py, tests/test_cli/test_registry/test_utils.py
Author name validation before push/publish implemented + tests. #627 
------
=> Author name validation before push/publish implemented + tests (AEA-271)

docs/raspberry-set-up.md, docs/weather-skills.md, mkdocs.yml
Added a section for raspberry setup. Updated weather-skill to use connections.yalm to change the IP address.
No open issue.
=> Update weather-skill docs and added a raspberry-set-up.md

aea/cli/common.py, aea/cli/config.py, docs/cli-commands.md, tests/test_cli/test_config.py
Make `aea config` work with vendor configurations.
First step toward fixing #595 
EDIT: after 58ec704: fix #595
=> make 'aea config' work with vendor configurations

tests/test_packages/test_connections/test_gym.py, tests/test_packages/test_connections/test_local/test_misc.py, tests/test_packages/test_connections/test_oef/test_communication.py, tests/test_packages/test_connections/test_tcp/test_base.py
Update public ids in Envelope constructor arguments of some tests, due to the changes introduced by #652 
None.
=> update public ids in Envelope constructor arguments of some tests.

aea/decision_maker/base.py, aea/decision_maker/messages/transaction.py, packages/fetchai/skills/carpark_client/handlers.py, packages/fetchai/skills/ml_train/handlers.py, packages/fetchai/skills/tac_negotiation/transactions.py, packages/fetchai/skills/weather_client/handlers.py
Update obsolete usage of ids and use public ids instead. These were missing changes that should have been done in #652 
=> Fix more bugs after #652

aea/registries/base.py, aea/skills/base.py, packages/fetchai/skills/tac_control/behaviours.py, packages/fetchai/skills/tac_negotiation/behaviours.py, packages/fetchai/skills/tac_participation/handlers.py
This PR lets the skill to be turned off programmatically.
Fixes #265 
=> AEA-224 Let a skill to be turned off programmatically

aea/cli/publish.py, aea/cli/registry/fetch.py, tests/test_cli/test_publish.py, tests/test_cli/test_registry/test_fetch.py, tests/test_cli/tools_for_testing.py
… Incl tests.
Checking dependencies before local agent publish implemented. Incl some small fixes + tests.
#636 
Fetch command fixed (wrong public ID creation), creating dirs before local fetch added.
=> Local publish dependencies check added, small fixes to fetch command

aea/crypto/fetchai.py, tests/test_crypto/test_ledger_apis.py
Part2 of the transaction validation. This covers the Fetchai side.
#574 
=> AEA-247 generate_tx_nonce for fetchai and validate tx

docs/generator.md
Adds documentation for protocol generator.
=> AEA-307 Adding documentation for protocol generator

aea/protocols/generator.py, examples/protocol_specification_ex/default.yaml, examples/protocol_specification_ex/fipa.yaml, examples/protocol_specification_ex/gym.yaml, examples/protocol_specification_ex/ml_trade.yaml, examples/protocol_specification_ex/oef.yaml, examples/protocol_specification_ex/output/two_party_negotiation/message.py, examples/protocol_specification_ex/sample.yaml, examples/protocol_specification_ex/tac.yaml, tests/data/sample_specification.yaml
Adding standardised types for protocol specification. 
Converting these types to their equivalents in the target programming language (currently Python) 
=> AEA-307 Adding standard specification Types

aea/cli/add.py, aea/cli/common.py, aea/cli/core.py, aea/cli/create.py, aea/cli/generate.py, aea/cli/install.py, aea/cli/login.py, aea/cli/publish.py, aea/cli/push.py, aea/cli/registry/fetch.py, aea/cli/registry/utils.py, aea/cli/remove.py, aea/cli/run.py, aea/cli/scaffold.py, docs/cli-commands.md, tests/test_cli/test_common.py, tests/test_cli/test_login.py, tests/test_cli/test_publish.py, tests/test_cli/test_push.py, tests/test_cli/test_registry/test_utils.py
- item unpacking path on add fixed (added `vendor` subpath)
- logic command call changed to `aea login USERNAME --password=[password]`
- tests fixed
- docs updated
#578 
=> AEA-311 AEA-264 AEA-243 Bugfix/registry compatibility

aea/crypto/ethereum.py, aea/crypto/ledger_apis.py, docs/tac-skills.md, docs/thermometer.md, docs/weather-skills.md, packages/fetchai/skills/weather_client/skill.yaml, packages/fetchai/skills/weather_client/strategy.py, tests/data/dummy_aea/aea-config.yaml, tests/test_cli/test_run.py, tests/test_crypto/test_ledger_apis.py
Added an assertion to check if the estimated gas is less than the provided gas.
#638 
=> Tx_misconfiguration for ethereum

tests/test_packages/test_skills/test_thermometer.py
Adds a test for the thermometer skill.
- 
=> Test for theremometer skill based on the weather one without ledger

docs/aea-vs-mvc.md, docs/integration.md, docs/protocol.md, mkdocs.yml
Adds a few sentences on comparing AEA framework with MVC frameworks conceptually.
Adds some small info on ledger apis.
#667
-
=> AEA-295 add section on mvc and ledger apis

Pipfile.lock
After `pipenv update watchdog` we've got a clean execution of `tox -e py37 -- --no-integration-tests --ci`, i.e. without warnings.
```
=================================================================================== 643 passed, 47 skipped in 117.83s (0:01:57) ===================================================================================
_____________________________________________________________________________________________________ summary _____________________________________________________________________________________________________
py37: commands succeeded
congratulations :)
```
Fixes #581 
=> Fixed watchdog warnings

docs/ml-skills.md, docs/weather-skills.md
Adds the discussion section to the docs of weather and ml skills.
-
=> AEA-294 Adds the discussion section to the docs of weather and ml skills.

aea/aea.py, aea/protocols/base.py
Remove the `Protocol.check` method of the class `aea.protocols.base.Protocol`, since it was not utilized.
Fixes #639 
=> Remove `Protocol.check` method.

docs/car-park-skills.md, docs/gym-skill.md, docs/ml-skills.md, docs/raspberry-set-up.md, docs/tac-skills.md, docs/thermometer-skills.md, docs/weather-skills.md, mkdocs.yml, packages/fetchai/skills/ml_data_provider/skill.yaml
Part2 of the improvement of the existing demos. 
-
=> AEA-294 AEA-315 Improve existing demo guides.

README.md
=> Update readme and remove outdated commands

aea/cli/remove.py
Fix of failure on local item remove.
#719 
=> Checking if item present in vendor or local items changed

packages/fetchai/skills/generic_seller/generic_data_model.py
Fix the is instance check inside the DataModel file.
- 
=> Fixed the isinstance() in the datamodel

packages/fetchai/skills/carpark_detection/detection_database.py
Changed the way we are adding the data in the database.
-
=> Changes based on bandit report B608

tests/test_cli/test_registry/test_publish.py, tests/test_cli/test_registry/test_push.py, tests/test_cli/test_registry/test_utils.py, tests/test_registries.py, tests/test_skills/test_behaviours.py, tests/test_skills/test_error.py, tests/test_task.py
=> Fix tests before release 0.2.0

Jenkinsfile, docs/agent-vs-aea.md, docs/skill.md, tests/test_cli/test_generate/test_protocols.py, tests/test_skills/test_base.py, tox.ini
=> fixes temp file

tests/test_examples/test_gym_ex.py, tests/test_packages/test_skills/test_generic_aea.py, tests/test_packages/test_skills/test_weather_ledger.py
This PR fixes some issues in the tests on the skills packages.
=> Fix skill packages tests.

docs/oef-ledger.md, docs/skill-guide.md
Fixes small issues with the docs
-
-
=> small docs update to remove oef links

aea/cli/push.py, tests/test_cli/test_push.py, tests/test_cli/tools_for_testing.py
CLI push covered with tests 100%
#684 
=> AEA-360 CLI push covered with tests 100%

docs/car-park-skills.md, docs/generic-skills.md, docs/thermometer-skills.md, docs/weather-skills.md
Update misconfigurations in docs. Update the skill paths to contain the `vendor/fetchai/skills`.
-
=> Update misconfigurations in docs.

aea/cli/fetch.py, tests/test_cli/test_common.py, tests/test_cli/test_config.py, tests/test_cli/test_fetch.py, tests/test_cli/test_generate/test_generate.py, tests/test_cli/test_install.py, tests/test_cli/test_publish.py, tests/test_cli/test_push.py, tests/test_cli/tools_for_testing.py
Test coverage on `aea.cli`
#684 
=> WiP Test/cli coverage AEA-360

aea/cli/install.py, aea/cli/registry/settings.py, aea/cli_gui/__init__.py, aea/protocols/generator.py, packages/fetchai/connections/oef/connection.py, packages/fetchai/protocols/fipa/serialization.py, packages/fetchai/protocols/gym/serialization.py, packages/fetchai/protocols/ml_trade/serialization.py, packages/fetchai/protocols/oef/serialization.py, packages/fetchai/skills/carpark_detection/behaviours.py, scripts/oef/launch.py, tests/common/oef_search_pluto_scripts/launch.py, tests/conftest.py, tests/test_aea.py, tests/test_cli/test_gui.py, tests/test_cli/test_run.py, tests/test_connections/test_stub.py, tests/test_examples/test_gym_ex.py, tests/test_multiplexer.py, tests/test_packages/test_connections/test_oef/test_models.py, tests/test_packages/test_skills/test_carpark.py, tests/test_packages/test_skills/test_echo.py, tests/test_packages/test_skills/test_generic_aea.py, tests/test_packages/test_skills/test_gym.py, tests/test_packages/test_skills/test_ml_skills.py, tests/test_packages/test_skills/test_thermometer.py, tests/test_packages/test_skills/test_weather.py, tests/test_packages/test_skills/test_weather_ledger.py, tox.ini
Remove bandit skips from testenvs `bandit-main` and `bandit-tests`.
Fixes #724 
=> Remove `bandit` skips

aea/protocols/generator.py, examples/protocol_specification_ex/output/two_party_negotiation/TwoPartyNegotiation_pb2.py, examples/protocol_specification_ex/output/two_party_negotiation/message.py, examples/protocol_specification_ex/output/two_party_negotiation/serialization.py, examples/protocol_specification_ex/output/two_party_negotiation/twoPartyNegotiation.proto, tests/data/sample_specification.yaml
Added performative and contents encoding in serialisation.py
Addressed failures in tests
code reformatting
=> AEA-361 Performative and content in encode in serialisation.py

docs/quickstart.md
Changes the Quickstart guide to follow https://docs.fetch.ai/getting-started/quickstart/
#766 
=> AEA-313 First draft for quickstart

docs/questions-and-answers.md
Added more questions based on the feedback.
- 
=> Update q&a. Added more questions/answers

aea/skills/behaviours.py, tests/test_skills/test_behaviours.py
Update the `FSMBehaviour`
Fixes #530 
=> AEA-347 - update Finite State Machine Behaviour.

mkdocs.yml
=> add ordering of f docs

aea/protocols/generator.py, docs/generator.md, examples/protocol_specification_ex/output/two_party_negotiation/TwoPartyNegotiation_pb2.py, examples/protocol_specification_ex/output/two_party_negotiation/message.py, examples/protocol_specification_ex/output/two_party_negotiation/serialization.py
The generator adds decoding for performatives and contents
=> AEA-361 Decoding of performatives and contents

Jenkinsfile
Changes to Jenkins pipeline to avoid unnecessary runs on failure. This increases the time the pipeline takes to finish in a green case.
-
-
=> Change Jenkins stages

docs/index.md, docs/quickstart.md
This PR adds embedded videos of the tutorials to the docs
-
=> adds tutorial videos to docs

tests/test_packages/test_skills/test_echo.py, tests/test_packages/test_skills/test_generic_aea.py
This PR fixes the echo and generic aea tests to close down subprocesses properly.
-
-
=> fix echo and generic aea tests

tests/test_packages/test_skills/test_carpark.py
Re-ordered the code and added try/finally code inside the test.
-
=> Refactored test_carpark.py

tests/test_docs/test_skill_guide/test_skill_guide.py, tests/test_examples/test_gym_ex.py, tests/test_multiplexer.py, tests/test_packages/test_skills/test_echo.py, tests/test_packages/test_skills/test_generic_aea.py, tests/test_packages/test_skills/test_gym.py, tests/test_packages/test_skills/test_ml_skills.py, tests/test_skills/test_error.py
This PR fixes several instances of misused subprocess and Thread, adding try, finally blocks where needed
-
-
=> addresses misusage of subprocess and Thread

tests/test_packages/test_skills/test_thermometer.py, tests/test_packages/test_skills/test_weather.py, tests/test_packages/test_skills/test_weather_ledger.py
Fix test weather skill (No ledger) to not trying to interact with ledger.
-
=> Fix weather test

aea/cli/install.py, tests/test_cli/test_run.py
=> fixes to cli tests

aea/cli/install.py, tests/test_cli/test_registry/test_fetch.py
=> add further tests

tests/test_cli/test_run.py, tests/test_packages/test_skills/test_weather.py
Fixed test weather_client to change the config file on runtime. 
Changed the paths in test_run to mirror other code.
- 
=> Minor changes on the tests

aea/skills/base.py, aea/skills/behaviours.py, tests/test_skills/test_base.py, tests/test_skills/test_behaviours.py
Skills subpackage covered 100%
#684 
------
=> AEA skills coverage 100% AEA-360

aea/connections/base.py, tests/test_connections/test_base.py, tests/test_connections/test_stub.py, tests/test_skills/test_tasks.py
Missing  from previous pr module covered. Incl. some smaller coverage gaps filling.
#684 
=> aea.skills.tasks & aea.connections covered with tests 100% AEA-360

HISTORY.md, aea/__version__.py, deploy-image/docker-env.sh, develop-image/docker-env.sh, docs/logging.md, docs/thermometer-skills-step-by-step.md, docs/version.md, packages/fetchai/agents/car_data_buyer/aea-config.yaml, packages/fetchai/agents/car_detector/aea-config.yaml, packages/fetchai/agents/ml_data_provider/aea-config.yaml, packages/fetchai/agents/ml_model_trainer/aea-config.yaml, packages/fetchai/agents/my_first_aea/aea-config.yaml, packages/fetchai/agents/weather_client/aea-config.yaml, packages/fetchai/agents/weather_station/aea-config.yaml, tests/data/dummy_aea/aea-config.yaml
This PR prepares develop for the next release: v0.2.1
-
-
=> prepare develop for v0.2.1

README.md, setup.py
=> small layout fixes and setup.py

docs/index.md
Some links in the index.md were wrongly pointing to the parent segment of
the URL path. Since index.md corresponds to the root page of the
website, there's no need for that.
=> fix broken links in docs/index.md.

docs/generator.md, docs/logging.md, docs/quickstart.md, tests/test_docs/test_bash_yaml/md_files/bash-generator.md, tests/test_docs/test_bash_yaml/md_files/bash-logging.md, tests/test_docs/test_bash_yaml/md_files/bash-quickstart.md, tests/test_docs/test_bash_yaml/md_files/bash-scaffolding.md
Adds more tests for yaml and bash codeblocks. 
#770 
=> AEA-380 More tests for docs

tests/test_cli_gui/test_run_oef.py
Fixes a missing oef skip in tests
-
-
=> fix oef test skip

packages/fetchai/skills/ml_train/skill.yaml
Pin `tensorflow` version to `1.14.0` in ml_train skill.
=> Pin 'tensorflow' version to '1.14.0' in ml_train skill.

aea/cli/core.py, tests/test_cli/test_core.py, tests/test_cli/tools_for_testing.py
CLI core 100% covered + small refactoring.
=> CLI core 100% covered + small refactoring.

Pipfile, tests/test_cli/test_add_key.py, tests/test_decision_maker/test_base.py, tests/test_decision_maker/test_ownership_state.py, tests/test_packages/test_connections/test_p2p_client.py, tests/test_protocols/test_base.py, tests/test_skills/test_base.py, tox.ini
This PR introduces `pytest-randomly`.
Tests to fix:
Fixes #775 
=> AEA-383 Introduce pytest-randomly

Makefile
Add the clean of:
- coverage.xml was missing
- pip-wheel-metadata/ is due to the introduction of pyproject.toml (see #828)
=> add more clean subcommands to Makefile.

tests/test_decision_maker/test_base.py, tests/test_mail.py
Covers mailbox 100%
Decision maker transaction 100%
- 
=> Covered mail base and decision maker transaction.py

scripts/check_copyright_notice.py
update copyright check script.
=> update copyright check script.

docs/cli-vs-programmatic-aeas.md, docs/connect-a-frontend.md, docs/questions-and-answers.md
Adds the changes suggested by Cristina to the docs.
-
-
=> docs fixes based on PR comments

.github/workflows/workflow.yml, Makefile, README.md, aea/cli/install.py, tests/test_cli/test_freeze.py, tests/test_cli/test_install.py, tests/test_cli/test_list.py, tests/test_connections/test_stub.py, tests/test_docs/test_agent_vs_aea/test_agent_vs_aea.py, tests/test_docs/test_build_aea_programmatically/test_programmatic_aea.py, tests/test_docs/test_multiplexer_stand_alone/test_multiplexer_stand_alone.py, tests/test_docs/test_standalone_decision_maker_transaction/test_decision_maker_transaction.py, tests/test_docs/test_standalone_transaction/test_standalone_transaction.py
Adds the `--ci` flag back in. Adds a timeout.
-
=> update workflow yaml

Makefile, aea/cli/install.py
=> small fixes and commands

aea/agent.py, aea/cli/common.py, aea/cli/config.py, aea/cli/core.py, aea/cli/create.py, aea/cli/search.py, aea/cli_gui/__init__.py, aea/configurations/loader.py, aea/connections/base.py, aea/context/base.py, aea/crypto/ethereum.py, aea/crypto/fetchai.py, aea/crypto/ledger_apis.py, aea/crypto/wallet.py, aea/decision_maker/base.py, aea/helpers/dialogue/base.py, aea/helpers/search/models.py, aea/mail/base.py, aea/registries/base.py, aea/skills/base.py, aea/skills/tasks.py
This PR fixes some issues raised by `pip install pylint` with the following config:
```
[MESSAGES CONTROL]
disable=C0103, C0123, C0330, C0301, E0602, E1101, R0401, R0801, R0902, R0903, R0904, R0911, R0912, R0913, R0914, R1705, W0107, W0221, W0223, W0622, W0703, W1202
ignore-patterns=generator.py,base_pb2.py
good-names=logger, T, e
```
-
=> address pylint issues

MANIFEST.in, setup.py
Due to the update of the Manifest file (e.g. look at commit 57a44c54ab8bda729070ed43b405564f1b7929da), a hidden bug popped up. The 'setup.py' has not been updated correctly (long time ago) when *.json files have been moved from their original position. Moreover, the *.yaml files have not been added when introduced.
Use the 'package_data' parameter of the 'setup' function, as explained here:
https://setuptools.readthedocs.io/en/latest/setuptools.html#including-data-files
Moreover, apply black formatting to the setup.py file.
Fixes #883 
This commit should be `git cherry-pick`ed for `develop`.
=> Fix packaging issue

MANIFEST.in, setup.py
=> fix packaging issue (develop)

packages/fetchai/skills/generic_seller/behaviours.py
Replace `self.context.self.context` with `self.context`.
=> Fix typo in `generic_seller` skill

aea/cli/common.py
=> fix file open if non exist

aea/connections/stub/connection.py, docs/agent-vs-aea.md, docs/build-aea-programmatically.md, docs/multiplexer-standalone.md, docs/quickstart.md, tests/conftest.py, tests/test_cli/test_add/test_connection.py, tests/test_cli/test_add/test_protocol.py, tests/test_cli/test_add/test_skill.py, tests/test_cli/test_common.py, tests/test_cli/test_push.py, tests/test_cli/test_registry/test_push.py, tests/test_cli/tools_for_testing.py, tests/test_configurations/test_base.py, tests/test_decision_maker/test_base.py, tests/test_decision_maker/test_ownership_state.py, tests/test_docs/test_agent_vs_aea/agent_code_block.py, tests/test_docs/test_agent_vs_aea/test_agent_vs_aea.py, tests/test_docs/test_bash_yaml/md_files/bash-quickstart.md, tests/test_docs/test_build_aea_programmatically/programmatic_aea.py, tests/test_docs/test_build_aea_programmatically/test_programmatic_aea.py, tests/test_docs/test_multiplexer_stand_alone/multiplexer_standalone.py, tests/test_docs/test_multiplexer_stand_alone/test_multiplexer_stand_alone.py, tests/test_docs/test_skill_guide/test_skill_guide.py
Fixes the envelopes fed to the stub connection for usage with default protocol.
-
-
=> fix envelopes for default protocol

aea/registries/base.py
Load only the agent components specified in `aea-config.yaml`.
Connections are automatically filtered by 'aea run'.
Fixes #797 
=> Load only specified packages

HISTORY.md, aea/__version__.py, deploy-image/docker-env.sh, develop-image/docker-env.sh, docs/logging.md, docs/thermometer-skills-step-by-step.md, docs/version.md, packages/fetchai/agents/car_data_buyer/aea-config.yaml, packages/fetchai/agents/car_detector/aea-config.yaml, packages/fetchai/agents/ml_data_provider/aea-config.yaml, packages/fetchai/agents/ml_model_trainer/aea-config.yaml, packages/fetchai/agents/my_first_aea/aea-config.yaml, packages/fetchai/agents/weather_client/aea-config.yaml, packages/fetchai/agents/weather_station/aea-config.yaml, tests/data/dummy_aea/aea-config.yaml, tests/test_docs/test_bash_yaml/md_files/bash-logging.md, tests/test_docs/test_bash_yaml/md_files/bash-thermometer-skills-step-by-step.md
This PR prepares develop for the release v0.2.2.
-
-
=> prepare develop for 0.2.2 release

aea/configurations/base.py
The method `AgentConfig.json` did not include the `contracts`.
None.
=> Add 'contracts:' section in 'aea-config.yaml'

docs/cli-how-to.md, docs/oef-ledger.md, docs/scaffolding.md, tests/test_docs/test_bash_yaml/md_files/bash-scaffolding.md
=> AEA-437 Feature/docs

aea/cli_gui/__init__.py, scripts/oef/launch.py
This PR is an attempt to solve issues of the CLI GUI.
Fixes #816
=> Solve issues with the CLI GUI

aea/protocols/generator.py, tests/data/generator/test_protocol/message.py, tests/data/generator/test_protocol/serialization.py, tests/data/generator/test_protocol/test_protocol.proto, tests/data/generator/test_protocol/test_protocol_pb2.py, tests/data/sample_specification.yaml, tests/test_protocols/test_generator.py
This PR fixes the following outstanding bugs:
- repeat usage of key value dictionary and the associated mypy complain
- custom types "CustomXXX" not correctly declared
- Better, more informative, and more consistent error messages. 
=> AEA-428 Generator bug fixes

docs/skill-guide.md, packages/fetchai/agents/simple_service_registration/aea-config.yaml, packages/fetchai/skills/simple_service_registration/behaviours.py, tests/test_docs/test_bash_yaml/md_files/bash-skill-guide.md, tests/test_docs/test_skill_guide/test_skill_guide.py
This PR fixes the skill guide
-
-
=> Fixing skill-guide

aea/cli/launch.py
Due to #877, we moved 'aea launch' to use the 'subprocess' module
instead of 'multiprocessing'.
Fixes #877
=> Make 'aea launch' to use subprocess instead of multiprocessing.

HISTORY.md, docs/questions-and-answers.md
Adds explanation to docs how to use URI based routing of envelopes.
-
-
=> minor doc update re uri based envelope routing

aea/configurations/schemas/definitions.json
`fingerprint` was defined twice.
=> Minor fix to 'schema/definitions.json'

tests/test_packages/test_skills/test_tac.py, tests/test_packages/tools_for_testing.py
End-to-end tests for missing skills packages added
#685 
=> End-to-end tests for Tac skills implemented. AEA-359

docs/api/aea.md, docs/api/agent.md, docs/api/connections/base.md, docs/api/connections/stub/connection.md, docs/api/context/base.md, docs/api/crypto/ethereum.md, docs/api/crypto/fetchai.md, docs/api/crypto/ledger_apis.md, docs/api/crypto/wallet.md, docs/api/crytpo/base.md, docs/api/helpers/dialogue/base.md, docs/api/helpers/search/generic.md, docs/api/helpers/search/models.md, docs/api/identity/base.md, docs/api/mail/base.md, docs/api/protocols/base.md, docs/api/protocols/default/message.md, docs/api/protocols/default/serialization.md, docs/api/registries/base.md, docs/api/skills/base.md, docs/api/skills/behaviours.md, docs/api/skills/error/handlers.md, docs/api/skills/tasks.md, mkdocs.yml, scripts/generate_api_docs.py
This PR adds preliminary API docs.
-
-
=> adds api docs

aea/configurations/base.py, docs/api/aea.md, docs/api/agent.md, docs/api/configurations/base.md, docs/api/configurations/loader.md, docs/api/connections/base.md, docs/api/connections/stub/connection.md, docs/api/context/base.md, docs/api/crypto/ethereum.md, docs/api/crypto/fetchai.md, docs/api/crypto/ledger_apis.md, docs/api/crypto/wallet.md, docs/api/crytpo/base.md, docs/api/helpers/dialogue/base.md, docs/api/helpers/search/generic.md, docs/api/helpers/search/models.md, docs/api/identity/base.md, docs/api/mail/base.md, docs/api/protocols/base.md, docs/api/protocols/default/message.md, docs/api/registries/base.md, docs/api/skills/base.md, docs/api/skills/behaviours.md, docs/api/skills/error/handlers.md, docs/api/skills/tasks.md, mkdocs.yml, scripts/generate_api_docs.py
=> small fix to docs

aea/protocols/generator.py, tests/data/generator/t_protocol/__init__.py, tests/data/generator/t_protocol/message.py, tests/data/generator/t_protocol/serialization.py, tests/data/generator/t_protocol/t_protocol.proto, tests/data/generator/t_protocol/t_protocol_pb2.py, tests/data/sample_specification.yaml, tests/test_cli/test_generate/test_protocols.py, tests/test_protocols/test_generator.py
WIP Added a test that compares the test protocol package with the output of the latest generator.
Various bug fixes.
This is a WIP PR. There is a broken test in the test_geenrate.py file, which is worked on.
=> Compare test protocol package with latest generator

packages/fetchai/skills/thermometer/dialogues.py, packages/fetchai/skills/thermometer/handlers.py, packages/fetchai/skills/thermometer/strategy.py
After the latest update the fipa message doesn't accept `int` values. Updated the converts the thermometer value to str.
-
=> Fix inform msg after the latest update

aea/protocols/generator.py, tests/data/generator/t_protocol/custom_types.py, tests/data/generator/t_protocol/serialization.py
Updating the generator to address discrepancies with generated protocol packages. 
New format for encoding of custom types and updated serialisation.py with the new method call.
Updated test protocol package with the latest generator output. 
=> Updating generator with latest protocol packages

aea/aea.py, aea/agent.py, aea/configurations/base.py, aea/connections/base.py, aea/helpers/search/models.py, aea/identity/base.py, docs/api/aea.md, docs/api/agent.md, docs/api/configurations/base.md, docs/api/connections/base.md, docs/api/helpers/search/models.md, docs/api/identity/base.md, docs/build-aea-step-by-step.md, docs/identity.md, docs/protocol.md, docs/skill.md, scripts/generate_api_docs.py
This PR addresses several comments raised by @cyenyxe 
-
-
=> update docs based on Cristina's PR review

README.md
Add a BibTex entry to `README.md`.
N/A
N/A
=> AEA-461Make the repository citable.

aea/cli/init.py, aea/cli/register.py, aea/cli/registry/registration.py, aea/cli/registry/utils.py, tests/test_cli/test_registry/test_registration.py
Registration success handling fixed + tests updated and minor fixes.
#1003 
=> Bugfix/registration success handling AEA-464 

packages/fetchai/skills/thermometer/handlers.py, tests/test_docs/test_step_by_step_guide/__init__.py, tests/test_docs/test_step_by_step_guide/test_step_by_step_guide.py
Tests that the code blocks in the `thermometer-skills-step-by-step.md` is identical with the code inside of thermometer-skills
#1013 
=> Adds test for the step by step guide

aea/protocols/generator.py, examples/protocol_specification_ex/default.yaml, examples/protocol_specification_ex/fipa.yaml, examples/protocol_specification_ex/gym.yaml, examples/protocol_specification_ex/http.yaml, examples/protocol_specification_ex/ml_trade.yaml, examples/protocol_specification_ex/oef_search.yaml, examples/protocol_specification_ex/sample.yaml, examples/protocol_specification_ex/tac.yaml, tests/data/generator/t_protocol/custom_types.py, tests/data/generator/t_protocol/message.py, tests/data/generator/t_protocol/serialization.py, tests/data/generator/t_protocol/t_protocol.proto, tests/data/generator/t_protocol/t_protocol_pb2.py, tests/test_cli/test_generate/test_protocols.py
- Changed encode and decode methods from class methods to static methods
- Added "_performative" to the end of performative names in protocol buffer schema file
- Added 'test_configuration_file_not_valid' to the generator cli tests 
- Addressed optional content erroneous is_set assertion
=> Generator enhancements and bug fixes

aea/cli/common.py, aea/cli/init.py
Fixes init to avoid forbidden author names
- https://github.com/fetchai/agents-aea/issues/961
-
=> init update to verify author

aea/cli/publish.py, aea/cli/push.py, tests/test_cli/test_publish.py, tests/test_cli/test_push.py
CLI push and publish commands switched to --local flag.
#1002 
=> CLI push and publish commands switched to --local flag AEA-465

aea/cli/registry/settings.py
REGISTRY_API_URL switched from localhost to dev server.
=> REGISTRY_API_URL switched from localhost to dev server.

aea/cli/common.py, aea/cli/init.py, aea/cli/register.py
Validating username as author name before registration implemented.
=> Validating username as author name before registration implemented.

aea/configurations/components.py, aea/helpers/base.py
Restore loading of __init__ modules of a package before loading component modules.
N/A
=> Restore loading of __init__ modules.

tests/test_cli/test_add/test_connection.py, tests/test_cli/test_add/test_contract.py, tests/test_cli/test_add/test_protocol.py, tests/test_cli/test_add/test_skill.py, tests/test_cli/test_registry/test_fetch.py
Tests for add and fetch fixed due to the code changes.
=> Tests for add and fetch fixed due to the code changes.

aea/cli/registry/push.py
Pushing an item with deps fixed - request data updated.
=> Pushing an item with deps fixed - request data updated.

aea/cli/registry/fetch.py, docs/api/configurations/base.md, docs/api/configurations/components.md, docs/api/connections/base.md, docs/api/connections/stub/connection.md, docs/api/contracts/base.md, docs/api/contracts/ethereum.md, docs/api/crypto/base.md, docs/api/crypto/ethereum.md, docs/api/crypto/fetchai.md, docs/api/crypto/ledger_apis.md, docs/api/helpers/search/generic.md, docs/api/helpers/search/models.md, docs/api/protocols/base.md, docs/api/protocols/default/custom_types.md, docs/api/skills/base.md, tests/test_cli/test_registry/test_fetch.py
Previously fetch used the response from the registry to determine the dependencies of an agent. That should not be the case as it can lead to problems when the registry is wrong. The agent config file is the source of truth to be used.
-
-
=> minor fix to fetch

aea/cli/registry/settings.py, docs/questions-and-answers.md
=> minor fix to docs

MANIFEST.in
=> update manifest file to include .proto files in distribution

.github/workflows/workflow.yml, aea/cli/search.py, aea/crypto/ledger_apis.py, tests/test_cli/test_launch.py, tests/test_cli/test_search.py, tests/test_packages/test_skills/test_gym.py, tests/test_packages/test_skills/test_ml_skills.py, tox.ini
Reintroduces `macos` builds.
Multiple other minor fixes.
- #1065
-
=> reintroduces macos build

deploy-image/.aea/cli_config.yaml, deploy-image/Dockerfile, deploy-image/README.md, deploy-image/entrypoint.sh, develop-image/Dockerfile
The Docker images `develop` and `deploy` were a bit outdated.
Fixes #1056 
=> AEA-517 Update Docker images

tests/test_packages/test_connections/test_http_server/test_http_server.py
This PR is wip to resolve the macos build issues.
-
=> [WIP] attempt to fix broken test for macos

scripts/generate_ipfs_hashes.py
This is the continuation of #1073 
This PR adds the '--check' option to `scripts/generate_ipfs_hashes.py`. When this option is provided,
the script will not modify the existing hashes. If a mismatch is found, the script will print an error message and continues. If at least one mismatch is found, the script will return `1` (failure), and in case of success `0`.
N/A
=> Add '--check' option to 'scripts/generate_ipfs_hashes.py'

aea/cli/launch.py, docs/cli-commands.md, docs/tac-skills.md, tests/test_cli/test_launch.py, tests/test_cli/test_misc.py
This PR adds the '--multithreaded' option in 'aea launch'.
Fix #991 
The command is not very reliable when an error occurs in one of the agent.
=> AEA-501 Add '--multithreaded' option in 'aea launch'.

aea/aea_builder.py, aea/cli/add.py, aea/cli/common.py, aea/cli/list.py, aea/configurations/base.py, aea/configurations/loader.py, docs/api/configurations/base.md, docs/api/configurations/loader.md, scripts/generate_ipfs_hashes.py
This PR renames `ConfigurationType` with `PackageType`. 
Fixes #934 
=> AEA-499 rename 'ConfigurationType with 'PackageType'

aea/aea.py, aea/agent.py, tests/common/utils.py, tests/test_aea.py, tests/test_aeabuilder.py
depends on https://github.com/fetchai/agents-aea/pull/1085
small iprovements to run tests/test_aea.py faster
on my laptop speedup is about 20X
0.7 seconds  agains 17 seconds
just an experimental tests update to learn more about agent, connections, messages workflow
=> [WIP] AEA-531 Improvement/small refactoring to optimize tests

aea/cli/add.py, tests/test_cli/test_add/test_skill.py
Adding skill contracts dependencies implemented + tests.
#1045 
=> Adding skill contracts dependencies implemented + tests. AEA-518

aea/aea_builder.py, aea/cli/common.py, aea/cli/run.py, aea/exceptions.py
This PR improves error messages when the loading of an AEA component fails.
Fixes #890 and #1062 
=> AEA-503 Improve error messages on failed skill loading.

README.md, setup.py
This PR fixes some issues on the README:
- replace relative links with absolute links
- when releasing and uploading the package on PyPI, pick only some sections of the README to make it less verbose.
Fixes #1122
=> AEA-546 Update README and upload on PyPI only a part of it.

aea/helpers/search/models.py
Implement `aea.helpers.search.models.ConstraintType.is_valid`
Fixes #1113
=> AEA-547 implement aea.helpers.search.models.ConstraintType.is_valid

aea/cli/fingerprint.py, aea/cli/scaffold.py
This PR introduces the missing fingerprinting and scaffolding for the contract package to the CLI.
Fixes #1129
-
=> add fingerprinting and scaffolding for contract

tests/test_packages/test_skills/test_erc1155.py, tests/test_packages/test_skills/test_generic_aea.py, tests/test_packages/test_skills/test_gym.py, tests/test_packages/test_skills/test_ml_skills.py, tests/test_packages/test_skills/test_thermometer.py
Skills end-to-end tests refactored with test_tools
Fixes #1005
=> Feature/skills tests refactoring AEA-487

tests/common/mocks.py, tests/test_cli_gui/test_misc.py, tests/test_cli_gui/test_run_oef.py
mock fixes.
fix to pass ci tests on macos
=> mocks fixes to pass ci tests on macos

docs/aries-cloud-agent-demo.md
Small section on how to extend the Aries demo documentation page.
=> AEA-560 Future work section in Aries demo docs

aea/agent.py, aea/cli/run.py, aea/test_tools/test_cases.py, docs/quickstart.md, tests/test_docs/test_bash_yaml/md_files/bash-quickstart.md, tests/test_docs/test_orm_integration/test_orm_integration.py, tests/test_packages/test_skills/test_carpark.py, tests/test_packages/test_skills/test_echo.py, tests/test_packages/test_skills/test_erc1155.py, tests/test_packages/test_skills/test_generic_aea.py, tests/test_packages/test_skills/test_gym.py, tests/test_packages/test_skills/test_ml_skills.py, tests/test_packages/test_skills/test_thermometer.py, tests/test_packages/test_skills/test_weather.py, tests/test_packages/test_skills/test_weather_ledger.py
Check agent process output implemented and applied in echo test + some minor changes.
#1005 
=> Check agent process output implemented AEA-488

aea/aea_builder.py, aea/skills/base.py, benchmark/cases/react_multi_agents_fake_connection.py, benchmark/cases/react_speed.py, benchmark/cases/react_speed_in_loop.py, benchmark/cases/react_speed_multi_agents.py, benchmark/framework/aea_test_wrapper.py, docs/build-aea-programmatically.md, tests/test_docs/test_build_aea_programmatically/programmatic_aea.py, tests/test_docs/test_build_aea_programmatically/test_programmatic_aea.py
Better example to create AEA programmatically. AEABuilder.add_component_instance
- #1106
=> [AEA-563, AEA-569] better programmaticaly example. some updates on builder

.github/workflows/workflow.yml, Makefile, README.md, examples/__init__.py, examples/gym_ex/rl/agent.py, tox.ini
This PR aligns our test setup.
#1164
-
=> AEA-570 fix and align tests setup

aea/cli/common.py, aea/cli/fetch.py, aea/cli/scaffold.py, tests/test_cli/test_fetch.py, tests/test_cli/test_logout.py, tests/test_cli/test_publish.py, tests/test_cli/test_push.py, tests/test_cli/test_register.py, tests/test_cli/test_registry/test_fetch.py, tests/test_cli/test_registry/test_publish.py, tests/test_cli/test_registry/test_push.py, tests/test_cli/test_registry/test_utils.py, tests/test_cli/test_run.py, tests/test_cli/tools_for_testing.py
=> CLI coverage increase incl. fixes AEA-492

aea/agent.py, aea/skills/base.py, docs/core-components.md, docs/diagram.md, docs/protocol.md, docs/quickstart.md, docs/skill.md, tests/test_docs/test_docs_skill.py, tests/test_skills/test_base.py
This PR updates a few sections of the docs in line with user requests. It also fixes a few programmatic instantiation issues with skill components.
It fixes #1071, #1015, #955 
-
=> AEA-572 AEA-519 Feature/docs

aea/cli/registry/utils.py, tests/test_cli/test_registry/test_utils.py, tests/test_packages/test_skills/test_erc1155.py
Hotfix: Registry add item to correct dest path.
=> Hotfix: Registry add item to correct dest path.

docs/protocol-generator.md, tests/test_docs/test_bash_yaml/md_files/bash-protocol-generator.md
Added docs section on generating dialogues.
=> Docs update for generating dialogues

aea/cli/create.py, aea/cli/fetch.py, aea/cli/generate.py, aea/cli/registry/fetch.py, aea/cli/scaffold.py, tests/test_cli/test_fetch.py, tests/test_cli/test_registry/test_fetch.py
Cleanup after CLI create, fetch, generate and scaffold commands implemented
#930 
=> Cleanup after CLI create, fetch, generate and scaffold commands implemented AEA-491

tests/test_cli/test_init.py
=> cli.init tests added

aea/cli/core.py, aea/cli/launch.py, aea/helpers/win32.py, tests/common/pexpect_popen.py, tests/test_cli/test_gui.py, tests/test_cli/test_launch.py, tests/test_examples/test_gym_ex.py
fix pexpect  to work on windows
=> switch to pexpect popen to work on windows. + small ctrl+c fix for windows

Makefile, aea/cli/core.py, aea/crypto/base.py, aea/crypto/cosmos.py, aea/crypto/ethereum.py, aea/crypto/fetchai.py, aea/crypto/ledger_apis.py, docs/ledger-integration.md, pytest.ini, tests/conftest.py, tests/test_cli/test_core.py, tests/test_crypto/test_cosmos_crypto.py, tests/test_crypto/test_ethereum_crypto.py, tests/test_crypto/test_fetchai_crypto.py, tests/test_crypto/test_ledger_apis.py, tests/test_crypto/test_wallet.py, tests/test_decision_maker/test_base.py, tests/test_packages/test_connections/test_oef/test_communication.py, tests/test_packages/test_skills/test_erc1155.py, tests/test_packages/test_skills/test_tac.py
This PR adds the ledger api for cosmos interaction. It does so in an adhoc fashion. The interface is maintained but the internals are hacky. Since this is for the testnet only we can start using it and improve it.
This PR increases test coverage of crypto module.
Useful resources:
- https://cosmos.network/rpc/v0.38.3
-
-
=> AEA-583 Add part of ledger api cosmos

aea/cli/common.py, tests/test_cli/test_common.py, tests/test_cli/test_core.py, tests/test_cli/test_create.py, tests/test_cli/test_fingerprint.py, tests/test_cli/test_generate/test_generate.py, tests/test_cli/tools_for_testing.py
=> Tests/cli coverage AEA-492

aea/aea.py, aea/agent_loop.py, aea/helpers/exception_policy.py, aea/helpers/exec_timeout.py, tests/test_aea_exception_policy.py, tests/test_agent_loop.py, tests/test_helpers/test_exec_timeout.py
Better exception handling/logging and AEA exception handle policy: log, stop, propagate.
=> AEA-587 AEA-588 Feature/aea skill exception handling

aea/aea.py, aea/aea_builder.py, aea/agent.py, tests/test_configurations/test_aea_config.py
loop_mode variable for AEA
now loop_mode will be specified on Agent construction not as Agent.start option.
=> [WIP] loop_mode variable for AEA

docs/protocol.md
This PR updates the docs on the protocol.
=> Docs update

tests/conftest.py, tests/test_aea_builder.py, tests/test_cli/test_create.py, tests/test_cli_gui/test_run_agent.py, tests/test_docs/test_build_aea_programmatically/test_programmatic_aea.py, tests/test_docs/test_multiplexer_standalone/test_multiplexer_standalone.py, tests/test_packages/test_connections/test_p2p_libp2p/test_communication.py, tests/test_packages/test_skills/test_echo.py, tests/test_packages/test_skills/test_gym.py, tests/test_packages/test_skills/test_http_echo.py
=> skip test on windows decorator improved

aea/cli/add.py, aea/cli/utils/config.py
This PR fixes the add command which was broken in the last PR.
-
-
=> fix add command

aea/cli/create.py, scripts/check_package_versions_in_docs.py, scripts/deploy_to_registry.py
This script is for internal usage to deploy packages to registry after making a release.
-
-
=> adds deployment script for package to registry deployment

aea/aea_builder.py, aea/components/__init__.py, aea/components/loader.py, aea/configurations/components.py
This PR aims to simplify the code in the `aea/aea_builder.py` module regarding the loading of the AEA components.
Fixes #1190 
n/a
=> Refactor `aea/aea_builder.py` code re. component loading

aea/agent.py, aea/cli/run.py, aea/test_tools/test_cases.py, docs/config.md
This PR fixes two issues:
- loop_mode was not displayed correctly on `aea run` and wrongly defined in docs
- test case did not work for aea projects as `packages` was a requirement when it is not
-
-
=> fix loop mode display and docs, fix test tool

aea/cli/config.py, aea/cli/push.py, aea/cli/registry/push.py, aea/cli/utils/click_utils.py, aea/cli/utils/config.py, aea/cli/utils/constants.py, aea/cli/utils/generic.py, aea/cli/utils/package_utils.py, aea/test_tools/generic.py, tests/test_cli/test_config.py, tests/test_cli/test_utils.py
CLI config command refactored.
#997 
=> Feature/cli config refactoring AEA-490

aea/registries/resources.py
Use `AgentComponentRegistry` for skills as well.
Preliminary work for #1290 and #1291
=> Register skills to `AgentComponentRegistry`

aea/registries/resources.py, tests/test_aea.py, tests/test_registries.py, tests/test_skills/test_base.py, tests/test_skills/test_error.py
Remove `directory` argument from 'Resources'
Preliminary work for #1290 and #1291 
=> Remove 'directory' argument from 'Resources'

aea/configurations/base.py, aea/configurations/schemas/aea-config_schema.json, tests/data/aea-config.example_w_keys.yaml, tests/test_configurations/test_aea_config.py
This PR aims to add an optional `connection_private_key_paths` field in `aea-config.yaml`. 
Preliminary work for #1191 
=> Connection private keys in agent configuration

aea/crypto/wallet.py
Introduce the split of private keys between "main" (the usual ones) and "connection", associated to `private_key_paths` and `connection_private_key_paths`, respectively.
Addresses #1191, though it is still missing the exposition of such keys during the connection initialization
n/a
=> Wallet split between 'main' private keys and the ones used by the connections.

aea/configurations/base.py
This PR makes `connection_private_key_paths` optional.
n/a
=> Make 'connection_private_key' optional

aea/cli/list.py, aea/cli/utils/constants.py, tests/test_cli/test_list.py
List all command implemented
#1212 
=> List all command implemented AEA-621

aea/cli/add.py, aea/cli/login.py, aea/cli/logout.py, aea/cli/registry/add.py, aea/cli/registry/login.py, aea/cli/registry/logout.py, aea/cli/registry/utils.py, tests/test_cli/test_registry/test_add.py, tests/test_cli/test_registry/test_login.py, tests/test_cli/test_registry/test_logout.py, tests/test_cli/test_registry/test_utils.py
Registry utils specific methods moved to a separate modules
=> Registry utils specific methods moved to a separate modules

aea/helpers/base.py, aea/protocols/base.py, tests/test_packages/test_protocols/test_tac.py
make proper use of importlib and module specs before executing the module.
n/a
=> Fix AEA package loading

docs/core-components-1.md, docs/core-components-2.md, docs/language-agnostic-definition.md, docs/oef-ledger.md, docs/orm-integration.md
This PR makes updates to docs by continuing the work in this PR #1307.
=> Continuing PR #1307

aea/crypto/cosmos.py
This PR updates the cosmos faucet endpoint.
-
=> AEA-611 Change cosmos faucet endpoint

aea/agent.py
=> unused code removed

docs/upgrading.md, mkdocs.yml
This PR addresses two minor doc issues
-
-
=> small doc fixes

setup.py, tests/test_cli/test_run.py, tests/test_packages/test_connections/test_p2p_libp2p/test_aea_cli.py, tests/test_packages/test_connections/test_p2p_libp2p/test_communication.py, tests/test_packages/test_connections/test_p2p_libp2p_client/test_aea_cli.py, tests/test_packages/test_connections/test_p2p_libp2p_client/test_communication.py
=> Quickfix libp2p mark tests as flaky

aea/connections/base.py, aea/contracts/base.py, aea/helpers/base.py, aea/skills/base.py
In #1333, a new approach to loading was introduced, but only for protocol. Extend it to connections, contracts and skills.
n/a
=> Update component package module loading

aea/cli_gui/__init__.py, tests/test_cli_gui/test_add.py
GUI add functionality switched to programmatic usage AEA-630
#1057 
=> GUI add functionality switched to programmatic usage AEA-630

aea/aea.py, aea/aea_builder.py, aea/agent.py, aea/configurations/base.py, aea/context/base.py, aea/multiplexer.py, aea/registries/resources.py, aea/runtime.py, docs/cli-vs-programmatic-aeas.md, tests/test_aea.py, tests/test_docs/test_cli_vs_programmatic_aeas/programmatic_aea.py, tests/test_skills/test_base.py, tests/test_skills/test_behaviours.py, tests/test_skills/test_error.py
Introduce the connection registry, so we treat the connection as any other component.
=> Connection registry

aea/cli_gui/__init__.py, aea/cli_gui/static/css/home.css, aea/cli_gui/templates/home.html, aea/cli_gui/templates/home.js
- displaying agent run log in GUI fixed.
- contracts added to GUI
- GUI search results styling fixed
=> Known GUI issues fixed.

docs/thermometer-skills-step-by-step.md, tests/test_docs/test_bash_yaml/md_files/bash-thermometer-skills-step-by-step.md
Small update to thermometer guide to fix some user issues
-
-
=> add more guidance in thermometer step by step guide

aea/cli/launch.py, aea/helpers/exec_timeout.py, aea/helpers/multiple_executor.py, aea/launcher.py, aea/runner.py, tests/test_runner.py
`cli launch` now uses AEARunner and AEALauncher
=> `cli launch` now uses AEARunner and AEALauncher!

aea/cli/interact.py, aea/cli/scaffold.py, aea/test_tools/test_cases.py, tests/test_cli/test_interact.py, tests/test_cli/test_scaffold/test_generic.py
Test coverage gaps for interact and scaffold filled
=> Test coverage gaps for interact and scaffold filled AEA-629

aea/skills/base.py
Raise an `AEAException` at build time if, when loading a skill, there is more than one model with the same name.
Fixes #993 
n/a
=> raise error at build time if more than one model with the same name

aea/aea_builder.py
Fix a problem introduced in #1423 due to mismatch between component id and public ids.
n/a
n/a
=> fix pr #1423

aea/cli_gui/__init__.py, aea/cli_gui/__main__.py, aea/cli_gui/utils.py, tests/test_cli_gui/test_delete.py, tests/test_cli_gui/test_get_items.py, tests/test_cli_gui/test_run_agent.py, tests/test_cli_gui/test_search.py, tests/test_cli_gui/test_utils.py
GUI test coverage 100%
Incl. init module splitting.
#1400
=> Feature/gui test coverage AEA-692

aea/cli_gui/__init__.py
Wrong working dir setting for GUI local search fixed. #1400 
=> Wrong working dir setting for GUI local search fixed.

aea/aea_builder.py, aea/helpers/base.py, tests/conftest.py, tests/test_crypto/test_cosmos.py, tests/test_crypto/test_ethereum.py, tests/test_crypto/test_fetchai.py, tests/test_packages/test_connections/test_ledger/test_contract_api.py, tests/test_packages/test_connections/test_ledger/test_ledger_api.py, tests/test_packages/test_contracts/test_erc1155/test_contract.py
With this PR we skip registration of contract if a contract with the same public key is already registered.
n/a
n/a
=> Skip registration of contract if already present

scripts/generate_ipfs_hashes.py
=> Fix hashes computation for ERC1155 contract.

aea/test_tools/test_cases.py
`packages_registry_src` was set to `None` instead of the default value `Path()`.
n/a
n/a
=> Fix BaseAEATestCase.teardown

setup.py
Fixes requests version in `setup.py` to avoid clashes on install.
-
-
=> fix requests version to avoid clashes

aea/components/base.py, aea/components/loader.py, tests/test_components/__init__.py, tests/test_components/test_base.py, tests/test_components/test_loader.py
Add tests for `aea/components/loader.py`
partially fixes #1467
=> Add tests for aea/components/*.py coverage

aea/mail/base.py, tests/test_mail/test_base.py
Increase coverage on aea/mail/*
- fix minor bug in `ProtobufEnvelopeSerializer.encode`
- test `Envelope.message_bytes` and `Envelope.skill_id`
n/a
n/a
=> AEA-715: Increase coverage on aea/mail/*

aea/skills/base.py, tests/test_skills/test_base.py
Add a default logger in SkillContext
n/a
n/a
=> Make default logger in SkillContext

MANIFEST.in
Include more files to build/source distribution.
n/a
=> fix MANIFEST file for 'aea gui' issue

tests/conftest.py, tests/test_examples/test_gym_ex.py, tests/test_mail/test_base.py
This PR tries to fix the Gym example test by updating the PYTHONPATH variable correctly.
n/a
=> Fix PYTHONPATH in Gym example test

aea/helpers/dialogue/base.py, tests/test_helpers/test_dialogue/test_base.py
This PR adds tests for the dialogue API.
=> AEA-702 Tests for Dialogue API

aea/cli/registry/publish.py, aea/cli/registry/push.py, aea/cli/registry/utils.py, aea/cli/utils/generic.py, aea/configurations/base.py, tests/test_cli/test_registry/test_publish.py, tests/test_cli/test_registry/test_push.py, tests/test_cli/test_registry/test_utils.py
Upload readme with packages implemented + tests
#1125 
=> Upload readme with packages implemented + tests AEA-675

aea/aea.py, aea/aea_builder.py, aea/agent_loop.py, aea/launcher.py, aea/multiplexer.py, aea/runner.py, aea/runtime.py, tests/test_aea.py, tests/test_aea_builder.py, tests/test_agent.py, tests/test_launcher.py, tests/test_multiplexer.py
improved test coverage for framework core
=> [AEA-712] Framework core better test coverage

aea/registries/resources.py, tests/test_registries/test_base.py
Add tests for aea.registries
n/a
=> AEA-741 Add tests for aea.registries

aea/helpers/async_friendly_queue.py, aea/helpers/async_utils.py, aea/helpers/base.py, aea/helpers/exec_timeout.py, aea/helpers/file_lock.py, aea/helpers/multiple_executor.py, aea/helpers/search/models.py, tests/data/dot_env_file, tests/test_agent_loop.py, tests/test_helpers/test_async_utils.py, tests/test_helpers/test_base.py, tests/test_helpers/test_multiple_executor.py, tests/test_helpers/test_search/test_generic.py, tests/test_helpers/test_search/test_models.py
better test coverage for aea.helpers
=> [AEA-711] aea.helpers increased test coverage

aea/registries/base.py, aea/registries/filter.py, tests/test_registries/test_base.py, tests/test_registries/test_filter.py
Add more tests for `aea.registries.*`
n/a
=> Add more tests for aea.registries.*

aea/helpers/dialogue/base.py, tests/test_helpers/test_dialogue/test_base.py
This PR increases test coverage for dialogue API.
=> Increasing test coverage for dialogue API

tests/test_cli/test_utils/test_utils.py
Missing test for generic utils method added.
=> Missing test for generic utils method added.

Makefile, examples/gym_ex/gyms/env.py, examples/gym_ex/proxy/agent.py, examples/gym_ex/proxy/env.py, examples/gym_ex/rl/agent.py, tox.ini
fix for pylint checks over examples
https://github.com/fetchai/agents-aea/issues/1483
=> [AEA-741] pylint examples check fix

tests/test_aea.py, tests/test_packages/test_connections/test_oef/test_communication.py, tests/test_packages/test_connections/test_tcp/test_base.py, tests/test_packages/test_connections/test_tcp/test_communication.py
Update log capture in some tests on TCP and OEF connections.
n/a
n/a
=> Update log capture in some tests

docs/cli-how-to.md, tests/test_docs/test_bash_yaml/md_files/bash-cli-how-to.md
The CLI tool can also be executed with:
python -m aea.cli
Describe such approach in the 'cli-how-to.md' docs file.
Fixes #1236 
n/a
=> Describe module execution (python -m) for the CLI tool

aea/agent_loop.py, aea/registries/filter.py, aea/skills/base.py, tests/test_registries/test_filter.py, tests/test_skills/test_base.py
Add new handlers queue, analogous to #677 .
Fixes #1383 
=> AEA-771 Add new handlers queue

aea/cli/generate_wealth.py, aea/cli/get_wealth.py, aea/cli/utils/package_utils.py, aea/crypto/__init__.py, aea/crypto/base.py, aea/crypto/cosmos.py, aea/crypto/ethereum.py, aea/crypto/fetchai.py, aea/crypto/helpers.py, aea/crypto/ledger_apis.py, aea/crypto/registries/__init__.py, aea/crypto/registries/base.py, tests/test_cli/test_generate_wealth.py, tests/test_crypto/test_ledger_apis.py
Ledger apis are made compatible with cli and vice versa.
Faucet registry added.
#1536, #1393
-
=> AEA-775 refactor ledger apis to improve how it works with registires

tests/test_cli/test_run.py
fix for aea.run multiple connection test
test fail cause fixed timeout
=> fix for aea.run multiple connection test

tests/test_packages/test_skills/test_ml_skills.py, tox.ini
Remove Tensorflow from test dependencies. Related to https://github.com/tensorflow/tensorflow/issues/27794
Since it was only used in the ML skill test, and that the Tensorflow installation is very flaky on CI, I propose to switch it off temporarily.
n/a
n/a
=> Remove Tensorflow from test dependencies.

.github/workflows/workflow.yml
Update GH Actions CI workflos
Partially addresses #1239 
n/a
=> update GH Actions CI Workflow

docs/skill.md, tests/test_docs/test_docs_skill.py
Add docs on 'new_handlers' queue.
Improves #1556 
n/a
=> Add docs on 'new_handlers' queue

aea/aea.py, aea/agent.py, aea/helpers/async_utils.py, aea/helpers/exec_timeout.py, aea/launcher.py, aea/runtime.py, docs/api/agent.md, tests/common/utils.py, tests/test_aea.py, tests/test_aea_exception_policy.py, tests/test_aea_exectimeout.py, tests/test_agent.py, tests/test_launcher.py
expose runtime.state to agent. runtime state small refactor. fixes. coverage fixes
#1323
=> [AEA-767] better runtime state support on agent

scripts/generate_ipfs_hashes.py, tox.ini
This PR tags the version of IPFS in tox.ini to the same version used in Pipfile. It also removes skipping checks for some files.
-
-
=> attempt to fix ipfs hashing inconsistencies

aea/aea_builder.py, aea/cli/generate_wealth.py, aea/cli/get_address.py, aea/cli/get_wealth.py, aea/cli/utils/package_utils.py, aea/crypto/helpers.py, tests/test_cli/test_generate_wealth.py, tests/test_cli/test_get_address.py, tests/test_cli/test_get_wealth.py, tests/test_crypto/test_helpers.py, tests/test_packages/test_connections/test_p2p_libp2p/test_public_dht.py
Aims to address a circularity in crypto methods
-
-
=> address circularity causing import issues on windows

tests/test_cli/test_add/test_connection.py, tests/test_cli/test_add/test_contract.py, tests/test_cli/test_add/test_protocol.py, tests/test_cli/test_add/test_skill.py, tests/test_cli/test_fetch.py, tests/test_docs/test_orm_integration/test_orm_integration.py, tests/test_docs/test_skill_guide/test_skill_guide.py, tests/test_examples/test_http_client_connection_to_aries_cloud_agent.py, tests/test_multiplexer.py, tests/test_packages/test_connections/test_p2p_libp2p/test_public_dht.py, tests/test_packages/test_skills/test_carpark.py, tests/test_packages/test_skills/test_erc1155.py, tests/test_packages/test_skills/test_generic.py, tests/test_packages/test_skills/test_ml_skills.py, tests/test_packages/test_skills/test_thermometer.py, tests/test_packages/test_skills/test_weather.py
set random locations for agents in integrational tests; to avoid different runs impacting each other
-
-
=> generate random locations for integration tests

tests/test_docs/test_cli_vs_programmatic_aeas/test_cli_vs_programmatic_aea.py
Update tests on programmatic AEA usage by using random location. Continuation of #1594 .
n/a
------
n/a
=> Update programmatic AEA test with random location

tests/test_helpers/test_logging.py
Add tests for aea/helpers/logging
n/a
n/a
=> Add tests for aea/helpers/logging

tests/test_docs/test_cli_vs_programmatic_aeas/test_cli_vs_programmatic_aea.py
Fix docs test on programmatic AEA
n/a
=> Fix docs test on programmatic AEA

setup.py, tests/test_cli/test_generate_wealth.py, tests/test_configurations/test_loader.py, tests/test_docs/test_cli_vs_programmatic_aeas/test_cli_vs_programmatic_aea.py, tests/test_packages/test_connections/test_local/test_search_services.py
- update header parsing in `setup.py` after #1602 
- 100% coverage of `aea.configurations.*`
- fix test on search services
n/a
n/a
=> Fix minor test issues before the release

aea/cli/interact.py
Fixes an issue of missing sender/counterparty in aea interact
-
------
=> fix aea interact command

aea/runtime.py
Filter keyboard interrupt from runtime logging.
n/a
n/a
=> Filter keyboard interrupt from runtime logging

tests/conftest.py, tests/test_cli/test_utils/test_utils.py, tests/test_helpers/test_logging.py, tests/test_packages/test_connections/test_local/test_search_services.py
- Remove `caplog` from tests in `test_helpers/test_logging`
- use `wait_for_condition` to overcome timeout problems in a search service test.
- fix other tests that used to overwrite the cli configuration `~/.aea/cli_config.yaml`
n/a
n/a
=> Minor fixes on misc tests.

setup.py
Set `ipfshttpclient` version to 0.4.12 in setup.py
Fixes #1629 
n/a
=> AEA-807 Set ipfshttpclient version to 0.4.12 in setup.py

aea/test_tools/test_cases.py, tests/test_cli/test_interact.py
Add integration test on 'aea interact'.
Fix #1607
n/a
=> AEA-810 add integration test on 'aea interact'

aea/crypto/cosmos.py, tests/test_crypto/test_cosmos.py
Fixes CosmWasm bugs
Fixed wrong detection of CosmWasm message in is_cosmwasm_transaction
Fixed CosmWasm broadcasting - temporary file path didn't include directory
=> CosmWasm detection and broadcasting fixed

tests/test_protocols/test_state_update.py
Increase coverage for aea.protocols.*
n/a
=> Increase coverage for aea.protocols.*

README.md, docs/aea-vs-mvc.md, docs/agent-oriented-development.md, docs/app-areas.md, docs/contract.md, docs/core-components-1.md, docs/demos.md, docs/index.md, docs/language-agnostic-definition.md, docs/oef-ledger.md, docs/quickstart.md, docs/version.md, docs/vision.md, mkdocs.yml, tests/test_docs/test_bash_yaml/md_files/bash-contract.md
This PR adds miscellaneous details to the docs and a section on usage of contracts packages.
-
-
=> AEA-840, AEA-841 Feature/docs

Pipfile
flake8-eradicate had a wrong Python version specifier: '0.4.0' instead of '==0.4.0'
n/a
=> fix Pipfile

tests/test_packages/test_connections/test_http_server/test_http_server_and_client.py
test for http client and server connection to check url get query
=> http client server tet now contains test for url query

scripts/update_package_versions.py, tests/test_packages/test_skills/test_thermometer.py
Now it bumps the version only if the match corresponds to the right package type.
Three arguments added:
- `-C`, `--context`: the number of rows to print above/below the match in the interactive prompt
- `-n`, `--no-interactive`: no interactive mode; 
- `-r`, `--replace-by-default`: if `--no-interactive` is set, replace the item (by default it doesn't).
Fixes #1678 
n/a
=> update package version script

aea/crypto/cosmos.py, aea/crypto/fetchai.py, tests/test_crypto/test_fetchai.py
Added token faucet updates to `fetchai.py`.
This PR supersedes: #1683
=> Token Faucet Updates

aea/cli/generate_wealth.py, aea/crypto/cosmos.py, aea/crypto/helpers.py, tests/test_cli/test_generate_wealth.py, tests/test_crypto/test_cosmos.py, tests/test_crypto/test_fetchai.py
This PR fixes some linter issues
-
-
=> fix linters

aea/aea_builder.py, aea/cli/generate_wealth.py, aea/configurations/base.py, aea/configurations/loader.py, aea/connections/base.py, aea/contracts/base.py, aea/crypto/cosmos.py, aea/crypto/fetchai.py, aea/crypto/helpers.py, aea/protocols/base.py, aea/skills/base.py, docs/api/configurations/base.md, tests/conftest.py, tests/test_aea_builder.py, tests/test_cli/test_generate_wealth.py, tests/test_configurations/test_base.py, tests/test_contracts/test_base.py, tests/test_crypto/test_cosmos.py, tests/test_crypto/test_fetchai.py
This was due to a in-function import statement in ComponentConfiguration.load. The method has been moved into aea.configurations.loader as a function with name 'load_component_configuration'
n/a
n/a
=> Remove circularities in aea.configurations

aea/agent.py, aea/connections/base.py, aea/context/base.py, aea/multiplexer.py, aea/skills/base.py, scripts/whitelist.py, tests/test_multiplexer.py, tests/test_packages/test_connections/test_ledger/test_contract_api.py, tests/test_packages/test_connections/test_p2p_libp2p_client/test_errors.py, tests/test_skills/test_base.py
Improvement of the multiplexer status object
https://github.com/fetchai/agents-aea/issues/1689
=> AEA-851 MultiplexerStatus

aea/aea.py, aea/agent.py, aea/helpers/async_utils.py, tests/test_aea.py, tests/test_helpers/test_async_utils.py, tests/test_helpers/test_base.py
=> missed tests for coverage

setup.py
Require eth-account==0.5.2
n/a
n/a
=> Require eth-account==0.5.2

aea/cli/registry/settings.py, aea/cli/search.py, aea/cli_gui/__init__.py, tests/test_cli/test_search.py, tests/test_cli_gui/test_get_items.py
CLI Search updated to use API v1. API url updated.
#1635 
=> CLI Search updated to use API v1. API url updated AEA-850

tests/test_cli/test_interact.py
updates on cli interract test to check for the broken pipe.
=> test for interract test brokenpipe

aea/aea.py, aea/aea_builder.py, aea/configurations/base.py, aea/configurations/schemas/aea-config_schema.json, aea/configurations/schemas/definitions.json, aea/multiplexer.py, aea/runtime.py, tests/test_aea_builder.py, tests/test_configurations/test_aea_config.py, tests/test_multiplexer.py
Exception handling option for multiplexer
=> multiplexer exception handling policy (for _send only at the moment)

tests/test_packages/test_protocols/test_fipa.py
This PR adds a test that proves fipa protocol supports exchanges of counter-proposals. 
=> AEA-897 Test for Fipa supporting counter-proposals

aea/aea.py, aea/aea_builder.py, aea/multiplexer.py, aea/runtime.py, docs/api/aea.md, docs/api/multiplexer.md, docs/config.md, tests/test_configurations/test_aea_config.py, tests/test_docs/test_bash_yaml/md_files/bash-config.md, tests/test_multiplexer.py
This PR aligns the default connection exception policy with the one in the skills.
-
-
=> change default connection exception policy

aea/cli/core.py, aea/cli/reset_password.py, tests/test_cli/test_misc.py, tests/test_cli/test_registry/test_login.py, tests/test_cli/test_reset_password.py
CLI reset_password command implemented AEA-887
=> CLI reset_password command implemented AEA-887

setup.cfg
Make `isort` to skip recursive links. This will also remove warnings from `isort` output during `make lint`.
n/a
n/a
=> Make isort to skip recursive links

aea/registries/base.py, docs/simple-oef-usage.md, tests/test_packages/test_connections/test_soef/test_soef_integration.py
set declared name test for soef integration
=> set declared name test for soef integration

aea/aea.py, aea/agent.py, aea/agent_loop.py, aea/cli/launch.py, aea/helpers/async_utils.py, aea/helpers/multiple_executor.py, aea/launcher.py, aea/multiplexer.py, aea/runner.py, aea/runtime.py, tests/test_aea.py, tests/test_agent.py, tests/test_agent_loop.py, tests/test_helpers/test_async_utils.py, tests/test_launcher.py, tests/test_multiplexer.py, tests/test_runtime.py, tests/test_skills/test_error.py
async interface to run runtime/agent/multiplexer
=> [AEA-812] Runtime, Agent loop, Multiplexer async interface

aea/multiplexer.py, tests/common/pexpect_popen.py, tests/test_cli/test_launch.py, tests/test_multiplexer.py
fix issue with termination on connect_all
=> fix for cancell error supression in multiplexer._connect_all

aea/configurations/base.py, aea/configurations/loader.py, aea/helpers/base.py, aea/manager.py, tests/test_configurations/test_base.py, tests/test_manager.py
Overwrite agent configurations in Agent Manager
n/a
n/a
=> Overwrite agent configurations in Agent Manager

HISTORY.md, aea/__version__.py, benchmark/run_from_branch.sh, deploy-image/docker-env.sh, develop-image/docker-env.sh, docs/acn.md, docs/quickstart.md, docs/upgrading.md, tests/test_docs/test_bash_yaml/md_files/bash-quickstart.md
This PR preps develop for the next release.
-
-
=> prep develop for release 0.6.2

mkdocs.yml
=> fix mkdocs doc paths

aea/cli/config.py, aea/configurations/base.py, aea/configurations/schemas/aea-config_schema.json, aea/configurations/schemas/contract-config_schema.json
=> small fixes to config set get

aea/configurations/loader.py, aea/configurations/schemas/connection-config_schema.json, aea/configurations/schemas/contract-config_schema.json, aea/configurations/schemas/protocol-config_schema.json, aea/configurations/schemas/skill-config_schema.json, tests/test_cli/test_add/test_connection.py, tests/test_cli/test_add/test_protocol.py, tests/test_cli/test_add/test_skill.py, tests/test_cli/test_fetch.py, tests/test_configurations/test_loader.py
Make 'type' field required in every component configuration.
Partially addresses #1702.
n/a
=> Make 'type' field required in every component configuration.

aea/helpers/yaml_utils.py, tests/test_helpers/test_base.py, tests/test_helpers/test_yaml_utils.py
add tests to custom YAML loading and env var resolving
Addresses #1702 and extends #1802 
=> add tests to custom YAML loading and env var resolving

aea/cli/remove.py, aea/cli/upgrade.py, tests/test_cli/test_add/test_skill.py, tests/test_cli/test_remove/test_base.py, tests/test_cli/test_remove/test_dependencies.py, tests/test_cli/test_upgrade.py
cli remove command supports dependencies removal
=> AEA-976 remove command: support dependencies removal

aea/aea_builder.py, aea/cli/run.py
Restore loading of dotenv file in AEABuilder.from_aea_project
Addresses #1512 
n/a
=> Restore loading of dotenv file in AEABuilder.from_aea_project

aea/cli/core.py, aea/cli/generate_wealth.py, aea/cli/get_address.py, aea/cli/get_wealth.py, aea/cli/transfer.py, aea/cli/utils/package_utils.py, aea/crypto/cosmos.py, tests/common/utils.py, tests/test_cli/test_generate_wealth.py, tests/test_cli/test_get_address.py, tests/test_cli/test_get_wealth.py, tests/test_cli/test_misc.py, tests/test_cli/test_transfer.py, tests/test_cli/test_utils/test_utils.py
cli command to transfer funds to another account
#1558
=> AEA-965 cli transfer command

aea/aea_builder.py, aea/helpers/base.py, tests/test_aea_builder.py, tests/test_helpers/test_base.py
factor out Kahn's algorithm from aea_builder module
Addresses #1512 
=> [AEA-896] factor out Kahn's algorithm from aea_builder module

aea/cli/remove.py, aea/cli/upgrade.py, aea/cli/utils/config.py, tests/test_cli/test_remove/test_base.py, tests/test_cli/test_upgrade.py, tests/test_cli/tools_for_testing.py
cleanup component configuration sections after remove/upgrade commands
=> [AEA-976] cli remove and upgrade purge unused component configuraions

aea/aea_builder.py, aea/cli/install.py, aea/configurations/project.py, aea/helpers/install_dependency.py, aea/manager.py, tests/test_aea_builder.py, tests/test_cli/test_install.py, tests/test_configurations/test_project.py, tests/test_helpers/test_install_dependency.py, tests/test_manager.py
AEABuilder.install_pypi_dependencies
=> [AEA-967] AEABuilder.install_pypi_dependencies  Manager.install_pypi_dependencies

docs/protocol-generator.md, docs/skill-testing.md, mkdocs.yml
This PR adds documentation for skill testing tool.
=> Skill Testing Documentation

aea/configurations/base.py
This is a sub-PR of #1834 
see #1834 
=> AEA-849, AEA-778 Load PUBLIC_ID from __init__.py module of AEA Pacakge

aea/cli/create.py, aea/cli/init.py, aea/cli/register.py, tests/test_cli/test_register.py
CLI register command updated due to opt-in marketing requirements.
=> AEA-961 CLI register command updated due to opt-in marketing requirements.

docs/contract.md
Just some helping text for the contract development.
- [] Lint and unit tests pass locally with my changes
None
=> [AEA-998] Minor clarifications to help with contract interactions

aea/aea_builder.py, aea/cli/remove.py, aea/cli/upgrade.py, tests/test_aea_builder.py, tests/test_cli/test_remove/test_base.py, tests/test_cli/test_upgrade.py
proper handling upgrade and remove dependencies for non vendor packages
=> [AEA-1002] proper handling upgrade and remove dependencies for non vendor packages

aea/cli/init.py, aea/cli/register.py, tests/test_cli/test_register.py
Subscribe flag changed to no_subscribe AEA-961
=> Subscribe flag changed to no_subscribe AEA-961

scripts/install.ps1, scripts/install.sh
install scripts for mac,win, ubuntu
=> install scripts

aea/cli/upgrade.py, tests/test_cli/test_upgrade.py
Fix `TestUpgradeProject.test_upgrade` after release `0.7.0`.
n/a
n/a
=> fix TestUpgradeProject.test_upgrade

aea/cli/scaffold.py, aea/cli/upgrade.py, aea/configurations/constants.py, tests/test_cli/test_scaffold/test_skills.py, tests/test_cli/test_upgrade.py
Update `PUBLIC_ID` variable in the `__init__.py` module of scaffolded items.
Fix #1866
n/a
=> [AEA-1015] Fix/1866

docs/quickstart.md
Expand known issues section of quickstart, including links to installation instructions.
n/a
=> [AEA-1007] Expand known issues section of quickstart

aea/cli/upgrade.py, tests/common/utils.py, tests/test_cli/test_upgrade.py
Make `aea upgrade` to update references in AEA config.
Partially addresses #1853
n/a
=> [AEA-1011] Fix/1853

aea/cli/remove.py, aea/cli/upgrade.py, aea/cli/utils/config.py, tests/test_cli/test_upgrade.py
Update references of non-vendor packages.
Fix #1853
n/a
=> [AEA-1022] Update references of non-vendor packages.

aea/protocols/dialogue/base.py, tests/test_protocols/test_dialogue/test_base.py
=> dialogues memory optimization

aea/cli/remove.py, aea/cli/upgrade.py, deploy-image/Dockerfile, scripts/deploy_to_registry.py
This fixes a few issues we discovered during `0.7.1` release
-
-
=> post release fixes

tests/test_packages/test_skills/test_tac_control/test_game.py, tests/test_packages/test_skills/test_tac_control/test_parameters.py, tests/test_packages/test_skills/test_tac_control_contract/test_parameters.py
Found three more wrongly specified geo locations in tests.
-
-
=> fix remaining geo locations

aea/cli/add.py, aea/cli/fetch.py, aea/cli/publish.py, aea/cli/registry/fetch.py, aea/cli/upgrade.py, aea/cli/utils/package_utils.py, aea/configurations/constants.py, tests/test_cli/test_fetch.py, tests/test_cli/test_registry/test_fetch.py, tests/test_cli/test_utils/test_utils.py
Fix `aea fetch` command.
PR #1816 broke backward compatibility.
n/a
n/a
=> Fix fetch command

aea/cli/remove.py, aea/cli/upgrade.py, tests/test_cli/test_upgrade.py
- remove obsolete print at the end of 'aea upgrade'
- upgrade vendor deps if only referenced by non-vendor deps
n/a
n/a
=> Fix `aea upgrade`

aea/cli/remove.py, tests/test_cli/test_upgrade.py
Increase code coverage of `aea.cli.upgrade`
n/a
n/a
=> Increase code coverage of `aea.cli.upgrade`

aea/cli/add.py, aea/cli/remove.py, aea/cli/utils/click_utils.py, tests/test_cli/test_add/test_skill.py, tests/test_cli/test_fetch.py
increase code coverage for `aea add`
n/a
n/a
=> Increase code coverage for `aea add`

aea/cli/utils/package_utils.py
Fix ledger api config override
n/a
=> Fix ledger api config override

aea/cli/add.py, aea/cli/fetch.py
Make `aea add` and `aea fetch` less verbose (by default) when package not found in local registry 
Updates changes made in #1903
n/a
------
n/a
=> Make `aea add` and `aea fetch` less verbose (by default) when package not found in local registry 

docs/development-setup.md, docs/quickstart.md, mkdocs.yml
This PR adds a new section in the docs which describes how to setup for AEA development.
-
-
=> Add guide how to work with local registry

aea/components/loader.py, aea/connections/base.py, aea/registries/base.py, aea/skills/base.py, aea/skills/behaviours.py, tests/test_agent_loop.py, tests/test_exceptions.py, tests/test_skills/test_base.py, tests/test_skills/test_behaviours.py
This PR addresses bugs and coverage gaps.
-
-
=> add tests to fill coverage gaps, fix behaviours

aea/crypto/helpers.py, tests/test_packages/test_skills_integration/test_tac.py
Two minor bug fixes. Ensures we no longer auto-overwrite keys if private key file exists.
-
-
=> fix key overwrite, fix tac setup

aea/cli/registry/publish.py, tests/test_cli/test_registry/test_publish.py
Error during package publish triggers exception on tar file remove on windows platform
#1940
=> AEA-1063 win publish tar remove fix

.github/workflows/workflow.yml, tests/common/docker_image.py, tests/conftest.py, tests/test_contracts/test_base.py
- refactor OEF search docker image
- add Ganache Docker image.
n/a
n/a
=> AEA-1078 Use Ganache Docker image for testing

tests/test_cli/test_scaffold/test_connection.py
see:  https://github.com/fetchai/agents-aea/runs/1411347675?check_suite_focus=true
n/a
=> Update test on scaffold with symlink

aea/test_tools/test_cases.py, tests/conftest.py, tests/test_crypto/test_ethereum.py, tests/test_packages/test_connections/test_ledger/test_ledger_api.py, tests/test_packages/test_skills_integration/test_tac.py
fix some issues introduced by #1957 in tests.
- new Ethereum testnet configuration weren't used everywhere;
- chain ID for Ganache was wrong, changed to the default `1337`
n/a
n/a
=> fix some issues introduced by #1957

aea/cli/push.py, aea/cli/registry/push.py, tests/test_cli/test_push.py, tests/test_cli/test_registry/test_push.py, tests/test_cli/tools_for_testing.py
=> actual version check on push

scripts/check_package_dependencies.py, scripts/check_package_versions_in_docs.py, scripts/deploy_to_registry.py
=> fix some scripts

tests/conftest.py, tests/test_contracts/test_base.py, tests/test_crypto/test_ethereum.py
Mark tests that should have been marked as integration/ledger.
Continuation of #1957 and #1959 
n/a
n/a
=> Mark tests that should have been marked as integration/ledger

aea/cli/core.py, aea/cli/remove_key.py, aea/configurations/base.py, aea/test_tools/test_cases.py, docs/cli-commands.md, tests/test_cli/test_misc.py, tests/test_cli/test_remove_key.py, tests/test_configurations/test_base.py
add "remove-key" command
Fixes #remove
n/a
=> AEA-960 add "remove-key" command

scripts/generate_api_docs.py
Make the script to find all the modules dynamically.
Addresses #1854 
n/a
=> AEA-1035 Update generate api docs script

docs/erc1155-skills.md, docs/tac-skills-contract.md, tests/test_docs/test_bash_yaml/md_files/bash-erc1155-skills.md, tests/test_docs/test_bash_yaml/md_files/bash-tac-skills-contract.md
Update docs on demos and skills such that they use Ganache to set up the Ethereum testnet.
n/a
------
=> AEA-1097 update demo docs with Ganache

AUTHORS.md, README.md, SECURITY.md, aea/cli/publish.py, scripts/RELEASE_PROCESS.md
This PR updates various meta information.
-
-
=> meta data updates

docs/oracle-demo.md, mkdocs.yml
Add a demonstration of a simple oracle agent and skills.
=> AEA-1122 Oracle demo

docs/generic-storage.md
Documentation for generic storage and dialogues offloading
=> storage docs

aea/manager.py, tests/test_manager.py
MultiAgentManager add project fix
https://github.com/fetchai/agents-aea/issues/1991
=> AEA-1138 multiagenmanager: same project add error handling

aea/cli/create.py, aea/helpers/base.py, scripts/bump_aea_version.py, tests/test_cli/test_create.py, tests/test_helpers/test_base.py
Fix aea_version field on 'aea create'
n/a
n/a
=> AEA-1175 Fix aea_version field on 'aea create'

aea/aea_builder.py, aea/cli/config.py, aea/cli/utils/config.py, aea/cli/utils/constants.py, aea/cli/utils/generic.py, aea/configurations/base.py, aea/configurations/schemas/aea-config_schema.json, aea/configurations/schemas/connection-config_schema.json, aea/configurations/schemas/contract-config_schema.json, aea/configurations/schemas/definitions.json, aea/configurations/schemas/protocol-config_schema.json, aea/configurations/schemas/skill-config_schema.json, aea/configurations/validation.py, aea/helpers/base.py, aea/skills/base.py, aea/test_tools/test_cases.py, tests/test_cli/test_build.py, tests/test_cli/test_config.py, tests/test_cli/test_generate_wealth.py, tests/test_cli/test_remove_key.py, tests/test_cli/test_upgrade.py, tests/test_configurations/test_aea_config.py, tests/test_configurations/test_base.py, tests/test_configurations/test_loader.py, tests/test_test_tools/test_test_cases.py
AgentConfigManager implementation
=> AgentConfigManager implementation

docs/car-park-skills.md, docs/ml-skills.md, tests/test_docs/test_bash_yaml/md_files/bash-car-park-skills.md, tests/test_docs/test_bash_yaml/md_files/bash-ml-skills.md
Fix outdated docs.
Branched-off from #2081 
Fix #2078 
=> AEA-1180 Feature/docs - 2

.github/workflows/workflow.yml
remove 'yml' input as per https://github.com/codecov/codecov-action/issues/51
n/a
=> remove 'yml' input as per codecov/codecov-action#51

docs/diagram.md, mkdocs.yml
Improves navigation for beginners and advanced developers. Adds more content.
#1381 
=> AEA-1180 modify navigation in docs

Makefile
Fix makefile 'new_env' command.
n/a
n/a
=> Fix makefile 'new_env' command.

aea/cli/push.py, tests/test_cli/test_push.py
`aea push --local` support vendors packages
=> AEA-1190 support vendorized packages for local push

Makefile, README.md, docs/interaction-protocol.md, docs/modes.md, docs/p2p-connection.md, docs/por.md, docs/simple-oef.md, mkdocs.yml, tests/test_docs/test_bash_yaml/md_files/bash-p2p-connection.md, tests/test_docs/test_bash_yaml/md_files/bash-por.md
This PR adds docs on PoR and interaction protocols, extends contribution guide.
#2091, #2078, #1923
-
=> AEA-1198 add more contribution guides, add PoR first draft

docs/generic-storage.md, tests/test_docs/test_generic_storage.py
Update tests for 'generic-storage.md'
n/a
------
n/a
=> Update tests for 'generic-storage.md'

docs/cli-commands.md, tests/test_docs/test_cli_commands.py
add test for 'cli-commands.md'.
n/a
n/a
=> AEA-1188 add test for 'cli-commands.md'

aea/cli/scaffold.py, aea/test_tools/test_cases.py, tests/test_cli/test_install.py, tests/test_cli/test_scaffold/test_protocols.py
scaffold protocol prompt added
=> AEA-1202 scaffold protocol prompt added

.github/workflows/workflow.yml, scripts/spell-check.sh, tox.ini
Run spell checking script in CI, but only when merging into master.
n/a
n/a
=> AEA-1204 Add spell-check script in CI

.github/workflows/workflow.yml
Update condition for common-check-5 on CI to run only on merging into master. NOT TESTED.
n/a
n/a
n/a
=> AEA-1204 Update common-check-5 in CI workflow 

aea/helpers/pipe.py, tests/test_cli/test_push.py, tests/test_helpers/test_pipe/test_pipe.py, tests/test_test_tools/test_test_cases.py
Fix minor coverage gaps in `aea.helpers.pipe` and `aea.test_tools.test_cases`
n/a
n/a
=> Fix minor coverage gaps in aea.helpers.pipe and aea.test_tools.test_cases

tests/test_manager/test_manager.py
small fix for test
small fix for test
=> small async test fix

.github/workflows/workflow.yml
use Python 3.7 instead of Python 3.6 for common check 5 in workflow
n/a
n/a
=> use Python 3.7 instead of Python 3.6 for common check 5 in workflow

aea/cli/remove.py, aea/cli/upgrade.py, aea/cli/utils/context.py, aea/cli/utils/decorators.py, aea/helpers/base.py, strategy.ini, tests/test_cli/test_upgrade.py, tests/test_cli/tools_for_testing.py, tests/test_helpers/test_base.py
Make 'aea upgrade' to don't check aea version (#2133).
Addresses #2133
n/a
=> AEA-1208 Make 'aea upgrade' to don't check aea version (#2133)

setup.py
Add Python 3.9 as project classifier in `setup()`. This will be visible in the README badge in the next release.
https://img.shields.io/pypi/pyversions/aea
n/a
n/a
=> Add Python 3.9 as project classifier.

aea/cli/core.py, aea/cli/registry/fetch.py, aea/cli/utils/click_utils.py, tests/test_cli/test_fetch.py, tests/test_cli/test_misc.py
raise error if target folder exists on aea fetch
https://github.com/fetchai/agents-aea/issues/2127
=> AEA-1211 raise error if target folder exists on aea fetch

docs/multi-agent-manager.md
Update multi-agent manager docs to fix #2116
Fix #2116
n/a
=> Update multi-agent manager docs (#2116)

aea/cli/issue_certificates.py, aea/manager/project.py, scripts/whitelist.py, tests/test_cli/test_issue_certificates.py
Fix component configuration overrides when issuing certificates.
n/a
n/a
=> Fix component configuration overrides when issuing certificates

aea/__init__.py, aea/cli/create.py, aea/cli/upgrade.py, aea/cli/utils/package_utils.py, aea/helpers/base.py, aea/test_tools/test_cases.py, tests/test_cli/test_upgrade.py
Update 'aea_version' in non-vendor packages on `aea upgrade`.
Fixes AEA-1225, #2160
n/a
=> AEA-1225 Update 'aea_version' in non-vendor packages when upgrading

scripts/install.ps1
Microsoft visual studio build tools automatic installation for windows
=> ms vs build tools auto install

aea/configurations/manager.py, aea/configurations/validation.py, tests/test_configurations/test_manager.py, tests/test_configurations/test_validation.py
filter data for config manager overrides, to apply only updated values
=> AEA-1238 filter config overrides

setup.py
dotenv dependency moved to core
https://github.com/fetchai/agents-aea/issues/2179
=> dotenv dependency moved to core

aea/cli/issue_certificates.py, examples/tac.sh, examples/tac_local.sh
This PR updates the tac scripts to work with v0.9.
-
-
=> update tac scripts for v0.9

.spelling, docs/identity.md, docs/index.md, docs/ledger-integration.md, docs/oef-ledger.md, docs/questions-and-answers.md, docs/quickstart.md, docs/trust.md, docs/upgrading.md, docs/version.md, mkdocs.yml, tests/test_docs/test_bash_yaml/md_files/bash-ledger-integration.md, tests/test_docs/test_bash_yaml/md_files/bash-quickstart.md
Multiple updates to docs
Fixes #2078 
-
=> AEA-1242 Update Q&A section and ledger section in docs

.spelling, aea/aea_builder.py, aea/agent_loop.py, aea/helpers/async_utils.py, docs/aea-vs-mvc.md, docs/core-components-1.md, docs/core-components-2.md, docs/generic-skills-step-by-step.md, docs/glossary.md, docs/index.md, docs/quickstart.md, docs/simple-oef.md, docs/skill-guide.md, docs/upgrading.md
This PR adds further improvements to the beginner guides and ensures all info is up-to-date in them.
#2078
-
=> AEA-1242 Improve beginner guides in docs

aea/abstract_agent.py, aea/aea.py, aea/agent.py, aea/multiplexer.py, aea/runtime.py, benchmark/framework/aea_test_wrapper.py, docs/cli-vs-programmatic-aeas.md, tests/test_aea.py, tests/test_docs/test_cli_vs_programmatic_aeas/programmatic_aea.py, tests/test_multiplexer.py, tests/test_runtime.py, tests/test_skills/test_base.py, tests/test_skills/test_error.py
multiplexer/agent/connections refactoring
=> AEA-941 multiplexer/agent/connections refactoring

.github/workflows/workflow.yml
Update `integration_checks_ledger` stage in CI by adding a `fetchcli` installation step.
n/a
n/a
=> Add `fetchcli` installation in ledger CI

tests/test_packages/test_connections/test_p2p_libp2p/test_fault_tolerance.py
Fix libp2p fault tolerance tests
n/a
n/a
=> Fix libp2p fault tolerance tests

aea/launcher.py, aea/protocols/dialogue/base.py, tests/test_protocols/test_dialogue/test_base.py
get_dialogue_from_label refactoring
https://github.com/fetchai/agents-aea/issues/2185
=> [AEA-1244] get_dialogue_from_label refactoring

aea/crypto/cosmos.py, aea/protocols/dialogue/base.py, aea/protocols/generator/base.py, tests/test_configurations/test_base.py, tests/test_protocols/test_base.py, tests/test_protocols/test_dialogue/test_base.py, tests/test_registries/test_base.py
This PR plugs miscellaneous test gaps and addresses #2128 
#2128
-
=> AEA-1268 Feature/misc

docs/app-areas.md, docs/identity.md, docs/index.md, docs/language-agnostic-definition.md, docs/oef-ledger.md, docs/trust.md, docs/vision.md
This PR updates documentation as part of a docs review. It covers the `concepts` subpages.
=> Documentation update: Concepts

.github/workflows/workflow.yml, aea/cli/launch.py, aea/cli_gui/__init__.py, aea/helpers/multiple_executor.py, aea/launcher.py, aea/manager/manager.py, scripts/NOTES.md, tests/common/docker_image.py, tests/test_aea.py, tests/test_helpers/test_exec_timeout.py, tests/test_launcher.py, tests/test_multiplexer.py, tests/test_test_tools/test_test_cases.py
This PR addresses a few issues with threads management.
-
-
=> AEA-1270 Join threads where it is missing

scripts/install.sh
fixes for mac os install script
=> fixes for mac os install script

aea/aea_builder.py, aea/cli/issue_certificates.py, aea/configurations/base.py, aea/configurations/schemas/aea-config_schema.json, docs/config.md, tests/data/aea-config.example.yaml, tests/test_docs/test_bash_yaml/md_files/bash-config.md
Add "data_dir" optional field in AEA configuration.
Continuation of #2155
n/a
=> Add "data_dir" optional field in AEA configuration.

aea/components/loader.py, tests/test_components/test_loader.py
error msg fix on package import failed
https://github.com/fetchai/agents-aea/issues/2191
=> [AEA-1287] error msg fix on package import failed

aea/helpers/search/models.py
Disable 'no-member' in 'aea/helpers/search/models.py'.
n/a
n/a
=> disable 'no-member' in 'aea/helpers/search/models.py'

aea/manager/manager.py, tests/test_manager/test_manager.py
Addresses added to list_agents_info method. AEA-1295
=> AEA-1306 Addresses added to list_agents_info method. AEA-1295

aea/aea_builder.py, aea/cli/utils/config.py, aea/cli/utils/decorators.py, aea/configurations/validation.py, tests/test_cli/test_add/test_protocol.py, tests/test_cli/test_run.py, tests/test_configurations/test_aea_config.py, tests/test_configurations/test_loader.py
Improve configuration validation error messages
fix #2176
n/a
=> AEA-1304 Improve configuration validation error messages

aea/manager/project.py, tests/test_manager/test_manager.py
mam agent auto create private keys if needed
=> AEA-1307 mam agent auto create private keys if needed

aea/aea.py, aea/cli/upgrade.py, aea/skills/tasks.py, tests/conftest.py, tests/test_configurations/test_base.py, tests/test_crypto/test_helpers.py, tests/test_helpers/test_base.py, tests/test_multiplexer.py
This PR plugs a few holes in the coverage.
-
-
=> AEA-1308 Fix coverage holes in aea core

aea/protocols/generator/base.py, aea/protocols/generator/common.py, tests/test_protocols/test_generator/test_common.py
This PR cleans up protolint part of protocol generator:
* Adds protolint configuration to command execution
* Removes certain parts of its output (the indentation automatic fixes)
* Cleans up the code (in line with other similar functionality in the generator)
=> AEA-1292 Protolint cleanup

README.md
=> Update guidance regarding go development

docs/upgrading.md
Update upgrading.md (after #2112 and #2289)
- add instructions regarding the 'dependencies' field in 'aea-config.yaml';
- add instructions regarding crypto plug-ins.
n/a
n/a
=> Update upgrading.md (after #2112 and #2289)

aea/multiplexer.py, tests/test_multiplexer.py
fix for sync multiplexer reconnect
=> [AEA-1314] fix for sync multiplexer reconnect

aea/configurations/base.py, docs/car-park-skills.md, docs/cli-vs-programmatic-aeas.md, docs/erc1155-skills.md, docs/generic-skills.md, docs/ml-skills.md, docs/oracle-demo.md, docs/orm-integration.md, docs/p2p-connection.md, docs/skill-guide.md, docs/tac-skills-contract.md, docs/tac-skills.md, docs/wealth.md, docs/weather-skills.md, tests/test_crypto/test_registry/test_crypto_registry.py, tests/test_docs/test_bash_yaml/md_files/bash-car-park-skills.md, tests/test_docs/test_bash_yaml/md_files/bash-erc1155-skills.md, tests/test_docs/test_bash_yaml/md_files/bash-generic-skills.md, tests/test_docs/test_bash_yaml/md_files/bash-ml-skills.md, tests/test_docs/test_bash_yaml/md_files/bash-oracle-demo.md, tests/test_docs/test_bash_yaml/md_files/bash-orm-integration.md, tests/test_docs/test_bash_yaml/md_files/bash-p2p-connection.md, tests/test_docs/test_bash_yaml/md_files/bash-tac-skills-contract.md, tests/test_docs/test_bash_yaml/md_files/bash-tac-skills.md, tests/test_docs/test_bash_yaml/md_files/bash-wealth.md, tests/test_docs/test_bash_yaml/md_files/bash-weather-skills.md, tests/test_packages/test_skills_integration/test_thermometer.py, tests/test_packages/test_skills_integration/test_weather.py
First update of 'from scratch' instructions for crypto plugins.
n/a
n/a
=> First update of 'from scratch' instructions for crypto plugins

benchmark/checks/check_mem_usage.py, benchmark/checks/check_multiagent.py, benchmark/checks/check_multiagent_http_dialogues.py, benchmark/checks/check_proactive.py, benchmark/checks/check_reactive.py, benchmark/checks/utils.py
=> AEA-1343 fix benchmark checks

aea/cli/upgrade.py
Ignore packages of which we cannot find newer version in 'aea upgrade'.
Fix #2313
n/a
=> AEA-1358 Ignore packages of which we cannot find newer version in 'aea upgrade'

aea/aea_builder.py
Consider agent PyPI dependencies in AEA builder
n/a
n/a
=> Consider agent PyPI dependencies in AEA builder

docs/upgrading.md, plugins/aea-ledger-cosmos/setup.py, plugins/aea-ledger-ethereum/setup.py, plugins/aea-ledger-fetchai/setup.py, scripts/update_plugin_versions.py
Add a script to bump plug-in version numbers throughout the repository.
n/a
n/a
=> AEA-1367 Script to bump plugins

.github/workflows/codeql-analysis.yml, .github/workflows/workflow.yml, tests/conftest.py, tests/test_packages/test_connections/test_ledger/test_ledger_api.py
This PR adds a full coverage report to the output in coverage checks.
Replaces fix/coverage branch, #1999 , replaces #2344
-
=> Add full coverage report output in coverage check

aea/helpers/pipe.py, tests/conftest.py
Don't bind sockets to all network interfaces.
n/a
n/a
=> AEA-1376 Don't bind sockets to all network interfaces

.github/workflows/workflow.yml, scripts/check_imports_and_dependencies.py, setup.py, tox.ini
=> AEA-1404 Fix/imports and deps

aea/crypto/plugin.py, aea/manager/manager.py, plugins/aea-cli-ipfs/aea_cli_ipfs/core.py, plugins/aea-cli-ipfs/aea_cli_ipfs/ipfs_utils.py
This PR ensures new plugins are registered each time a project's dependencies are installed.
-
-
=> Fix plugin loading in manager

tests/test_test_tools/test_test_cases.py
Increase coverage in test_tools/test_cases
n/a
n/a
=> Increase coverage in test_tools/test_cases

aea/multiplexer.py, tests/test_multiplexer.py
multiplexer: timeouts for connection methods
=> [AEA-1379] multiplexer: timeouts for connection methods

aea/identity/base.py, tests/conftest.py, tests/test_examples/test_http_client_connection_to_aries_cloud_agent.py, tests/test_multiplexer.py, tests/test_packages/test_connections/test_http_server/test_http_server_and_client.py, tests/test_packages/test_connections/test_p2p_libp2p/test_errors.py, tests/test_packages/test_connections/test_p2p_libp2p_client/test_errors.py, tests/test_packages/test_connections/test_soef/test_soef.py, tests/test_packages/test_connections/test_soef/test_soef_integration.py, tests/test_packages/test_connections/test_webhook/test_webhook.py
Add validation of parameter `name` in `Identity` constructor.
n/a
n/a
=> AEA-1416 Add validation of name in 'Identity' constructor

scripts/acn/Dockerfile, scripts/acn/Dockerfile.dev, scripts/acn/README.md
This PR updates the ACN script which did no longer match the folder structure of the p2p_libp2p connection package.
-
-
=> AEA-1422 Update acn scripts

docs/logging.md
Update example with log streaming via the browser.
n/a
n/a
=> Update example with log streaming via browser.

aea/agent_loop.py, aea/cli/remove.py, aea/crypto/plugin.py, aea/multiplexer.py, plugins/aea-ledger-cosmos/aea_ledger_cosmos/cosmos.py, plugins/aea-ledger-ethereum/tests/test_ethereum.py, plugins/aea-ledger-fetchai/aea_ledger_fetchai/_cosmos.py, plugins/aea-ledger-fetchai/tests/test_fetchai.py, tests/test_cli/test_remove/test_base.py, tests/test_manager/test_manager.py, tests/test_multiplexer.py
coverage fixes
fixes for cli remove command #2360
fix for mam plugins load after dependencies installed
=> [AEA-1420] [AEA-1424] [AEA-1415] [AEA-1414] Fix/misc coverage tests

docs/12-factor.md, mkdocs.yml
Add a documentation page on how the AEA framework allows the achievement of the Twelve-Factors for AEA projects.
n/a
n/a
=> AEA-968 12-factor for AEAs

.pylintrc, aea/aea.py, aea/aea_builder.py, aea/agent.py, aea/configurations/base.py, aea/configurations/schemas/aea-config_schema.json, aea/configurations/schemas/definitions.json, aea/runtime.py, tests/test_configurations/test_aea_config.py
=> AEA-1423 runtime_mode for aea config

tests/test_cli/test_launch_end_to_end.py
storage enabled for end to end test
=> AEA-1377 storage enabled for end to end test

aea/manager/manager.py, plugins/aea-ledger-cosmos/setup.py, plugins/aea-ledger-ethereum/setup.py, plugins/aea-ledger-fetchai/setup.py, tests/test_cli/test_upgrade.py
Fix project loading in manager
This PR fixes various issues noted during RC1 release and when using RC1.
-
-
=> AEA-1450 Fix dependencies in plugins

docs/http-connection-and-skill.md
This PR simply updates the HTTP guide in docs with details on HTTP client connection.
=> AEA-1407 Update HTTP guide

tests/test_components/test_base.py
extra test for package loading for package persistence
=> AEA-1438 extra test for package loading for package persistence

.gitignore, deploy-image/.aea/cli_config.yaml, deploy-image/Dockerfile, deploy-image/README.md, deploy-image/build.sh, deploy-image/docker-env.sh, deploy-image/entrypoint.sh, deploy-image/packages/__init__.py, deploy-image/scripts, docs/deployment.md, tests/test_docs/test_bash_yaml/md_files/bash-deployment.md
This PR proposes an update to the deploy image to make it useful. It creates a self-contained example that can be downloaded and used for single AEA deployment out of the box.
-
-
=> AEA-1451 Initial attempt to fix deploy image

aea/aea_builder.py, aea/cli/run.py, aea/exceptions.py, tests/test_aea_builder.py
Do minor fixes after removal of key auto-generation (replacement of #2384).
- at build time, in case the default ledger is not in the available wallet addresses, raise an error.
replaces #2384 
n/a
=> Minor fixes after removal of key auto-generation (replacement of #2384)

aea/aea_builder.py, aea/configurations/base.py, aea/configurations/data_types.py, aea/crypto/registries/base.py, aea/helpers/base.py, tests/test_aea_builder.py
Check `default_ledger` and `required_ledgers` are of the right format.
#2401
-
=> AEA-1409 Enforce regex across ledger ids

tests/test_cli/test_local_registry_update.py, tests/test_cli/test_run.py
Rewrite a flaky test `tests.test_cli.TestRunFailsWhenConnectionNotDeclared`.
It fails often on CI runs: https://github.com/fetchai/agents-aea/pull/2369/checks?check_run_id=2132924009
n/a
n/a
=> AEA-1405 rewrite flaky test

deploy-image/README.md, docs/quickstart.md, tests/test_docs/test_quickstart.py
This PR applies minor changes to the quickstart.md page of the documentation. 
=> AEA-1466 Review quickstart docs

.github/workflows/workflow.yml, tox.ini
=> AEA-1471 CI plugins install check

benchmark/checks/data/2021.04.01_v1_benchmark.txt
=> benchmark report for v1

libs/go/aealite/README.md, libs/go/aealite/agent.go, libs/go/aealite/agent_test.go, libs/go/aealite/connections/connections.go, libs/go/aealite/connections/p2pclient.go, libs/go/aealite/connections/p2pclient_test.go, libs/go/aealite/wallet/utils.go, libs/go/aealite/wallet/wallet.go, libs/go/aealite/wallet/wallet_test.go
Update example and minor fixes to aealite
n/a
n/a
=> AEA-1473 Update example and minor fixes to aealite

tests/test_packages/test_skills/test_registration_aw1/__init__.py, tests/test_packages/test_skills/test_registration_aw1/intermediate_class.py, tests/test_packages/test_skills/test_registration_aw1/test_behaviours.py, tests/test_packages/test_skills/test_registration_aw1/test_dialogues.py, tests/test_packages/test_skills/test_registration_aw1/test_handlers.py, tests/test_packages/test_skills/test_registration_aw1/test_strategy.py
This PR adds tests for registration_aw1 skill.
=> AEA-1488 Tests for registration_aw1 skill

aea/protocols/dialogue/base.py
in `DialogueLabel.__eq__`, compare the label fields rather than the hash of the label fields
n/a
n/a
=> fix: dialogue label equals

libs/go/aealite/go.mod, libs/go/aealite/go.sum, libs/go/aealite/helpers/base.go, libs/go/aealite/helpers/base_test.go, libs/go/aealite/protocols/dialogue.go, libs/go/aealite/protocols/dialogue_label.go, libs/go/aealite/protocols/dialogue_label_test.go, libs/go/aealite/protocols/dialogue_test.go, libs/go/aealite/protocols/message.go, libs/go/aealite/protocols/message_test.go
Implement the dialogue type in aealite.
n/a
n/a
=> AEA-1401 implement dialogue type in aealite

examples/tac_deploy/entrypoint.sh, examples/tac_deploy/tac-deployment.yaml
This PR modifies the configuration used for the tac deployment.
-
-
=> feat: extend logging and config of tac deployment

libs/go/aealite/protocols/dialogue.go, libs/go/aealite/protocols/dialogue_label.go, libs/go/aealite/protocols/dialogue_test.go, libs/go/aealite/protocols/dialogues.go, libs/go/aealite/protocols/message.go, libs/go/aealite/protocols/message_test.go, libs/go/aealite/protocols/storage_test.go
Add tests to dialogue-related modules in AEALite.
n/a
n/a
=> AEA-1401 Dialogue tests in AEALite

aea/cli/issue_certificates.py, aea/manager/project.py
This PR fixes an issue with password propagation.
-
-
=> AEA-1536 feat: propagate password in manager issue certificates

Makefile, scripts/RELEASE_PROCESS.md, setup.cfg, setup.py
=> AEA-1546, AEA-1553 multiplatform wheel build

.github/workflows/publish.yaml, scripts/acn/build_upload_img.sh
The framework should be deployed to the respective environment (in this case, staging) whenever a branch is merged to develop.
The deployment would be done on `sandbox-london-b` cluster (`agents-dht-testnet` namespace).
Deployment could be accessed through:
- agents-dht-testnet.sandbox-london-b.fetch-ai.com
- update secrets to use correct peerid and privkeys (currently, demo secrets from the helm-charts are used)
- once this staging deployment procedure is tested and verified then replicate this flow for prod deployments
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what …
=> feat: staging environment deployment automation

tests/test_packages/test_connections/test_p2p_libp2p/test_communication.py
Add decorator `libp2p_log_on_failure_all` to `TestLibp2pEnvelopeOrder` class.
n/a
n/a
=> test: update p2p_libp2p test

.github/workflows/publish.yaml
=> Added steps for prod deployment

aea/skills/base.py
Fix 'not declared in configuration file' warning for 'tac_controller_contract' agent
n/a
n/a
=> AEA-1556 Update aea.skills.base.py on skill loading

aea/aea_builder.py, tests/test_aea_builder.py
Add log info message if loaded component is abstract
Fixes #2474
n/a
=> AEA-1574 add log info message if loaded component is abstract

aea/cli/utils/package_utils.py, tests/test_cli/test_push.py, tests/test_cli/test_utils/test_utils.py
Improve some unhelpful error messages listed in #2482
Fix #2482
n/a
=> AEA-1573 Improve unhelpful error messages (#2482)

aea/test_tools/test_cases.py, tests/conftest.py, tests/test_cli/test_add_key.py, tests/test_cli/test_generate_key.py, tests/test_cli/test_generate_wealth.py, tests/test_cli/test_get_address.py, tests/test_manager/test_manager.py
add tests on MAM with password
Fix #2471
n/a
=> AEA-1575 add tests on MAM with password

docs/quickstart.md, scripts/install.ps1
win install script: golang and gcc addded
#2520
=> AEA-1585 win install script: golang and gcc addded

aea/cli/push.py, tests/test_cli/test_push.py
aea push --local: fix for proper author
https://github.com/fetchai/agents-aea/issues/2534
=> aea push --local: fix for proper author

aea/cli/get_multiaddress.py, aea/test_tools/generic.py, tests/test_cli/test_get_multiaddress.py
fix for aea get-multiaddress
#2530
=> AEA-1600 fix for aea get-multiaddress

aea/manager/manager.py, tests/test_manager/test_manager.py
Fill coverage gap in manager due to #2523 
n/a
n/a
=> Fill gaps in manager coverage

.spelling, HISTORY.md, docs/deployment.md, docs/quickstart.md, docs/upgrading.md
This PR: add history items, update upgrade guide, fix spelling
-
-
=> AEA-1591 chore: add history items, update upgrade guide, fix spelling

tests/test_manager/test_manager.py
Fill coverage gap in manager.py (due to #2550).
n/a
n/a
=> Fill coverage gap in manager.py (due to #2550)

docs/http-connection-and-skill.md, tests/test_docs/helper.py, tests/test_docs/test_bash_yaml/md_files/bash-http-connection-and-skill.md, tests/test_docs/test_docs_http_connection_and_skill.py
Fix tutorial for HTTP connection and skill (#2549)
Fix #2549
n/a
=> AEA-1616 Fix tutorial for HTTP connection and skill (#2549)

.github/workflows/workflow.yml, tests/common/docker_image.py, tests/conftest.py, tests/test_packages/test_skills_integration/test_tac.py
This PR adds a fixture that can be added to tests to run an isolated SOEF docker instance. It also uses the fixture on the tac integration test.
NOTE: Tests using the new fixture do NOT run on CI because of authentication issue.
Need to address authentication issue on google cloud on which the SOEF docker is hosted to be able to run the tests in CI and merge this PR.
=> AEA-1630, AEA-1634 SOEF Dockerised

docs/core-components-2.md
This PR adds more information regarding private key usage in AEAs to the introductory section.
#2320
=> AEA-1611 docs: add more context on private keys

tests/test_packages/test_connections/test_p2p_libp2p/test_public_dht.py
libp2p node public dht tests fix
=> libp2p node public dht tests fix

aea/cli/scaffold.py, docs/decision-maker.md, tests/test_docs/test_bash_yaml/md_files/bash-decision-maker.md
This PR fixes issues reported here: https://github.com/fetchai/agents-aea/issues/2583
https://github.com/fetchai/agents-aea/issues/2583
-
=> AEA-1697 fix: scaffolding of error and decision maker handlers

.github/workflows/publish.yaml
GH action files were outdated.
Fixes it.
-
=> fix: github actions file fix

tests/conftest.py
fix for pytest flaky crash on logging dictConfig
https://github.com/fetchai/agents-aea/issues/2431
=> fix for pytest flaky crash on logging dictConfig

docs/http-connection-and-skill.md
http skills docs updated according to last package updates
=> http skills docs updated according to last package updates

aea/cli/run.py, tests/test_cli/test_run.py
exclude connections flag for aea run
https://github.com/fetchai/agents-aea/issues/1652
=> exclude connections flag for aea run

aea/cli/registry/utils.py
better error reporing for aea registry requests
https://github.com/fetchai/agents-aea/issues/1987
------
and [`aea-user`](../user-image/README.md#publish))
=> better error reporing for aea registry requests

aea/cli/registry/push.py, aea/cli/registry/utils.py, aea/helpers/http_requests.py, tests/test_cli/test_registry/test_push.py, tests/test_cli/test_registry/test_utils.py
check dependencies present in registry on package push
https://github.com/fetchai/agents-aea/issues/1859
------
and [`aea-user`](../user-image/README.md#publish))
=> check dependencies present in registry on package push

tests/test_cli/test_registry/test_push.py, tests/test_cli/test_registry/test_utils.py
=> small tests fixes

plugins/aea-ledger-cosmos/aea_ledger_cosmos/cosmos.py, plugins/aea-ledger-fetchai/aea_ledger_fetchai/_cosmos.py
=> Fixed maximum Cosmos/Fetch limit after stargateworld-3 update

tests/test_packages/test_connections/test_oef/test_models.py
This PR adds more soef models NOT operator tests.
=> Add more soef models NOT tests

.github/workflows/upload_docker_images.yaml, develop-image/Dockerfile
docker images automation for CI
------
and [`aea-user`](../user-image/README.md#publish))
=> docker images automation for CI

tests/common/docker_image.py, tests/conftest.py
docker container start fix
- [] New feature (non-breaking change which adds functionality)
------
and [`aea-user`](../user-image/README.md#publish))
=> docker container start fix

.github/workflows/workflow.yml, Pipfile, plugins/aea-ledger-cosmos/setup.py, plugins/aea-ledger-fetchai/setup.py, tox.ini
=> cosmpy version restriction >=0.2.0,<0.3.0

.github/workflows/workflow.yml
=> pin ci github actions/setup-python to v3 instead of master

tests/test_packages/test_skills_integration/test_aries_demo.py
------
(check the READMEs of [`aea-develop`](https://github.com/fetchai/agents-aea/blob/master/develop-image/README.md#publi …
=> small fixes for aries demo

docs/ml-skills.md
Added preliminary commands for TensorFlow in ML skills demo
=> Add preliminary commands for tensorflow 

docs/gym-skill.md
Add instructions for grabbing the gym example files into the directory from the "gym example" demo into the "gym demo".
=> Update gym skills readme

docs/gym-skill.md
------
(check the READMEs of [`aea-develop`](https://github.com/fetchai/agents-aea/blob/master/develop-image/README.md#publi …
=> docs gym skill fix

plugins/aea-cli-ipfs/setup.py, plugins/aea-ledger-ethereum/setup.py, poetry.lock, pyproject.toml
------
(check the READMEs of [`aea-develop`](https://github.com/fetchai/agents-aea/blob/master/develop-image/README.md#publi …
=> chore: web3 and ipfsclient dependencies updated

.github/workflows/workflow.yml
This PR fixes workflow checks not run on release PRs.
=> fix: workflow

poetry.lock
=> build: update lock file

AUTHORS.md, CODE_OF_CONDUCT.md, README.md, scripts/RELEASE_PROCESS.md
This PR makes minor edits to the repo documentation according to the company policy. 
=> docs: minor edits

tests/test_aea/test_cli/test_upgrade.py
Fix cli upgrade tests: `tests/test_aea/test_cli/test_upgrade.py`
=> fix: cli upgrade test

pyproject.toml
Update project's meta-data in `pyproject.toml`.
- [x ] I have based my branch, and I am making a pull request against, the `develop` branch.
=> Build: update project metadata
